### ISSUE TITLE
xiwi: holding the "down" button on the keyboard only causes discrete scrolling, does not scroll continuously

### ISSUE THREAD

**Issue by zymbolic** [dnschneid/crouton#1472] opened 2015-03-05 05:41 UTC
**Bug Description:**
Holding the down button on the keyboard only produces a discrete scrolling event
**Expected behaviour:**
the document should continue to scroll down as long as the down button is held
**Remarks:**
Holding the up button works correctly and will scroll up as long as the up button is held
This bug is present not only in scrolling documents, but also in text selection
**Steps to reproduce:**
1. Enter chroot
2. Open a document that extends past the visible portion on the screen (I noticed this bug in Okular pdf reader, but was able to reproduce in Firefox and Kate text editor)
3. Press and hold the "down" button on the keyboard
**Work Around:**
Press the down button multiple times until you've reached the desired location
**Installed Targets:**
precise, xfce, extension, xiwi
**hardware:**
Acer C720

**Comment by smibarber** [comment] 2015-03-06 23:08
@drinkcat can probably shed some more light on if this is expected behavior or not.

**Comment by drinkcat** [comment] 2015-03-14 15:09
I thought this was fixed by 16ed10fca06b5633fb1b01f8a4ac9680f6a1e794... (admitedly, only tested on trusty, will look at precise...)

**Comment by drinkcat** [comment] 2015-03-14 16:06
I can't reproduce on precise/peppy/no freon:
```
crouton: version 1-20150304145447~master:550afdb3
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi
host: version 6680.64.0 (Official Build) stable-channel peppy
```

@zymbolic: Can you provide the output of `croutonversion`?

**Comment by DennisLfromGA** [comment] 2016-10-09 23:16
Closing. Please re-open if this issue is still a concern.

**Closed by DennisLfromGA** 2016-10-09 23:16 UTC
Labels: bug
