### ISSUE TITLE
Static Sound

### ISSUE THREAD

**Issue by helpdeskdan** [dnschneid/crouton#1590] opened 2015-04-07 22:13 UTC
The static sound issue seems to be back, previously experienced only on the beta channel.  Trusty, lxde latest chroot.  The sound gets static/garbled about a minute after it starts to play.  And, when you hit stop, the static continues for a sec after the music stops.  I don't see high cpu or anything when it occurs.  What information can I provide to assist?

**Comment by voteforcoffee** [comment] 2015-06-18 12:24
Can confirm this if this is the same as issues #791 and #792, which also have new reports from users that the problem is back again. Chrome stable channel, trusty, all updated to newest version, for me it happens on an Acer C720 with Unity desktop.

Hope @dnschneid or another dev looks at this soon, it's making crouton unusable for any multimedia task (as other people have said it's system wide, happens in games, when playing videos, etc.) and the problem has been there for months now according to some users (personally I only noticed it a month ago but I probably just hadn't done any updates for a while).

Haven't seen any responses from a dev in any of the issues yet since the problem popped up again, would be nice to get an update on this, if someone is already trying to figure this out or if devs aren't aware of the problem yet. I'm sure everyone is busy enough as it is, but this bug is a showstopper for what appears to be many users, so a status update would be much appreciated.

**Comment by helpdeskdan** [comment] 2015-06-19 02:39
Sounds like it, thanks.  I wish it would get some traction, although I hate to sound ungrateful to unpaid devs.

**Comment by voteforcoffee** [comment] 2015-06-19 09:25
@helpdeskdan Absolutely and it might sound like it sometimes that a user is ungrateful, but I am very grateful, without Crouton I wouldn't have bought a Chromebook in the first place, it's an essential piece of software to me, the devs' work is greatly appreciated. Which is also why I hope this gets fixed soon since right now, aside from doing programming work where I only need a working text editor and no sound, it has become useless for me and this is my only computer right now since my desktop PC has passed on which makes it even worse for me.

**Comment by helpdeskdan** [comment] 2015-06-21 03:36
You might be able to rewrite the Bios and use native Linux.  I use crouton on chromebox only.  (Great success with Chromebook bios, but bricked a stumpy Chromebox)

**Comment by dnschneid** [comment] 2015-06-23 04:40
Could you both post the output of croutonversion?

**Comment by voteforcoffee** [comment] 2015-06-23 08:47
Here you go:

```
(trusty)chris@localhost:~$ croutonversion
crouton: version 1-20150604154515~master:91b3e350
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,xiwi,extension,keyboard,chrome,unity
host: version 6946.58.0 (Official Build) stable-channel peppy
kernel: Linux localhost 3.8.11 #1 SMP Sat Jun 13 02:42:30 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

Thanks for looking into this!

**Comment by Lollerskater** [comment] 2015-06-24 09:09
Experiencing the same issue. Didn't see a reply from @helpdeskdan so thought I'd contribute my output from croutonversion:
```
crouton: version 1-20150617163120~master:5c73c9fd
release: trusty
architecture: amd64
xmethod: xorg
targets: unity,touch,keyboard
host: version 6946.58.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Sat Jun 13 02:42:30 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

**Comment by dnschneid** [comment] 2015-06-25 03:43
Can you all run `pgrep -c pulseaudio` and let me know if that's non-zero?

**Comment by dnschneid** [comment] 2015-06-25 04:04
Might be an issue only on stable.  Would one of you mind upgrading to beta to see if it works?  I can't repro on 45 at least.

**Comment by voteforcoffee** [comment] 2015-06-25 12:20
I'll give it a try. Do I have to re-enable developer mode to make crouton work again once I go back to the stable channel after trying this out? Or is there anything else I need to think of (never switched channels before)? The help text says all files get deleted when switching from an experimental to the stable channel, so it does sound like that might be the case.

**Comment by helpdeskdan** [comment] 2015-06-25 16:06
It was an issue on the beta channel a long time ago, but then moved to the stable channel.  I've had it for months now through several updates.  It's strange, kind of like a static but also an echo in that it continues a second after you hit stop.  Much thanks dnschneid!

╭─dans@localhost  ~  
╰─$ croutonversion 
crouton: version 1-20150617163120~master:5c73c9fd
release: trusty
architecture: amd64
xmethod: xorg
targets: lxde
host: version 6946.58.0 (Official Build) stable-channel stumpy 
kernel: Linux localhost 3.4.0 #1 SMP Sat Jun 13 04:18:11 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
╭─dans@localhost  ~  
╰─$

**Comment by voteforcoffee** [comment] 2015-06-26 08:05
In case it helps, I've noticed that the audio in Chrome OS applications is also affected by the problem if Linux is running (was watching Twitch in Chrome OS and the sound became garbled). If I logout of Linux everything works fine again.

**Comment by drinkcat** [comment] 2015-06-30 09:53
Asked our local expert. This sounds very similar to a bug that was introduced in R43 (unfortunately the issue was filed on a private tracker so there isn't much I can share).

The issue was only fixed last week, and will be included in R45 from 7212.0.0 onwards, and R44 from 7077.66.0. There is no plan to backport to R43 (current stable). I don't think any beta/dev channel includes the fix yet, but it might be worth checking out beta/dev channels to see if the issue is fixed.

**Comment by voteforcoffee** [comment] 2015-07-04 16:43
@drinkcat The problem is still there on beta, although much alleviated when compared to stable (it's still very bad when running more demanding games). dnschneid couldn't reproduce the problem on the dev channel, so there it might be fixed.

**Comment by ahaym** [comment] 2015-07-15 23:43
I may have the same problem on R45 on 7262; audio is completely fine in ChromeOS. I have just updated my chroot as well. I use headphones and have my machine plugged in to a TV with both HDMI Audio and Video, and observe that the problem is somewhat fixed when I either manually select my headphones through cras_test_client or unplug the TV, though it does not disappear altogether.

**Comment by Lollerskater** [comment] 2015-07-28 08:27
For the record my findings, after latest ChromeOS update I got and updating my chroot:
```
crouton: version 1-20150716185530~master:aba2c948
release: trusty
architecture: amd64
xmethod: xorg
targets: unity,touch,keyboard
host: version 7077.95.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Jul 14 21:49:35 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
Problem unfortunately still seems to persist, despite @drinkcat 's indications. The following behavior seems the norm:
- sound will be fine for an undetermined time
- through no discernible trigger, as of yet, sound gets distorted to different degrees, but the static-sound of it is a constant factor
- pausing all sound output also halts the distortion, though it continues when playback is resumed
- sound will return to normal as intermittently as it distorts; using/starting another application which also produces sound seems to help, though I haven't been able to reproduce this 100%
- I echo @voteforcoffee 's statement however that it seems to happen far less frequent than before

**Comment by Lollerskater** [comment] 2015-08-10 08:17
Reporting in that with these versions:
```
crouton: version 1-20150730171703~master:f8fdfb0c
release: trusty
architecture: amd64
xmethod: xorg
targets: unity,touch,keyboard
host: version 7077.111.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Jul 28 15:00:32 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
... the problem seems to have disappeared almost entirely. There are some noticeable remaining artifacts, such as a "popping" sound where previously the sound would get distorted or a hickup when sound starts playing from another source, but these are a lot more tolerable than the static that it used to be.

I'd like to still perform some tests using video playback, which used to be the biggest offender, but perhaps someone else can also report on their findings regarding the current state of this issue?

**Comment by helpdeskdan** [comment] 2015-08-12 03:19
Checked for upgrade recently, still there, not triggered as often.

**Comment by helpdeskdan** [comment] 2015-09-10 23:18
I am on beta.  I had a couple of versions that would play directly through the internal, even if you had headphones attached.  BUT - as of today's beta, everything seems to work correct.

**Closed** 2016-10-11 22:34 UTC
Labels: audio, crosbug
