### ISSUE TITLE
can't startxfce4 (sid&stretch)  

### ISSUE THREAD

**Issue by swors** [dnschneid/crouton#3310] opened 2017-07-05 14:55 UTC
```
chronos@localhost / $ sudo edit-chroot -all
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20170619181610~master:980f090f
release: kali-rolling
architecture: amd64
targets: core
host: version 9592.42.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-14861-g70c266fc4519 #1 SMP PREEMPT Thu Jun 29 22:03:53 PDT 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
name: sid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sid...
crouton: version 1-20170619181610~master:980f090f
release: sid
architecture: amd64
xmethod: xorg
targets: xfce,core
host: version 9592.42.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-14861-g70c266fc4519 #1 SMP PREEMPT Thu Jun 29 22:03:53 PDT 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/sid...
name: stretch
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/stretch...
crouton: version 1-20170619181610~master:980f090f
release: stretch
architecture: amd64
xmethod: xorg
targets: xfce,core
host: version 9592.42.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-14861-g70c266fc4519 #1 SMP PREEMPT Thu Jun 29 22:03:53 PDT 2017 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/stretch as another instance is using it.
```

#### Please describe your issue:
Can't startxfce4 , get these message
chronos@localhost / $ sudo enter-chroot -n sid startxfce4
Entering /mnt/stateful_partition/crouton/chroots/sid...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.18.0-14861-g70c266fc4519 #1 SMP PREEMPT Thu Jun 29 22:03:53 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=5c725308-cb72-a845-9df1-5d0581953249/PARTNROFF=1 hashtree=PARTUUID=5c725308-cb72-a845-9df1-5d0581953249/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=9ec0de4f3655ac5f1859ea660585fb96ef3f2ce9 salt=2db2ac1afb6b2355eec35ca5942bb12169757371f8492fbf9aaae507309b2909" noinitrd vt.global_cursor_default=0 kern_guid=5c725308-cb72-a845-9df1-5d0581953249 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic intel_idle.max_cstate=7  
Build Date: 15 March 2017  09:21:41PM
xorg-server 2:1.19.3-1 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Jul  5 22:53:14 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.

^C
Session terminated, terminating shell.../usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: unexpected signal 2
 ...terminated.
Unmounting /mnt/stateful_partition/crouton/chroots/sid...

**Comment by gfctam** [comment] 2017-07-07 01:28
[installkalilinuxinchromebook.docx](https://github.com/dnschneid/crouton/files/1129680/installkalilinuxinchromebook.docx)

follow the above instructions or look at this video https://www.youtube.com/watch?v=qjvD1dBZY4A to install kali linux on chromebook

**Comment by wallace11** [comment] 2017-07-07 10:37
I can confirm this issue with Stretch. 
Here's my Xorg log:
```
[   563.036] _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[   563.037] 
X.Org X Server 1.19.2
Release Date: 2017-03-02
[   563.037] X Protocol Version 11, Revision 0
[   563.037] Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
[   563.037] Current Operating System: Linux localhost 3.18.0-14593-g9c23f3f1b8d6 #1 SMP PREEMPT Thu Jun 22 14:34:07 PDT 2017 x86_64
[   563.037] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=1becd539-8ab2-c348-b66c-9ba3d448d844/PARTNROFF=1 hashtree=PARTUUID=1becd539-8ab2-c348-b66c-9ba3d448d844/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=eb11562e384419905fdd9a1139682f75c11350f1 salt=3c46d28958dfa1f70e6be1138617621384b229ee21c9796243ba005dfdf8a7a5" noinitrd vt.global_cursor_default=0 kern_guid=1becd539-8ab2-c348-b66c-9ba3d448d844 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic intel_idle.max_cstate=7  
[   563.037] Build Date: 03 March 2017  03:14:41PM
[   563.037] xorg-server 2:1.19.2-1 (https://www.debian.org/support) 
[   563.037] Current version of pixman: 0.34.0
[   563.037] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[   563.037] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[   563.037] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jul  7 19:26:26 2017
[   563.038] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   563.038] (==) No Layout section.  Using the first Screen section.
[   563.038] (==) No screen section available. Using defaults.
[   563.038] (**) |-->Screen "Default Screen Section" (0)
[   563.038] (**) |   |-->Monitor "<default monitor>"
[   563.038] (==) No device specified for screen "Default Screen Section".
	Using the first device section listed.
[   563.038] (**) |   |-->Device "Intel Graphics"
[   563.038] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[   563.039] (==) Automatically adding devices
[   563.039] (==) Automatically enabling devices
[   563.039] (==) Automatically adding GPU devices
[   563.039] (==) Max clients allowed: 256, resource mask: 0x1fffff
[   563.039] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[   563.039] 	Entry deleted from font path.
[   563.039] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	/usr/share/fonts/X11/100dpi/:unscaled,
	/usr/share/fonts/X11/75dpi/:unscaled,
	/usr/share/fonts/X11/Type1,
	/usr/share/fonts/X11/100dpi,
	/usr/share/fonts/X11/75dpi,
	built-ins
[   563.039] (==) ModulePath set to "/usr/lib/xorg/modules"
[   563.039] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[   563.039] (II) Loader magic: 0x5be1e60ede00
[   563.039] (II) Module ABI versions:
[   563.039] 	X.Org ANSI C Emulation: 0.4
[   563.039] 	X.Org Video Driver: 23.0
[   563.039] 	X.Org XInput driver : 24.1
[   563.039] 	X.Org Server Extension : 10.0
[   563.069] (EE) systemd-logind: failed to get session: Launch helper exited with unknown return code 1
[   563.070] (II) xfree86: Adding drm device (/dev/dri/card0)
[   563.071] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
[   563.197] (--) PCI:*(0:0:2:0) 8086:1906:8086:2015 rev 7, Mem @ 0xd0000000/16777216, 0xc0000000/268435456, I/O @ 0x00001c00/64
[   563.197] (II) LoadModule: "glx"
[   563.197] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[   563.200] (II) Module glx: vendor="X.Org Foundation"
[   563.200] 	compiled for 1.19.2, module version = 1.0.0
[   563.200] 	ABI class: X.Org Server Extension, version 10.0
[   563.200] (II) LoadModule: "intel"
[   563.200] (II) Loading /usr/lib/xorg/modules/drivers/intel_drv.so
[   563.215] (II) Module intel: vendor="X.Org Foundation"
[   563.215] 	compiled for 1.19.0, module version = 2.99.917
[   563.215] 	Module class: X.Org Video Driver
[   563.215] 	ABI class: X.Org Video Driver, version 23.0
[   563.215] (II) intel: Driver for Intel(R) Integrated Graphics Chipsets:
	i810, i810-dc100, i810e, i815, i830M, 845G, 854, 852GM/855GM, 865G,
	915G, E7221 (i915), 915GM, 945G, 945GM, 945GME, Pineview GM,
	Pineview G, 965G, G35, 965Q, 946GZ, 965GM, 965GME/GLE, G33, Q35, Q33,
	GM45, 4 Series, G45/G43, Q45/Q43, G41, B43
[   563.215] (II) intel: Driver for Intel(R) HD Graphics
[   563.215] (II) intel: Driver for Intel(R) Iris(TM) Graphics
[   563.215] (II) intel: Driver for Intel(R) Iris(TM) Pro Graphics
[   563.215] (EE) 
Fatal server error:
[   563.215] (EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
[   563.215] (EE) 
[   563.215] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[   563.215] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[   563.216] (EE) 
[   563.216] (WW) xf86CloseConsole: KDSETMODE failed: Bad file descriptor
[   563.216] (WW) xf86CloseConsole: VT_GETMODE failed: Bad file descriptor
[   563.216] (EE) Server terminated with error (1). Closing log file.

```

**Comment by zguithues** [comment] 2017-07-07 14:08
I was fighting with this same thing last night!  The issue is a package called xserver-xorg-legacy
detailed here #2875 

A quick fix is to enter the chroot with
`sudo enter-chroot -n CHROOTNAME`
and run
`sudo apt remove xserver-xorg-legacy`

xfce will start after this.

As far as i can tell, this issue effects Stretch, Sid, & Kali-Rolling

**Comment by swors** [comment] 2017-07-07 14:40
@zguithues 
I've tried this solution. It does work, but a new problem is that it doesn't resume after lid and open laptop again.

**Comment by swors** [comment] 2017-07-07 14:46
It seems to be ok after "sudo apt remove --purge xserver-xorg-legacy; sudo apt remove --purge xfce4-power-manager"

**Comment by zguithues** [comment] 2017-07-07 15:58
Thanks for the tip @swors !

I hope we can get a fix for this issue that's less hacky than current workarounds.  I trust @dnschneid has a plan as this is more of a debian issue than an xfce issue.

**Comment by Carl393** [comment] 2017-07-08 07:28
THANK GOODNESS I FOUND THIS POST! THANK YOU SO MUCH SWORS!

**Comment by formatCvt** [comment] 2017-07-09 13:15
same error with `gnome-desktop` and there is no `xserver-xorg-legacy`

**Comment by swors** [comment] 2017-07-09 15:04
@formatCvt 
I installed the stretch/gnome chroot a few hour ago and I didn't have the problem.

**Comment by formatCvt** [comment] 2017-07-11 12:09
@swors i do this:
```
sudo sh ~/Downloads/crouton -t gnome-desktop
Downloading latest crouton installer...
######################################################################## 100.0%
Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading latest debootstrap...
2017-07-10 17:50:43 URL:https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [70014] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
....
....
....
Audio from the chroot will now be forwarded to CRAS (Chromium OS audio server),
through an ALSA plugin.

Future Chromium OS upgrades may break compatibility with the installed version
of CRAS. Should this happen, simply update your chroot.

You can flip through your running chroot desktops and Chromium OS by hitting
Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward.

You can start GNOME via the startgnome host command: sudo startgnome

Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Done! You can enter the chroot using enter-chroot.

```
and get this:
```
chronos@localhost / $ sudo startgnome
Entering /mnt/stateful_partition/crouton/chroots/xenial...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-45-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-14861-g70c266fc4519 #1 SMP PREEMPT Thu Jun 29 22:04:02 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=8de8b014-b4ca-dd42-88e2-57f43f00e544/PARTNROFF=1 hashtree=PARTUUID=8de8b014-b4ca-dd42-88e2-57f43f00e544/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=3b54ee9600675cf789387d0d4d82ba125409e1d4 salt=d8283ef47a7665ea9896a642c81b9e9b1807f438e007876c230bce074093e87c" noinitrd vt.global_cursor_default=0 kern_guid=8de8b014-b4ca-dd42-88e2-57f43f00e544 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic intel_idle.max_cstate=7  
Build Date: 02 November 2016  10:06:10PM
xorg-server 2:1.18.4-0ubuntu0.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jul 11 15:00:47 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
HP Chromebook 13 G1 beta.
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome-desktop
host: version 9592.42.0 (Official Build) beta-channel chell 
kernel: Linux localhost 3.18.0-14861-g70c266fc4519 #1 SMP PREEMPT Thu Jun 29 22:04:02 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

**Comment by swors** [comment] 2017-07-12 14:38
@formatCvt 
Have you fixed it? I've no idea about your issue, and the key error message is not same as mine.
Yours is **(EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)**
Mine is **(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)**

**Comment by formatCvt** [comment] 2017-07-13 13:07
@swors nope
i will file new issue

**Comment by dnschneid** [comment] 2017-07-14 06:15
Seems like this is a duplicate of #2875?  Maybe the fix [I suggested](https://github.com/dnschneid/crouton/issues/2875#issuecomment-261073012) is the way to go.

**Comment by darcyparker** [comment] 2017-10-11 10:41
@dnschneid - I can confirm that `sudo startcli`, then `sudo apt-get remove xserver-xorg-legacy` works. After doing this I can `startxfce4 -b` with a fresh install of stretch.  (Which I installed with `sudo sh -e ~/Downloads/crouton -r stretch -t xfce,cli-extra,keyboard,chrome,extension,xiwi`

**Comment by gardwired** [comment] 2017-10-21 03:24
+1 on removing xserver-xorg-legacy.  worked with stretch/lxde.   chronos 63/crouton latest as of today.   prior to finding this fix i tried jessie with at least three different targets xfce, lxde etc.  same behavior.

so glad to know there's a fix.

**Comment by githubgnulinux** [comment] 2017-11-12 22:37
Thanks for the command to enter chroot.

Tried to remove xserver xorg legacy but not installed.

Only xserver-xorg newest versio 17718. How to downgrade?

x server unable to start due to xinit:
https://github.com/dnschneid/crouton/issues/3510

**Comment by DennisLfromGA** [comment] 2017-11-12 23:34
@githubgnulinux,

I ran into the same situation, it reported `xserver-xorg-legacy` was not installed.
When I looked at the error when I ran the `prepare.sh` script I got more details that told me, in my case, that the conflicting package was `xserver-xorg-legacy-hwe-16.04` so I removed it with -

`sudo apt purge  xserver-xorg-legacy-hwe-16.04`
`sudo /prepare.sh`

The `prepare.sh` script ran and completed this time.

*Hope this helps,*
-**DennisL**

**Comment by DennisLfromGA** [comment] 2018-07-16 22:43
Closing. Please update your chroot and try again, re-open if this issue is still a concern.

**Closed** 2018-07-16 23:01 UTC

**Comment by akamai100** [comment] 2020-09-06 10:05
The solution that it works for me was:
sudo chmod -R 777 /tmp

**Comment by akamai100** [comment] 2020-09-06 10:05
The solution that it works for me was:
sudo chmod -R 777 /tmp

**Comment by akamai100** [comment] 2020-09-06 10:05
The solution that it works for me was:
sudo chmod -R 777 /tmp

**Comment by akamai100** [comment] 2020-09-06 10:05
The solution that it works for me was:
sudo chmod -R 777 /tmp

**Comment by akamai100** [comment] 2020-09-06 10:05
The solution that it works for me was:
sudo chmod -R 777 /tmp

**Comment by akamai100** [comment] 2020-09-06 10:05
The solution that it works for me was:
sudo chmod -R 777 /tmp

**Comment by akamai100** [comment] 2020-09-06 10:05
The solution that it works for me was:
sudo chmod -R 777 /tmp

**Comment by akamai100** [comment] 2020-09-06 10:05
The solution that it works for me was:
sudo chmod -R 777 /tmp

**Comment by akamai100** [comment] 2020-09-06 10:05
The solution that it works for me was:
sudo chmod -R 777 /tmp

**Comment by akamai100** [comment] 2020-09-06 10:05
The solution that it works for me was:
sudo chmod -R 777 /tmp

**Comment by akamai100** [comment] 2020-09-06 10:05
The solution that it works for me was:
sudo chmod -R 777 /tmp

**Comment by akamai100** [comment] 2020-09-06 10:05
The solution that it works for me was:
sudo chmod -R 777 /tmp

**Comment by akamai100** [comment] 2020-09-06 10:05
The solution that it works for me was:
sudo chmod -R 777 /tmp
