### ISSUE TITLE
Failed to complete chroot setup.

### ISSUE THREAD

**Issue by imarisimpson** [dnschneid/crouton#4442] opened 2021-03-19 19:15 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all
I: Installing core packages...
W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/libc6_2.23-0ubuntu3_amd64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/libc6_2.23-0ubuntu3_amd64.deb is at fault)
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:When I run the sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton command it says Failed to complete chroot setup.Someone please help.




#### If known, describe the steps to reproduce the issue:

**Comment by MrHallway0** [comment] 2021-03-19 19:25
Please run `sudo edit-chroot -all` and paste the output.

**Comment by imarisimpson** [comment] 2021-03-19 19:34
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
Creating hwaudio group with GID 18...
su: pam_start: error 26
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by MrHallway0** [comment] 2021-03-19 21:41
Duplicate of #4441.

**Closed** 2021-03-19 21:45 UTC
