### ISSUE TITLE
Error about "http://archive.ubuntu.com/ubuntu/dists/precise/InRelease"

### ISSUE THREAD

**Issue by miesn** [dnschneid/crouton#2915] opened 2016-11-29 09:26 UTC
```
Please paste the output of the following command here: sudo sh -e ~/Downloads/crouton -n jessie -t xfce
```

#### Please describe your issue:
when the installation begin, a error shows "Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/InRelease"

and then some packages were downloaded and installed.
but then it occur the error "Failed to fetch http://archive.ubuntu.com/ubuntu/dists/precise-security/main/binary-amd64/Packages"

and i found the url "http://archive.ubuntu.com/ubuntu/dists/precise/InRelease" can't be reached. it shows a 404 error.

**Comment by DennisLfromGA** [comment] 2016-11-29 20:49
That's usually a transient network error, try again or try again later.

I would suggest that you install a newer release than 'precise' though, perhaps 'trusty' or 'xenial', they work better.

*Hope this helps,*
-**DennisL**

**Comment by bradley2W1DL** [comment] 2016-12-03 21:14
I've been getting the same error when trying to download trusty as well.
```
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease
...
W: http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease was corrupt
```

**Comment by dvwz** [comment] 2016-12-05 02:38
I also got this error while trying to download trusty.

**Comment by leoparder** [comment] 2016-12-21 11:12
I have the same issue. I tried two days ago and today, same :

> Download from Debian gitweb failed. Trying latest release...
> 2016-12-21 12:10:07 URL:http://debian.proxad.net/debian/pool/main/d/debootstrap/ [6667/6667] -> "-" [1]
> Downloading debootstrap version 1.0.87...
> 2016-12-21 12:10:11 URL:http://debian.bononia.it/debian/pool/main/d/debootstrap/debootstrap_1.0.87.tar.gz [65875/65875] -> "-" [1]
> Patching debootstrap...
> Downloading bootstrap files...
> W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
> I: Retrieving InRelease 
> W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease

Checking this link, I see the file seems named "Release" and not "InRelease".
See : http://archive.ubuntu.com/ubuntu/dists/trusty/

What should I do ? I tried a mirror like advised on some websites, no luck.

**Comment by jbeale1** [comment] 2017-01-28 19:41
I have the same ".../trusty/InRelease" file-not-found problem. Looks like someone changed the name and an install script therefore failed?

**Comment by dnschneid** [comment] 2017-03-16 01:30
Dupe of #2966

**Closed by dnschneid** 2017-03-16 01:30 UTC
