### ISSUE TITLE
Chroot Setup Issue For Kali-Rolling 

### ISSUE THREAD

**Issue by dethslayer999** [dnschneid/crouton#4153] opened 2019-10-11 15:45 UTC
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20190902190258~master:9a594a66
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12371.75.0 (Official Build) stable-channel snappy 
kernel: Linux localhost 4.4.186-16721-gcdc0ab99cc00 #1 SMP PREEMPT Wed Sep 25 23:41:02 PDT 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12371.75.0 (Official Build) stable-channel snappy 
kernel: Linux localhost 4.4.186-16721-gcdc0ab99cc00 #1 SMP PREEMPT Wed Sep 25 23:41:02 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### So when i tried reinstalling Kali Rolling It Give's Me This Error

Package xbindkeys is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'xbindkeys' has no installation candidate
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in kali-rolling
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

#### Well all i really Did Was 
sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce
and i have tried removing the -e still same stuff

**Comment by spaceinvators** [comment] 2019-10-12 18:20
Same issue after a wipe... Very frustrating

**Comment by tdugger** [comment] 2019-10-13 15:43
Hitting same issue.  I could swear that it was working fine on Oct 7 and then started failing on Oct 8.  I was doing the install many times with different -t options and then suddenly what worked no longer worked on Oct. 8.

**Comment by tdugger** [comment] 2019-10-13 16:23
installing xenial/unity works fine.
$ sudo sh ~/Downloads/crouton -r xenial -t unity
I think something changed in kali-rolling that caused this recently.

**Comment by Tuxerito** [comment] 2019-10-16 23:01
Same error installing Debian Bullseye + XFCE

**Comment by spaceinvators** [comment] 2019-10-18 20:01
Any update?

**Comment by ernest-park** [comment] 2019-10-19 23:56
Any way to install build from month ago until this gets resolved?


E: Package 'xbindkeys' has no installation candidate
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/KALI...

**Comment by mstair** [comment] 2019-10-20 21:53
Until this gets addressed (xbindkeys pkg seems like got removed from a repo), a workaround to get kali installed (kali-last-snapshot, which has a timestamp of 20190823 at http://archive.linux.duke.edu/kalilinux/kali/dists/ as of writing).

It may be easier to just fork/clone and make changes below, I just made changes inline...

Find one of the recent crouton cache dirs under `/tmp/crouton-installer-cache` (`/tmp/crouton-installer-cache/crouton.F8M` for examples below).

Sudo and edit `/tmp/crouton-installer-cache/crouton.F8M/installer/kali/releases` and append `kali-last-snapshot`.

Then run following from `/tmp/crouton-installer-cache` dir:
`sudo crouton.F8M/installer/main.sh -r kali-last-snapshot -t xfce`

I have never installed kali-rolling via crouton before, so not sure if it includes all the tools. I had to run `apt-get install kali-linux-all` from inside kali-last-snapshot.

**Comment by Rimulator** [comment] 2019-10-21 03:20
Working through this now. Good to see that it is not just me.

**Comment by mstair** [comment] 2019-10-21 12:55
It looks like kali.org, you can export `CROUTON_MIRROR_kali` env var in the sudo, if you know of a better mirror:

https://github.com/dnschneid/crouton/blob/master/installer/kali/defaults#L23

**Comment by spaceinvators** [comment] 2019-10-23 18:47
Do we have a solution :)?

**Comment by BlackAssassin** [comment] 2019-10-27 12:28
> Until this gets addressed (xbindkeys pkg seems like got removed from a repo), a workaround to get kali installed (kali-last-snapshot, which has a timestamp of 20190823 at http://archive.linux.duke.edu/kalilinux/kali/dists/ as of writing).
> 
> It may be easier to just fork/clone and make changes below, I just made changes inline...
> 
> Find one of the recent crouton cache dirs under `/tmp/crouton-installer-cache` (`/tmp/crouton-installer-cache/crouton.F8M` for examples below).
> 
> Sudo and edit `/tmp/crouton-installer-cache/crouton.F8M/installer/kali/releases` and append `kali-last-snapshot`.
> 
> Then run following from `/tmp/crouton-installer-cache` dir:
> `sudo crouton.F8M/installer/main.sh -r kali-last-snapshot -t xfce`
> 
> I have never installed kali-rolling via crouton before, so not sure if it includes all the tools. I had to run `apt-get install kali-linux-all` from inside kali-last-snapshot.

Thanks for your method.I've tried it.But It's not work in the last-snap version too.How can fix it?

**Comment by stestereichert** [comment] 2019-11-06 16:22
Still no solution to this? Having the same issue

**Comment by meanderpaul** [comment] 2019-11-08 02:25
I’m also experiencing this issue. Is there a way we can find the part calling for the xbindkeys and remove it or have the installer ignore it?

**Comment by kadenbcampbell** [comment] 2019-11-10 05:03
I'm also having this issue. Has anyone found a solution?

**Comment by cLussE** [comment] 2019-11-10 20:15
I'm having this same issue, any solutions yet?

**Comment by e636** [comment] 2019-11-11 21:10
I’m also having same issue. Any solutions?

**Comment by RomHtK** [comment] 2019-11-13 14:11
I didn't understand, I thought it was coming from me because I had installed the Mrchromebox firmware and changed the size of the SSD partitions to test the dual-boot
So for the moment it's due to a missing package.

**Comment by skilfoy** [comment] 2019-11-15 04:53
I'm having the same issue! Any help would be greatly appreciated.

**Comment by Rimulator** [comment] 2019-11-15 08:23
Seems like we need to collectively mirror this image. Can we collectively
determine a build process? I can host everything.

**Comment by skilfoy** [comment] 2019-11-17 03:06
Getting a bit desperate here. The USB stick I put Kali on works for my Mac but not on my Chromebook... It'd be so much easier if the crouton method worked properly!

**Comment by RomHtK** [comment] 2019-11-17 18:32
I just found this [https://github.com/dnschneid/crouton/issues/4130#issuecomment-528161403](url) in another post that was written before this one, there were apparently some concerns with Debian as well.
I'll try this, don't hesitate to come and comment if you try on your side

**Comment by twonklesDev** [comment] 2019-11-20 06:04
Solution:
Download package based on your architecture using one of the mirrors from the link: https://packages.debian.org/jessie/xbindkeys

sudo enter-chroot -u root -n kali-rolling

sudo apt-get install curl

curl -O "insert bindkeys download here.deb"

install with dpkg

dpkg -i "bindkeys.deb"

continue the install with:

sudo enter-chroot -u root -n kali-rolling

The install should continue now with no issues.

**Comment by Rimulator** [comment] 2019-11-20 10:35
Note: 
-u probably not necessary 

Chromebook packages are AMD64 based.

So . . .

1. [ctrl]+[alt]+t <ENTER>

2. _shell_<ENTER>

[This is to install to an external drive](https://github.com/dnschneid/crouton/wiki/How-To-Install-To-External-Drive). This gives you the option of as much space as you need and the security that your kali build is on a tiny SD card.

a) _sudo su_ <ENTER>
b) _fdisk -l_ <ENTER>
c) _umount /dev/sdb1_ <ENTER> (or unmount your removable media)
d) mkfs -t ext4 /dev/sdb1 <ENTER> (or whatever your removable media is)
e) mount /dev/sdb1



- -e = Encryption

- -r = Release

- -t = Target

- -n = Name of chroot
3. _sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce,xiwi -n Kali_ <ENTER>

or (if installing to external drive)
_sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce, xiwi -n Kali -p '/media/removable/SD Card'_ <ENTER>

4. _sudo enter-chroot -n Kali_ <ENTER>

5. "d" <ENTER>

6. _sudo apt-get install curl_ <ENTER>

7. "y" <ENTER>

8. curl -O "http://http.us.debian.org/debian/pool/main/x/xbindkeys/xbindkeys_1.8.6-1_amd64.deb" <ENTER>

9. _dpkg -i "xbindkeys_1.8.6-1_amd64.deb"_ <ENTER>

Note: error messages from missing dependencies. Skip 10, 11 and 12 if you don't see these messages.

10. _sudo apt-get install xbindkeys_ <ENTER>

11. _apt --fix-broken install_ <ENTER>

12. "Y" <ENTER>

13. (install is not complete here, but close) Close and restart shell, items 1, then 2 above.

14. (**Important**) _sudo sh -e ~/Downloads/crouton -u -n Kali -t xiwi_ <ENTER>

15.  _sudo enter-chroot -n Kali_ <ENTER>

16. _sudo su apt-get update_ <ENTER>

17. _sudo su apt-get upgrade_ <ENTER>

18. (If you have space, like Google Pixel Go, Pixelbook, older HP Chromebook G1) _sudo apt-get install kali-linux-full_ <ENTER>
          
          ~ else ~

- _sudo apt-get install nmap_ <ENTER>

- _sudo apt-get install metasploit-framework_ <ENTER>

- _sudo apt-get install nikto_ <ENTER>

19. "Y" <ENTER>

20. Enjoy.

Credit to [twonklesDev](https://github.com/twonklesDev) for this working install. Strange that the kali linux crouton as installed is an old, almost unsupported version.

https://github.com/dnschneid/crouton/wiki/Kali

**Comment by spaceinvators** [comment] 2019-11-21 18:18
> Solution:
> Download package based on your architecture using one of the mirrors from the link: https://packages.debian.org/jessie/xbindkeys
> 
> sudo enter-chroot -u root -n kali-rolling
> 
> sudo apt-get install curl
> 
> curl -O "insert bindkeys download here.deb"
> 
> install with dpkg
> 
> dpkg -i "bindkeys.deb"
> 
> continue the install with:
> 
> sudo enter-chroot -u root -n kali-rolling
> 
> The install should continue now with no issues.
> 
> Original post : #4130
> 
> Tried and confirmed working.

Sure? I will try it tonight, are those the right steps?

**Comment by spaceinvators** [comment] 2019-11-21 19:14
> Chromebook packages are AMD64 based.
> 
> So . . .
> 
> 1. [ctrl]+[alt]+t
> 2. _shell_
> 
> **SSD**. [This is to install to an external drive](https://github.com/dnschneid/crouton/wiki/How-To-Install-To-External-Drive). This gives you the option of as much space as you need and the security that your kali build is on a tiny SD card.
> 
> a) _sudo su_ 
> b) _fdisk -l_ 
> c) _umount /dev/sdb1_ (or unmount your removable media)
> d) mkfs -t ext4 /dev/sdb1 (or whatever your removable media is)
> e) mount /dev/sdb1
> 
> * -e = Encryption
> * -r = Release
> * -t = Target
> * -n = Name of chroot
>   Note: Don't install xiwi at this point. It might hang the install with a [weird error](https://github.com/dnschneid/crouton/issues/2971).
> 
> 1. _sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce -n Kali_ 
>    ```
>       ~ else ~
>    ```
> 
> (if installing to external drive)
> **SSD**. _sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce -n Kali -p '/media/removable/SD Card'_
> 
> 1. _sudo enter-chroot -n Kali_ 
>    ```
>       ~ else ~
>    ```
> 
> **SSD**. _sudo enter-chroot -c /media/removable/'SD Card'/chroots -n Kali_ -u root
> 
> 1. "d"
> 2. _sudo apt-get install curl_
> 3. "y"
> 4. curl -O "http://http.us.debian.org/debian/pool/main/x/xbindkeys/xbindkeys_1.8.6-1_amd64.deb"
> 5. _dpkg -i "xbindkeys_1.8.6-1_amd64.deb"_
> 
> Note: error messages from missing dependencies. Skip 10, 11 and 12 if you don't see these messages.
> 
> 1. _sudo apt-get install xbindkeys_
> 2. _apt --fix-broken install_
> 3. "Y"
> 4. (install is not complete here, but close) _exit_ 
>    ```
>      ~ else ~
>    ```
> 
> Close and restart shell, items 1, then 2 above.
> 
> 1. (**Important**) _sudo sh -e ~/Downloads/crouton -u -n Kali -t xiwi_ 
>    ```
>      ~ else ~
>    ```
> 
> **SSD**. _sudo sh -e ~/Downloads/crouton -u -n Kali -t xiwi -p '/media/removable/SD Card'_
> 
> 1. _sudo enter-chroot -n Kali_ 
>    ```
>     ~ else ~
>    ```
> 
> **SSD**. _sudo enter-chroot -n Kali -c /media/removable/'SD Card'/chroots_
> 
> 1. _sudo su apt-get update_
> 2. _sudo su apt-get upgrade_
> 3. (If you have space, like Google Pixel Go, Pixelbook, older HP Chromebook G1) _sudo apt-get install kali-linux-full_  (about 30 minutes and 7gb)
>    ```
>      ~ else ~
>    ```
> 
> * _sudo apt-get install nmap_
> * _sudo apt-get install metasploit-framework_
> * _sudo apt-get install nikto_
> 
> 1. "Y"
> 2. sudo startxfce4 -n Kali_ 
>    ```
>      ~ else ~
>    ```
> 
> **SSD**. sudo startxfce4 -n nameofchroot -c /media/removable/'SD Card'/chroots_
> 
> 1. Enjoy.
> 
> Credit to [twonklesDev](https://github.com/twonklesDev) for this working install. Strange that the kali linux crouton as installed is an old, almost unsupported version.
> 
> https://github.com/dnschneid/crouton/wiki/Kali

Still not working, after step 5: UID 1000 not found
Any help?

**Comment by Anonymoustank** [comment] 2019-12-02 01:38
How I got Kali-Rolling amd64 with Xfce working:

1. sudo crouton -r kali-rolling -t audio,core

2. sudo enter-chroot -n kali-rolling

    a. sudo apt install curl

    b. sudo curl -O "http://http.us.debian.org/debian/pool/main/x/xbindkeys/xbindkeys_1.8.6-1_amd64.deb"

    c. sudo apt install ./xbindkeys*

    d. exit

3. sudo crouton -r kali-rolling -t xfce -u

**Comment by WilhelmZhu** [comment] 2019-12-02 18:41
> How I got Kali-Rolling amd64 with Xfce working:
> 
> 1. sudo crouton -r kali-rolling -t audio,core
> 2. sudo enter-chroot -n kali-rolling
>    a. sudo apt install curl
>    b. sudo curl -O "http://http.us.debian.org/debian/pool/main/x/xbindkeys/xbindkeys_1.8.6-1_amd64.deb"
>    c. sudo apt install ./xbindkeys*
>    d. exit
> 3. sudo crouton -r kali-rolling -t xfce -u

That's working perfectly!

**Comment by thatonetechdude** [comment] 2019-12-06 02:25
@Anonymoustank thank you so much, I have been waiting for over half a monthe too get the darn thing installed and you gave it the last push it needed thank you so much!

**Comment by Anonymoustank** [comment] 2019-12-06 02:32
No problem :)

**Comment by thatonetechdude** [comment] 2019-12-06 02:55
@Anonymoustank I must simply ask, are you tech jesus? You solved my problum with 1 short post thank you so much.

**Comment by cserg8621** [comment] 2019-12-06 19:08
Life saver

**Comment by tdugger** [comment] 2019-12-07 18:34
After doing the install steps provided above (thanks @Anonymoustank) what's the best way to install all the kali linux tools?  I'm trying to mimick what is in the offensive security's virtualbox image.  https://www.offensive-security.com/kali-linux-vm-vmware-virtualbox-image-download/
Is the katoolin something you guys use?  https://www.tecmint.com/install-kali-linux-tools-using-katoolin-on-ubuntu-debian/
Thanks.

**Comment by cserg8621** [comment] 2019-12-07 18:38
The Katoolin is actually a headache to use IMO

**Comment by tdugger** [comment] 2019-12-07 22:14
> The Katoolin is actually a headache to use IMO
How would you suggest to install all the kali tools then?  After following anonymoustank's steps, the tools don't show up in the Applications menu like it does in the virtualbox image from OS.

**Comment by Rimulator** [comment] 2019-12-07 22:36
This is an installation option 

sudo su apt-get update
sudo su apt-get upgrade
(If you have space, like Google Pixel Go, Pixelbook, older HP Chromebook G1) sudo apt-get install kali-linux-full (about 30 minutes and 7gb)
  ~ else ~
sudo apt-get install nmap
sudo apt-get install metasploit-framework
sudo apt-get install nikto

**Comment by Rimulator** [comment] 2019-12-07 22:43
sudo su
git clone https://github.com/LionSec/katoolin.git && cp katoolin/katoolin.py /usr/bin/katoolin
chmod +x /usr/bin/katoolin
sudo katoolin

**Comment by tdugger** [comment] 2019-12-08 04:40
Thanks @Rimulator 

Anyone know the window manager that is used by the offensive security's virtualbox kali linux image?

It's nice cause all the tools are on the menu and categorized.  I'm assuming after installing kali-linux-full that the tools won't be in a menu like this.

![Screenshot 2019-12-07 at 10 38 37 PM](https://user-images.githubusercontent.com/637190/70384302-6a4a1f80-1942-11ea-8a9c-2e6807790526.png)

**Comment by Rimulator** [comment] 2019-12-08 05:25
You are right. We will want . . 

1. Encrypted Kali on Chromebook
2. All tools
3. Easy navigation, like the VMWARE image
4. Disposable - installation to external SD card, external encryption key, no PII on image, key or decryption tied to MAC or hardware specific data and user specific data


So, we have #1 and possibly #2. #3 just needs documentation and testing. #4 needs to be investigated.

Bonus - how do we clean up the desktop folders to a dozen drives that don't exist?

Should we fork this as a separate project?

**Comment by tdugger** [comment] 2019-12-08 15:00
That's exactly what I'm looking for.  And definitely #4.  I did some searching on #4 and didn't find how to put a chroot on an SD card.  For #3, we probably want to get in touch with someone at offensive security.  Maybe they have a script that creates these menus or someone just did it once and done.

**Comment by tdugger** [comment] 2019-12-08 15:06
Also, I tried to do the `sudo apt-get install kali-linux-full` command and it churned for awhile and then failed at installing maltego.

**Comment by HPchrome** [comment] 2019-12-13 12:02
Still i have the same problem, after `sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce -n Kali` have 

> E: Package 'xbindkeys' has no installation candidate   

i m not installing on external drive.
Which  code should i enter ?

**Comment by DennisLfromGA** [comment] 2019-12-14 22:39
@HPchrome,

Did you run steps 2 & up in this comment?
- https://github.com/dnschneid/crouton/issues/4153#issuecomment-560190450

*Hope this helps,*
-**DennisLfromGA**

**Comment by HPchrome** [comment] 2019-12-15 15:23
Ok... maybe i write so short about the steps that reproduce this problem.

1. I Open my browser and press  ctrl+alt+t
2. `shell`
3. ` sudo su `
4. `sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce -n Kali`
     after some time 

> E: Package 'xbindkeys' has no installation candidate

and here i stop with the installation.
On this command `sudo edit-chroot -all`  it gave 

> name: Kali
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/Kali...
WARNING: Unable to register core dump handler.
crouton: version 1-20190902190258~master:9a594a66
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12739.4.0 (Official Build) dev-channel setzer 
kernel: Linux localhost 3.18.0-19937-g5da699e3897c #1 SMP PREEMPT Tue Dec 10 00:01:28 PST 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/Kali...

how can i continue with installation and to have a Kali...?
or maybe steps that i`m doing are not correct and please explain more.
Which command should i use to continue?

**Comment by DennisLfromGA** [comment] 2019-12-15 16:22
@HPchrome,

I'll ask again -
- Did you run steps 2 & up in this comment?
- - #4153 (comment)

Hope this helps,
-DennisLfromGA

**Comment by HPchrome** [comment] 2019-12-15 17:25
@DennisLfromGA
Sorry, 
in browser shell gave 

> chronos@localhost / $ sudo crouton -r kali-rolling -t audio,core
sudo: crouton: command not found

and 

> chronos@localhost / $ sudo enter-chroot -n kali-rolling
/mnt/stateful_partition/crouton/chroots/kali-rolling not found.

**Comment by Rimulator** [comment] 2019-12-15 21:16
Try this - https://github.com/dnschneid/crouton/issues/4153#issuecomment-555943965

My answer is longer than some of the other solutions, but it is the same. Do not skip any steps.


When complete, do this - https://github.com/dnschneid/crouton/issues/4153#issuecomment-562892794

**Comment by thatonetechdude** [comment] 2019-12-16 00:14
@HPchrome you must install "http://http.us.debian.org/debian/pool/main/x/xbindkeys/xbindkeys_1.8.6-1_amd64.deb"
from @Anonymoustank previous comment, then run the command again.

**Comment by HPchrome** [comment] 2019-12-16 08:52
@Rimulator 

> chronos@localhost / $ sudo su
> localhost / # fdisk -l
> Disk /dev/loop0: 3.1 GiB, 3312095232 bytes, 6468936 sectors
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> 
> 
> Disk /dev/loop1: 407.5 MiB, 427315200 bytes, 834600 sectors
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> 
> 
> Disk /dev/loop2: 4 KiB, 4096 bytes, 8 sectors
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> 
> 
> Disk /dev/loop3: 4 KiB, 4096 bytes, 8 sectors
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> 
> 
> Disk /dev/loop4: 49.6 MiB, 51994624 bytes, 101552 sectors
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> 
> 
> Disk /dev/loop5: 415.6 MiB, 435802112 bytes, 851176 sectors
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> 
> 
> Disk /dev/mmcblk0: 14.7 GiB, 15758000128 bytes, 30777344 sectors
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> Disklabel type: gpt
> Disk identifier: 83B0C87C-47E7-134B-AFEE-6C72D3348DC9
> 
> Device            Start      End  Sectors  Size Type
> /dev/mmcblk0p1  8704000 30744575 22040576 10.5G Microsoft basic data
> /dev/mmcblk0p2    20480    53247    32768   16M ChromeOS kernel
> /dev/mmcblk0p3  4509696  8703999  4194304    2G ChromeOS root fs
> /dev/mmcblk0p4    53248    86015    32768   16M ChromeOS kernel
> /dev/mmcblk0p5   315392  4509695  4194304    2G ChromeOS root fs
> /dev/mmcblk0p6    16448    16448        1  512B ChromeOS kernel
> /dev/mmcblk0p7    16449    16449        1  512B ChromeOS root fs
> /dev/mmcblk0p8    86016   118783    32768   16M Microsoft basic data
> /dev/mmcblk0p9    16450    16450        1  512B ChromeOS reserved
> /dev/mmcblk0p10   16451    16451        1  512B ChromeOS reserved
> /dev/mmcblk0p11      64    16447    16384    8M unknown
> /dev/mmcblk0p12  249856   315391    65536   32M EFI System
> 
> Partition table entries are not in disk order.
> 
> 
> 
> 
> Disk /dev/mmcblk0boot1: 4 MiB, 4194304 bytes, 8192 sectors
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> 
> 
> Disk /dev/mmcblk0boot0: 4 MiB, 4194304 bytes, 8192 sectors
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> 
> 
> Disk /dev/dm-0: 2 GiB, 2087714816 bytes, 509696 sectors
> Units: sectors of 1 * 4096 = 4096 bytes
> Sector size (logical/physical): 4096 bytes / 4096 bytes
> I/O size (minimum/optimal): 4096 bytes / 4096 bytes
> 
> 
> Disk /dev/mapper/encstateful: 3.1 GiB, 3312095232 bytes, 6468936 sectors
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> 
> 
> 
> 
> Disk /dev/mapper/F8BFEC3E073D0AD3DB85885D427CD20B4E14527BB6E5C1653A5EC4BA6B41DEDF: 412.4 MiB, 432390144 bytes, 105564 sectors
> Units: sectors of 1 * 4096 = 4096 bytes
> Sector size (logical/physical): 4096 bytes / 4096 bytes
> I/O size (minimum/optimal): 4096 bytes / 4096 bytes
> localhost / # umount /dev/sdb1 
> umount: /dev/sdb1: no mount point specified.

what to umount ?

@thatonetechdude

> chronos@localhost / $ sudo apt install curl
> sudo: apt: command not found
> chronos@localhost / $ sudo curl -O "http://http.us.debian.org/debian/pool/main/x/xbindkeys/xbindkeys_1.8.6-1_amd64.deb"
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file xbindkeys_1.8.6-1_amd64.deb: Read-only file 
> Warning: system
>   3 37136    3  1230    0     0   1194      0  0:00:31  0:00:01  0:00:30  1940
> curl: (23) Failed writing body (0 != 1230)
> chronos@localhost / $ sudo apt install ./xbindkeys*
> sudo: apt: command not found

**Comment by Rimulator** [comment] 2019-12-16 12:03
What kind of machine is this? What OSes are installed?

**Comment by HPchrome** [comment] 2019-12-16 12:21
hp chromebook model 11-v001nd about OS i only know that run chrome OS i made power wash recently before that i only  installed ubuntu as same way as i want to install Kali now.

**Comment by NasifQadri** [comment] 2019-12-24 05:08
> How I got Kali-Rolling amd64 with Xfce working:
> 
> 1. sudo crouton -r kali-rolling -t audio,core
> 2. sudo enter-chroot -n kali-rolling
>    a. sudo apt install curl
>    b. sudo curl -O "http://http.us.debian.org/debian/pool/main/x/xbindkeys/xbindkeys_1.8.6-1_amd64.deb"
>    c. sudo apt install ./xbindkeys*
>    d. exit
> 3. sudo crouton -r kali-rolling -t xfce -u

Thanks, this works for me

**Comment by DennisLfromGA** [comment] 2019-12-25 16:04
Closing. Please re-open if this issue is still a concern.

**Closed by DennisLfromGA** 2019-12-25 16:04 UTC

**Comment by jeffvader90** [comment] 2020-01-11 13:07
@NasifQadri How did you get the xbindkeys deb package to install?  I tried using apt, dpkg and I also forced it with dpkg but I kept getting an error.  I have tried everything suggested in this thread and no luck.

**Comment by Rimulator** [comment] 2020-01-11 21:39
There are a dozen working examples herein, each describing how the package and dependencies were installed. Specifically which set of instructions did you carefully follow?

**Comment by GunnerBasil** [comment] 2020-01-11 23:31
@Anonymoustank when I run the sudo enter-chroot, my terminal prompt changes from:

chronos@localhost / $
to
(kali-rolling)gunnerbasil@localhost:~$

I thought that this would open kali-rolling like it opened xfce, as a desktop, but instead it is just a prompt. is this supposed to happen? How would I be able to make it a desktop?

**Comment by GunnerBasil** [comment] 2020-01-11 23:39
I made a reddit post about it: https://www.reddit.com/r/Crouton/comments/enfcwf/clarification_and_questions_regarding_kali_linux/

**Comment by GunnerBasil** [comment] 2020-01-11 23:44
never mind, I was just stoopid.
