### ISSUE TITLE
lenov c630 Failed to complete chroot setup  QaQ

### ISSUE THREAD

**Issue by xxmNIe** [dnschneid/crouton#4475] opened 2021-05-06 15:11 UTC
version 92.0.4489.0
run   sudo crouton  -t xfce 

the result is :
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
I: Installing core packages...
W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/libc6_2.23-0ubuntu3_amd64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/libc6_2.23-0ubuntu3_amd64.deb is at fault)
Failed to complete chroot setup.
sh: 0: getcwd() failed: No such file or directory
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment] 2021-05-06 17:00
Duplicate of: Help please. #4441   
For details & tracking please see:
- #4441 (comment)

Hope this helps,
-DennisLfromGA

**Closed by DennisLfromGA** 2021-05-06 17:00 UTC
