### ISSUE TITLE
sudo apt-get install not working

### ISSUE THREAD

**Issue by andrewfhou** [dnschneid/crouton#2778] opened 2016-09-17 19:38 UTC
```
name: trusty
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160902144033~master:9f8e9a22
release: trusty
architecture: amd64
xmethod: xorg
targets: audio,extension,chrome,keyboard,xfce
host: version 8530.81.0 (Official Build) beta-channel reks 
kernel: Linux localhost 3.18.0-12632-g42a6df4 #1 SMP PREEMPT Wed Sep 7 16:55:22 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

#### Please describe your issue:
I'm getting all sorts of issues when trying to install the steam .deb file. The details of what happened are here: https://www.reddit.com/r/Crouton/comments/52qv4z/sudoapt_get_install_not_working/
I deleted and made a new chroot a few times, and keep on getting the same issues. The most recent two times (out of 4), I was able to use sudo apt-get install to initially install software center, but the next time I tried to use the command, it gave me the 
`E: Method http has died unexpectedly!
E: Sub-process http has received a segmentation fault`
error

**Comment by BharatAdhana** [comment] 2016-09-20 10:04
After a fresh install of ubuntu run :

sudo apt-get update && sudo apt-get upgrade on Terminal (Ctrl+Alt+T)

Once, this process has been completed, you can install packages using sudo apt-get install <package_name>


or



sudo rm /var/lib/apt/lists/* -vf
sudo apt-get clean
sudo apt-get update
sudo apt-get upgrade
That should clear your existing lists and rebuild.

By the evening i'll post a video also.

**Comment by jamesgraves** [comment] 2016-09-21 18:02
I have also seen the issue where running `apt-get update` fails with an http segfault.

```
$ sudo apt-get update
E: Method http has died unexpectedly!
E: Sub-process http received a segmentation fault.
```

This is on an Acer Chromebook R11:

```
crouton: version 1-20160902144033~master:9f8e9a22
release: trusty
architecture: amd64
xmethod: xiwi
targets: audio,xfce-desktop,xiwi,cli-extra,touch
host: version 8530.90.0 (Official Build) beta-channel cyan 
kernel: Linux localhost 3.18.0-12635-g9cfba74 #1 SMP PREEMPT Tue Sep 20 00:27:59 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

From inside the chroot I can ping other hosts and use the web browser to access `http://archive.ubuntu.com/ubuntu`, so it doesn't seem like an network connectivity issue.

Stopping and restarting the chroot seems to fix the issue, at least temporarily.

**Comment by drinkcat** [comment] 2016-10-11 17:50
Duplicate of #2688.

**Closed by drinkcat** 2016-10-11 17:50 UTC
