### ISSUE TITLE
How to get different wp-query results with a same pagination

### ISSUE THREAD

**Issue by truetesterphp** [dnschneid/crouton#1507] opened 2015-03-17 07:11 UTC
i have 4 different post types 1.page 2.post 3.news and 4.videos. i need to get all the post types in separate section in search result page with a same pagination. This time my search result page first shows page then post then news and in last news. I want to show all as like the format below. 
page
 titles of pages 
post 
titles of posts 
news 
title of news post types posts 
videos 
title of videos post type posts

and at the end need a common pagination for all query

**Comment by smibarber** [comment] 2015-03-17 15:33
Dupe of #262

**Closed by smibarber** 2015-03-17 15:33 UTC
