### ISSUE TITLE
Error org.freedesktop.DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by myxxmikeyxx** [dnschneid/crouton#4482] opened 2021-05-14 17:28 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /media/removable/ubuntu/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 12105.100.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Sun Jul 14 00:09:57 PDT 2019 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /media/removable/ubuntu/chroots/xenial...

#### Please describe your issue:
When I run `sudo startxfce4` it runs into an error.

`chronos@localhost /usr/local $ sudo startxfce4
Entering /media/removable/ubuntu/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.0-140-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Sun Jul 14 00:09:57 PDT 2019 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure root=PARTUUID=0b9857d8-7b0a-e348-a928-0b5664dc79ac/PARTNROFF=1 rootwait rw dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=0 dm="1 vroot none ro 1,0 2539520 verity payload=ROOT_DEV hashtree=HASH_DEV hashstart=2539520 alg=sha1 root_hexdigest=3bfc672b009a3247d3cd8399a74f96ac53188553 salt=306427720380043295ff7f5e5f7ef68a81138057901e316471bd1520719b78b2" noinitrd vt.global_cursor_default=0 kern_guid=0b9857d8-7b0a-e348-a928-0b5664dc79ac  
Build Date: 08 April 2021  02:42:23PM
xorg-server 2:1.19.6-1ubuntu4.1~16.04.6 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri May 14 13:24:15 2021
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1621013055.898288 sender=:1.10 -> destination=:1.54 serial=781 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1621013057.867224 sender=:1.10 -> destination=:1.56 serial=782 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /media/removable/ubuntu/chroots/xenial...
chronos@localhost /usr/local $ `

#### If known, describe the steps to reproduce the issue:

All I have done is followed the https://github.com/dnschneid/crouton/wiki/How-To-Install-To-External-Drive
I changed the drives name to ubuntu, and I made a link in /usr/local/chroots to /media/remoable/ubuntu/chroots
`sudo ln -s /media/removable/ubuntu/chroots chroots`

**Comment by MrHallway0** [comment] 2021-07-08 16:21
Duplicate of #4368.

**Closed** 2021-07-10 00:14 UTC
