### ISSUE TITLE
Need Freon support in xorg

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#1265] opened 2014-12-21 00:08 UTC
Hello,

   I've tried installing Ubuntu Trusty & Precise on my Acer C720-3404 twice. In between installs I turned Developer Mode off to clear any previous installs. I've used the following commands:

<code>
sudo sh -e ~/Downloads/crouton -t unity (1st attempt - precise)
</code>
<code>
sudo sh -e ~/Downloads/crouton -r trusty -t unity (2nd attempt - trusty)
</code>

As far as I can tell, there are no errors during installation, but every time I try to initiate unity (sudo startunity) I get the following error:

<code>
xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
</code>

I appreciate any help and I will post the entire initialization at the bottom of this post.

Regards,
Vialeport

/dev files:
<code>
chronos@localhost /dev $ dir
</code>

<code>
block             core               dm-1  hwrng   i2c-5  log    loop6         network_latency     ptmx    sda1   sda5  stderr  uhid     vhci
bsg               cpu                dri   i2c-0   i2c-6  loop0  loop7         network_throughput  pts     sda10  sda6  stdin   uinput   video0
bus               cpu_dma_latency    fb0   i2c-1   i2c-7  loop1  loop-control  null                random  sda11  sda7  stdout  urandom  zero
bus_throughput    cros_ec            fd    i2c-10  i2c-8  loop2  mapper        nvram               rfkill  sda12  sda8  tpm0    usbmon0  zram0
char              device_throughput  full  i2c-2   i2c-9  loop3  mcelog        port                rtc     sda2   sda9  tty     usbmon1
chromeos-low-mem  disk               fuse  i2c-3   input  loop4  mem           ppp                 rtc0    sda3   shm   tty1    usbmon2
console           dm-0               hpet  i2c-4   kmsg   loop5  net           pstore              sda     sda4   snd   tty8    v4l
</code>

Entire log:
<frame>
X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-70-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Dec 17 20:15:28 PST 2014 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=75bae8b0-f99d-5843-9de2-1f73b28f3080/PARTNROFF=1 hashtree=PARTUUID=75bae8b0-f99d-5843-9de2-1f73b28f3080/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=0035a6e81c87a14f2728ce7656a72489fc70c348 salt=635f605833ed8caf164b114f1ff1dece71e6d076b9881db47cf7f086302dca7e" noinitrd vt.global_cursor_default=0 kern_guid=75bae8b0-f99d-5843-9de2-1f73b28f3080 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3 
Build Date: 10 December 2014  06:15:52PM
xorg-server 2:1.15.1-0ubuntu2.6 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sat Dec 20 17:44:30 2014
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

</frame>

**Comment by reeved** [comment] 2015-01-09 20:57
Just checking, are you guys still working on this?

**Comment by DennisLfromGA** [comment] 2015-01-09 22:11
Yes, they are.

-DennyL

**Comment by reeved** [comment] 2015-01-10 15:59
cool :)

**Comment by dnschneid** [comment] 2015-01-12 17:52
For `startcli`, see [this bug](http://crbug.com/445003).  Star it if you're interested.

**Comment by AdrienCardoso** [comment] 2015-01-13 17:30
Before I powerwash back to stable unnecessarily, can someone confirm that if I do, I will get rid of freon and get HW Accel back again?

I was conviced that it'd be a fix, but now, I'm not sure anymore.

**Comment by drinkcat** [comment] 2015-01-28 16:33
A few notes regarding this:
 - Last I checked, the hack in a45f4afd773bb152eb6708e1679b53c4ed1e66d5 worked fine, and was fairly complete. Switching was seamless and very fast as no mode switching is done.
 - Changing resolution in X11 led to artifacts: We should find a way to prevent that, or support that properly.
 - There were backlight brightness problems (similar to #407).
 - Integration with crouton is missing (compile the hack, xserverrc wrapper etc.)
 - Integration with croutoncycle is also missing. One of the issues is that xbindkeys won't work in Chromium OS with freon. The extension can register shortcuts, but not the current ones (see https://developer.chrome.com/extensions/commands: Ctrl+Alt is forbidden, so are backward/forward keys).
 - I have not thought about how to handle multiple X servers (surely doable).
 - I don't think the current hack will play too well with frecon (I'm not even sure if/how we can detect that frecon is currently holding DRM)...
 - We need to get it right, as X server crashes if it cannot obtain DRM.

**Comment by dnschneid** [comment] 2015-01-29 16:10
Filed #1386 for croutoncycle stuff.

**Comment by dnschneid** [comment] 2015-02-07 04:42
Starting to work on integration in my x11_freon branch.

**Comment by dnschneid** [comment] 2015-02-07 06:16
Findings so far:

* I'm not so sure LD_PRELOAD is going to work. It gets wiped for setuid so we have to go through alternate paths (ld.so.preload) and it gets very messy and would probably result in an insecure X server.
* I can launch an X server by doing the following steps (of course, I don't have a proper way to kill it):
```
sudo touch /dev/tty2
sudo mount --bind /dev/null /dev/tty2
host-dbus dbus-send --system --dest=org.chromium.LibCrosService --type=method_call --print-reply /org/chromium/LibCrosService org.chromium.LibCrosServiceInterface.ReleaseDisplayOwnership
/usr/bin/X -sharevt vt2
host-dbus dbus-send --system --dest=org.chromium.LibCrosService --type=method_call --print-reply /org/chromium/LibCrosService org.chromium.LibCrosServiceInterface.TakeDisplayOwnership
```
* croutoncycle could easily manage display ownership.
* Not sure how to do the /dev/input/event grabbing without LD_PRELOAD.  Perhaps one option is to bind-mount /dev/input/event somewhere else, then have a daemon that grabs and pipes the true /dev/input/event data to the various X servers.  Not sure what other ioctls are in use though...

**Comment by dnschneid** [comment] 2015-02-08 22:30
xorg.conf:
```
Section "InputClass"
    Identifier "freon keyboard grab"
    Driver "evdev"
    Option "GrabDevice" "True"
    MatchIsKeyboard "On"
EndSection
```
seems to do what we want...although that of course is unlikely to behave correctly when switching.

**Comment by dnschneid** [comment] 2015-02-09 04:02
OK, having probably gone through all the same steps that @drinkcat went through originally, I've arrived back at @drinkcat's original implementation, feeling wiser and enlightened.

**Comment by dnschneid** [comment] 2015-02-10 08:02
Implementation is moving along (you can [try it out](https://github.com/dnschneid/crouton/archive/x11_freon.zip)).  Switching works, but it's not integrated with Chromium OS yet, so you'll have to manually run `sudo enter-chroot croutoncycle next` in a new tab to cycle to a running chroot.

**Comment by bertnic** [comment] 2015-02-10 08:32
Stumblled into the same problem and freon branch did the trick for me.
so #1398 is actually a duplicate of this.
So happy to have my ubuntu back :-)
Thanks again

**Comment by dnschneid** [comment] 2015-02-10 23:42
Oh, and if you install the extension and the extension target, you can switch via the extension's popup menu.

**Comment by reeved** [comment] 2015-02-12 22:50
How do I use the X11_Freon.zip ?

**Comment by dnschneid** [comment] 2015-02-12 23:15
Whoops, that should have been tar.gz.  Regardless, I'm going to start releasing prebuilt stuff so it's easier.

Download the crouton installer like normal, but when you run it, prepend with CROUTON_BRANCH=x11_freon.  So a command like this: `sudo CROUTON_BRANCH=x11_freon sh ~/Downloads/crouton -t xfce`...etc

**Comment by daviday** [comment] 2015-02-12 23:53
I haven't been spending as much time as I was on this as I was pretty happy with my unity build but am again having issues. I've searched freon, is there anything else I can/should read?

**Comment by daviday** [comment] 2015-02-12 23:53
Hats off to you guys btw.

**Comment by dnschneid** [comment] 2015-02-13 00:01
You can search for "unity" in the issue tracker.  This bug is not the right place to ask.

**Comment by dnschneid** [comment] 2015-02-15 02:25
Keyboard shortcut works now, so the x11_freon branch is getting pretty solid.  Please try it out `sudo CROUTON_BRANCH=x11_freon sh ~/Downloads/crouton ...` and let me know what breaks.

**Comment by dnschneid** [comment] 2015-02-15 03:00
One interesting issue: when installing a chroot, the trackpad loses the "australian scrolling" setting.  You have to log out/log in or set the setting to normal and back for it to reapply.

**Comment by reeved** [comment] 2015-02-15 21:47
If I were to use the x11_freon branch, would I have to redownload a whole new chroot?

**Comment by dnschneid** [comment] 2015-02-15 22:04
Nope, you can update your current chroot with the branch.

**Comment by Watney** [comment] 2015-02-20 06:50
@dnschneid CROUTON_BRANCH=x11_freon is working great with -n trusty -t xfce (w/o browser integration)

**Comment by dnschneid** [comment] 2015-02-20 23:35
Excellent!

**Comment by aquatix** [comment] 2015-02-23 07:00
Hey, I installed the x11_freon branch this weekend and was able to successfully get into my xfce4 chroot again. Awesomeness! Afterwards, ChromeOS was a quick ctrl+alt+shift+arrowback away, but apparently I can't switch to the still running chroot again?

I read about the extension and I was wondering if that would help me. Do I have to install from the same branch and if so, how exactly? I couldn't seem to find it in the source tree.

**Comment by dnschneid** [comment] 2015-02-24 00:59
You should be able to switch back and forth.  There was a bug that would cause it to not work on 32-bit systems, so try updating the chroot again with x11_freon and see if it works now.

If you install the extension target (directly or via a dependency), crouton will print out a link to the Chromium OS extension to install in the output at the very end if you don't have it installed already.

**Comment by Watney** [comment] 2015-02-24 18:45
@dnshneid more feedback on the x11_freon branch. First, I'm on 42.0.2305.2 dev (64-bit), Platform 6797.0.0 (Official Build) dev-channel glimmer_freon. 

I tried several fresh installs this morning using the x11_freon branch, and all met with disaster. I was *unable* to install ``-n trusty -t xfce,keyboard,xorg``. The script failed, and even after continuing the script and then an -u, it wouldn't launch. The error report was the 'ol ``UID 1000 not found``. 

I moved on and gave Gnome a shot. I *was able* to set up a basic ``-n trusty -t gnome,keyboard,xorg``. It sort of worked, but the super key (search) didn't bind. Next I tried ``-t gnome-desktop``, and it failed. (I'm sorry, but I didn't record the details.).

**Comment by dnschneid** [comment] 2015-02-25 00:12
The australian flop is a known issue with Chromium OS that's being addressed.

I tried `-r trusty -t xfce,keyboard,xorg` and it worked fine on a fresh install.  Could you post what error messages you're seeing in the install process?

**Comment by Watney** [comment] 2015-02-25 00:23
@dnschneid I'm sorry, David, but I foolishly didn't save the error messages.

**Comment by dnschneid** [comment] 2015-02-25 00:31
Well, next time you try it out, please post them.

**Comment by Watney** [comment] 2015-02-25 00:31
Will do!!

**Comment by hannibalhuang** [comment] 2015-02-25 12:40
HI dnschneid,

I sitll got the errors when I update my installation to the freon branch. I'm on dev channel using Samsung ARM Chromebook, the cmd I run is 

sudo CROUTON_BRANCH=x11_freon sh -e ~/Downloads/crouton -n trusty -t xfce,xiwi,extension -u

the errors:

usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
stdbuf: stdbuf: stdbuf: stdbuf: failed to run command 'hexdump': No such file or directorystdbuf: stdbuf: 
failed to run command 'hexdump': No such file or directory
failed to run command 'hexdump'failed to run command 'hexdump'failed to run command 'hexdump': No such file or directory: No such file or directory
failed to run command 'hexdump': No such file or directory

Do you have any ideas how could I solve this? THX

**Closed** 2015-02-26 19:25 UTC
Labels: bug, needstesting, upstreambug

**Comment by dnschneid** [comment] 2015-02-26 19:28
I think you have an old version of the installer.  The hexdump issue was fixed in 3d32410.

Anyway, I've merged the branch into master, so try updating without the CROUTON_BRANCH part.

**Comment by grit96** [comment] 2015-03-27 18:32
`host-x11` doesn't work with Freon, it just outputs `echo 'No Chromium OS X server is available.' 1>&2`

Chroot was created with `sudo sh Downloads/crouton -r trusty -t xfce,keyboard,xorg`

ChromeOS version 42.0.2311.60 Beta

Output of `sudo enter-chroot croutonversion`:
```
crouton: version 1-20150325193646~master:f7b2a0af
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce,keyboard,xorg
host: version 6812.52.0 (Official Build) beta-channel peppy 
kernel: Linux chromebook 3.8.11 #1 SMP Tue Mar 24 20:51:28 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

**Comment by dnschneid** [comment] 2015-03-27 19:13
Yep.  With Freon, there's no Chromium OS X server.  If you want similar functionality, try xiwi.

**Comment by grit96** [comment] 2015-03-27 19:26
That's a shame. It means I won't be able to use synergy in ChromeOS anymore.

I tried xiwi and still prefer having xfce on a separate display so I can
easily switch back and forth without Aura stealing my keybindings.

Do you plan on making xiwi the default?

**Comment by dnschneid** [comment] 2015-03-27 19:38
@grit96, nope!
