### ISSUE TITLE
Pass Arraylist as value from Mapper to reducer in Hadoop

### ISSUE THREAD

**Issue by silent23** [dnschneid/crouton#2473] opened 2016-03-02 19:07 UTC
Hi all,
I am working on a project which requires to pass data and have an **Arraylist** to be used
as a value emitted in <Key, Value> pair from the **Mapper** and collected in the **reducer**.
So, i wrote a custom data-type class implementing the Writable Interface and use it to pass
the # arraylist but i am facing _problems_ to implement the same. Kindly help.
.The code for the class is as following:-

import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;
import java.util.ArrayList;

import org.apache.hadoop.io.Text;
import org.apache.hadoop.io.Writable;

public class MyNestedArraylist<E extends Writable> extends ArrayList<E>
		implements Writable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public MyNestedArraylist() {
		super();
	}

	public MyNestedArraylist(ArrayList<E> fin) {
		//this.addAll(fin);
		super(fin);
	}

	/*
	 * (non-Javadoc) Deserializes the array
	 * 
	 * @see org.apache.hadoop.io.Writable#readFields(java.io.DataInput)
	 */
	public void readFields(DataInput in) {
		this.clear();
		try {
			int numFields = in.readInt();
			if (numFields == 0)
				return;
			String className = in.readUTF();
			E obj;
			Class c = Class.forName(className);
			for (int i = 0; i < numFields; i++) {
				obj = (E) c.newInstance();
				obj.readFields(in);
				
				this.add(obj);
			}
		} catch (IOException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			System.out.println(e.getMessage());
		} catch (InstantiationException e) {
			System.out.println(e.getMessage());
		}

	}

	/*
	 * (non-Javadoc) Serializes the array
	 * 
	 * @see org.apache.hadoop.io.Writable#write(java.io.DataOutput)
	 */
	@SuppressWarnings("unused")
	public void write(DataOutput out) {
		try {
			out.writeInt(this.size());
			
			System.out.println(out.toString());
			if (size() == 0)
				return;
			//Text obj;
			//Object obj = Object.class.cast(get(0));
			//Text t = new Text(this.get(0).getClass().getCanonicalName().toString());
			//System.out.println("text is:"+t.toString());
			//out.writeUTF(t.toString());
			System.out.println("in it:"+get(0).toString());
			E obj=get(0);
			
			out.writeUTF(get(0).getClass().getCanonicalName());
			//str.setReq(this.get(0).getClass().getCanonicalName().toString());
			//DbscannerString nm = new DbscannerString(str.getReq());
			//out.writeUTF(nm.t.toString());
			for (int i = 0; i < size(); i++) {
				System.out.println("i in nest"+i);
				//String first = this.get(i).toString();
				//DbscannerString obj = new DbscannerString(first);
				if (obj == null) {
					throw new IOException("cannot serialize null fields");
				}
				obj.write(out);
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	/*
	 * Generates Human readable String representation of this ArrayList
	 */
	public String toString()
	{
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		for(int i=0;i<this.size();i++)
		{
			if(i!=0)
				sb.append(",");
			sb.append(this.get(i));
		}
		sb.append("]");
		return sb.toString();
	}

}

**Comment by smibarber** [comment] 2016-03-02 19:17
HTTP/1.1 301 Moved Permanently
Location: http://www.stackoverflow.com

Dupe of #262

**Closed by smibarber** 2016-03-02 19:17 UTC
