### ISSUE TITLE
xiwi screen freezes and repeats last key stroke. Error: find_shm: Error running helper.

### ISSUE THREAD

**Issue by hsuijs** [dnschneid/crouton#2181] opened 2015-10-12 17:27 UTC
When I start my crouton session with xiwi in a window, after some time running I get screen freezes after which key strokes are repeated multiple times and sometimes the screen turns black for a second.

After the first freeze (which can take some time to appear) it gets worse really quickly with freezes every 10-30 seconds.

Most common errors around this time:
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...

See the complete log of a session:
X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Fri Sep 18 00:42:28 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=92ff718b-b6af-e344-ba30-7a3f500db8fd/PARTNROFF=1 hashtree=PARTUUID=92ff718b-b6af-e344-ba30-7a3f500db8fd/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=f9baec8f94f6518ad147cd0f0a28f37fd961cff2 salt=6f27c81451b6ac1d2c19b083045b515b6946c059cc8743bffcf8bdb36b21160d" noinitrd vt.global_cursor_default=0 kern_guid=92ff718b-b6af-e344-ba30-7a3f500db8fd add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Oct 12 13:09:57 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150924014025~master:04ff0c11
release: trusty
architecture: amd64
xmethod: xiwi
targets: gnome,xiwi,keyboard
host: version 7262.57.0 (Official Build) stable-channel auron_yuna 
kernel: Linux localhost 3.14.0 #1 SMP Fri Sep 18 00:42:28 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a window.
deciding for version 4 due to this line: # i3 config file (v4)
10/12/15 13:10:07 - ERROR: Could not translate string to key symbol: "button2"
Error: target STRING not available

(process:27350): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Error: target STRING not available
10/12/15 13:10:12 - ERROR: Could not translate string to key symbol: "button2"
10/12/15 13:10:12 - ERROR: Could not translate string to key symbol: "button2"
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
croutonwebsocket error: Unable to open display ':2'.Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
Running exit commands...
/usr/bin/xinit: connection to X server lost

**Comment by hsuijs** [comment] 2015-10-13 11:29
I just discovered that the repeating of a single keystroke happens independent from the above errors.

**Comment by hsuijs** [comment] 2015-10-15 04:39
I've created a whole new image with just xiwi trusty and installed firefox (like the chroot I had). I'm only using it to set up a citrix connection with a citrix receiver. With this new chroot the behavior is pretty much the same, but the errors are now somewhat different:

onnected to extension, launched crouton in a window.
deciding for version 4 due to this line: # i3 config file (v4)
10/14/15 14:51:26 - ERROR: Could not translate string to key symbol: "button2"

(process:21444): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(firefox:21444): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Failed to execute child process "dbus-launch" (No such file or directory)
10/14/15 14:51:34 - ERROR: Could not translate string to key symbol: "button2"
10/14/15 14:51:34 - ERROR: Could not translate string to key symbol: "button2"
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
write_image: Cannot find shm, moving on...
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
write_image: Cannot find shm, moving on...
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
write_image: Cannot find shm, moving on...
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
write_image: Cannot find shm, moving on...
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
write_image: Cannot find shm, moving on...
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
write_image: Cannot find shm, moving on...
Error: target STRING not available
Error: target STRING not available
croutonwebsocket error: Unable to open display ':1'.Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
write_image: Cannot find shm, moving on...
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
write_image: Cannot find shm, moving on...
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
write_image: Cannot find shm, moving on...
Error: target STRING not available
Error: target STRING not available
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
write_image: Cannot find shm, moving on...
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
croutonwebsocket error: Unable to open display ':1'.Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Error: target STRING not available
Running exit commands...
/usr/bin/xinit: connection to X server lost

**Comment by leeko** [comment] 2016-02-21 22:38
Hi, 

I'm having pretty much exactly the same issue. It makes my xfce environment pretty much unusable after 30 minutes or so. Did you ever figure out the cause? Let me know if there's any debug information I can provide. 

Thanks,

Lee

**Comment by monaka** [comment] 2016-06-11 07:23
I also have the same issue. And trying to fix.

In my case, findnacld shows log like below when `find_shm: Cannot open nacl file.` was shown.

```
popen2: child exited with status 1
find_nacl: Error running helper
```

**Comment by monaka** [comment] 2016-06-11 10:42
In addition. It seems I got the reason why this issue is caused. I'm testing my additional patch now.
I'll report results a couple of days later.

**Comment by monaka** [comment] 2016-06-12 05:08
I posted two pull requests #2621 #2622. Could someone try them?
This issue was fixed in my environment (at least).

**Closed** 2017-03-15 22:37 UTC
Labels: bug
