### ISSUE TITLE
Error when trying to install Kali 

### ISSUE THREAD

**Issue by thebutcher307** [dnschneid/crouton#4128] opened 2019-09-01 18:35 UTC
```
chronos@localhost / $ sudo edit-chroot -all
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20190807171712~master:6f45f06a
release: kali-rolling
architecture: amd64
targets: xfce
host: version 12239.67.0 (Official Build) stable-channel terra 
kernel: Linux localhost 3.18.0-19679-gd1d0bbedf35d #1 SMP PREEMPT Tue Aug 6 05:55:45 PDT 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### Please describe your issue:

I am trying to install Kali Linux on a Chromebook. Each time I've tired, I get an error.

"Preparing to unpack .../patch_2.7.6-6_amd64.deb ...
Unpacking patch (2.7.6-6) ...
Setting up patch (2.7.6-6) ...
patch set to automatically installed.
Compiling CRAS (i386)...
libcras/cras_client.c: In function 'handle_message_from_server':
libcras/cras_client.c:1730:12: error: converting a packed 'struct cras_client_message' pointer (alignment 1) to a 'struct cras_client_get_hotword_models_ready' pointer (alignment 4) may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1730 |    (struct cras_client_get_hotword_models_ready *)msg;
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
../src/common/cras_messages.h:91:37: note: defined here
   91 | struct __attribute__ ((__packed__)) cras_client_message {
      |                                     ^~~~~~~~~~~~~~~~~~~
../src/common/cras_messages.h:625:8: note: defined here
  625 | struct cras_client_get_hotword_models_ready {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling..."

![Screenshot 2019-09-01 at 12 24 44 PM](https://user-images.githubusercontent.com/54777729/64080739-fb12be80-ccb4-11e9-8a50-9049178f62bb.png)

**Comment by drinkcat** [comment] 2019-09-03 01:27
Dupe of #4119.

**Closed by drinkcat** 2019-09-03 01:27 UTC
