### ISSUE TITLE
sudo startunity

### ISSUE THREAD

**Issue by LaneBren** [dnschneid/crouton#3012] opened 2017-01-10 03:48 UTC
chronos@localhost ~ $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:04:16 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=899e5b5b-69e0-0546-9df2-1726d03c3c80/PARTNROFF=1 hashtree=PARTUUID=899e5b5b-69e0-0546-9df2-1726d03c3c80/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=4534f027f05bf44cd9353db7bc208a36aa165c8a salt=c3ddc1a30ef1cbe0cebdd1255c02d4495fee4eeb64329bc324ac6c74d226e063" noinitrd vt.global_cursor_default=0 kern_guid=899e5b5b-69e0-0546-9df2-1726d03c3c80 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Jan  9 23:41:58 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension

Please paste the output of the following command here: sudo edit-chroot -all

chronos@localhost ~ $ sudo edit-chroot -all
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 8872.73.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:04:16 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Having issue with unity. Similar to other startunity problems except this line:
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Any help would be appreciated!

**Comment by DennisLfromGA** [comment] 2017-01-10 18:16
Different target/desktop but still a dupe of #2970 I believe.

**Closed by DennisLfromGA** 2017-01-10 18:16 UTC
