### ISSUE TITLE
xiwi keyboard target isn't working

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1558] opened 2015-03-29 22:31 UTC
I created a chroot with 

```
sudo sh -e ~/Downloads/crouton -t unity,xiwi,keyboard -r trusty -n mychroot
```

The chomebook keys (e.g. search-left for home) work fine in a command line when I enter the chroot like

```
sudo enter-chroot -n mychroot
```

However in either desktop unity or xfce I don't get those bindings at all.  For example the search key acts like Super_L and opens up the unity dash.

I've read the keyboard wiki and it says it should just work.  I haven't tried any xmodmap stuff.  xmodmap is new to me.

chromebook pixel 2015
Version 41.0.2272.102 (64-bit)
Platform 6680.78.0 (Official Build) stable-channel samus
Firmware Google_Samus.6300.102.0

**Edit:** I've been studying the keyboard on chromebook in general.  After reading other posts I was given the impression that the chromebook overlay definition is stored under `/usr/share/X11`.  But that directory doesn't exist on my chromebook.  Where are the definitions stored?

**Comment by dnschneid** [comment] 2015-03-30 23:32
Can you check the keyboard settings in Unity?  It should have "model: chromebook" set in there somewhere.

**Comment by mark-hahn** [comment] 2015-03-31 00:45
The unity gui has setting windows for`Keyboard Settings` and `Text Entry` (see screen caps below) but can't find anywhere to put in normal text-file config options.  Do you know how to change that setting?

I found the `/etc/X11/xkb` directory but it was empty.  I found the `/etc/default/keyboard` file  which contained

```
XKBMODEL="pc105"
XKBLAYOUT="us"
XKBVARIANT=""
XKBOPTIONS=""
```

I tried changing each of `XKBMODEL` and `XKBLAYOUT` to "chromebook" but neither change made any difference.

BTW, this problem is the same in unity and xfce so I doubt it is a unity setting.  Actually, my end goal is to have this work with the Atom editor in a xiwi window.  Atom works great now in a xiwi window but it has this same keyboard problem. 

I'm sorry to be such a pain.  I promise that after asking all these questions and I become an  expert (grin), I'll start helping others.


![screenshot 2015-03-30 at 5 02 07 pm](https://cloud.githubusercontent.com/assets/811455/6909767/85be3570-d6fe-11e4-9e93-5bc2a951adc3.png)

![screenshot 2015-03-30 at 5 00 53 pm](https://cloud.githubusercontent.com/assets/811455/6909748/5aafc560-d6fe-11e4-8cf2-969116a31872.png)

**Comment by mark-hahn** [comment] 2015-03-31 19:03
More info .. 

I created a fresh unity chroot with the same command and the keyboard target still doesn't work in a desktop.  However I did notice some messages about the keyboard when unity was starting up the first time.  I don't know what they mean but I hope someone could tell me if they might be related to the problem.

```
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Compat map for group 2 redefined
>                   Using new definition
> Warning:          Compat map for group 3 redefined
>                   Using new definition
> Warning:          Compat map for group 4 redefined
>                   Using new definition
Errors from xkbcomp are not fatal to the X server
```

**Comment by mark-hahn** [comment] 2015-04-02 15:26
I want to bump this because it is a real pita to not have home, end, and backspace keys.

From my experience the last few days this has to be a problem on any Chromebook Pixel.  The key overlay doesn't work in either xfce or unity.  I started things fresh many times.

Does any other pixel user have these keys working?

**Comment by mark-hahn** [comment] 2015-04-03 04:48
I did a complete wipe/recovery of my chromebook, immediately installed unity with the command above, and the keyboard target didn't work.  

Does anyone have working home/end/del keys on any crouton install?

**Comment by mark-hahn** [comment] 2015-04-03 19:27
I guess it doesn't work for anyone if it ever did.  I have asked over and over if anyone else has the problem and no one replied until now.  A unity user verified the search-key combinations don't work at #1351.

I'm going to try to fix it.  If anyone is familiar with how the keyboard target is supposed to work and/or where to look for the code, can you please give me some advice?

**Comment by mark-hahn** [comment] 2015-04-04 21:55
Progress so far ...

I've found the keyboard layout at `/usr/share/X11/xkb/symbols/chromebook` and the `/usr/share/X11/xkb/rules/evdev` and `evdev.lst` and `evdev.xml` settings.  These are all created by the keyboard target and they look like they are set up properly according to my googling.  It is amazing how complicated all this xkb stuff is.

---

I haven't fixed anything but have found more clues from the xorg log created when the unity desktop was starting up.  Hopefully someone will understand this (author of keyboard target?) and give me a hand.

I cleared out `/tmp/Xorg.crouton.1.log` and then loaded unity.  I scoured the log and these sections from the resulting log are the ones that relate to the keyboard.  Note the message `Failed to load module "Warning, couldn't open module kbd` that occurs twice...

```
[ 16225.063] (==) ModulePath set to "/usr/lib/x86_64-linux-gnu/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[ 16225.063] (==) |-->Input Device "<default pointer>"
[ 16225.063] (==) |-->Input Device "<default keyboard>"
[ 16225.063] (==) The core pointer device wasn't specified explicitly in the layout.
        Using the default mouse configuration.
[ 16225.063] (==) The core keyboard device wasn't specified explicitly in the layout.
        Using the default keyboard configuration.

[ 16225.166] Initializing built-in extension XKEYBOARD

[ 16225.167] (II) LoadModule: "kbd"
[ 16225.168] (WW) Warning, couldn't open module kbd
[ 16225.168] (II) UnloadModule: "kbd"
[ 16225.168] (II) Unloading kbd
[ 16225.168] (EE) Failed to load module "kbd" (module does not exist, 0)

[ 16225.196] (II) LoadModule: "kbd"
[ 16225.196] (WW) Warning, couldn't open module kbd
[ 16225.196] (II) UnloadModule: "kbd"
[ 16225.196] (II) Unloading kbd
[ 16225.196] (EE) Failed to load module "kbd" (module does not exist, 0)
[ 16225.196] (EE) No input driver matching `kbd'
```

The following is from a random xorg log (`https://bbs.archlinux.org/viewtopic.php?id=76436`) I found on the web.  It specifies `edev` which mine didn't.

```
(II) XINPUT: Adding extended input device "USB Keyboard + Mouse" (type: KEYBOARD)
(**) Option "xkb_rules" "evdev"
(**) Option "xkb_model" "evdev"
(**) Option "xkb_layout" "us"
```

**Comment by mark-hahn** [comment] 2015-04-05 05:48
Probably no one is reading these posts but I'll keep posting what I've learned in my quest.  If nothing else some other poor newbie like me looking for input device setup help will find these.

I now know that evdev is getting loaded.  The evdev rules that matched are wrong though.  This came from a terminal inside the unity desktop ...

```
(trusty) $ setxkbmap -print -verbose 10
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc105
layout:     us
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us+inet(evdev)
geometry:   pc(pc105)
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+inet(evdev)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```

Note that this says `model: pc105` instead of the `model:chromebook` that @dnschneid referred to above.  I suspect this is related to the fact that the only input device listed in the `Text Entry` dialog is `us`.

The file loaded is `/usr/share/X11/xkb/rules/evdev.` which has the chromebook specified as ...

```
! model		=	symbols
  chromebook	=   +inet(evdev)+chromebook(overlay)
  $evdevkbds    =   +inet(evdev)+inet(%m)
  applealu_jis  =   +inet(evdev)+macintosh_vndr/jp(alujiskeys)
  *             =   +inet(evdev)
```
and
```
! model		layout		=	compat
  chromebook	*		=	complete+chromebook
  pc98		nec_vndr/jp	=	pc98(basic)
  *		jp		=	complete+japan
  olpc          *               =       olpc
  olpcm         *               =       olpc
  *		*		=	complete

! model		layout[1]	=	compat
  chromebook	*		=	complete+chromebook
  *		*		=	complete
```
This all looks like greek to me but I do know it has something to do with specifying that the chromebook symbols layout file should be used when the rules above match.   I'm assuming that there is something wrong with this evdev rules file for chromebook that keeps it from matching.  What this is trying to match and how the matching works are questions I need to answer next.

Once again, if anyone knows anything about any of this stuff I'd appreciate some help.

**Comment by DennisLfromGA** [comment] 2015-04-05 05:58
Mark,

I'm following along silently since I don't have any help to offer.
My reasons are a little selfish though 'cause I've got my eye on a new
Pixel 2 LS. ;)
Probably won't be 'til much later this year, maybe even Christmas before I
get one... :(

On Sun, Apr 5, 2015 at 1:48 AM, mark-hahn <notifications@github.com> wrote:

> Probably no one is reading these posts but I'll keep posting what I've
> learned in my quest. If nothing else some other poor newbie like me looking
> for input device setup help will find these.
>
> I now know that evdev is getting loaded. The evdev rules that matched are
> wrong though. This came from a terminal inside the unity desktop ...
>
> (trusty) $ setxkbmap -print -verbose 10
> Setting verbose level to 10
> locale is C
> Trying to load rules file ./rules/evdev...
> Trying to load rules file /usr/share/X11/xkb/rules/evdev...
> Success.
> Applied rules from evdev:
> rules:      evdev
> model:      pc105
> layout:     us
> Trying to build keymap using the following components:
> keycodes:   evdev+aliases(qwerty)
> types:      complete
> compat:     complete
> symbols:    pc+us+inet(evdev)
> geometry:   pc(pc105)
> xkb_keymap {
>     xkb_keycodes  { include "evdev+aliases(qwerty)" };
>     xkb_types     { include "complete"  };
>     xkb_compat    { include "complete"  };
>     xkb_symbols   { include "pc+us+inet(evdev)" };
>     xkb_geometry  { include "pc(pc105)" };
> };
>
> Note that this says model: pc105 instead of the model:chromebook that
> @dnschneid <https://github.com/dnschneid> referred to above. I suspect
> this is related to the fact that the only input device listed in the Text
> Entry dialog is us.
>
> The file loaded is /usr/share/X11/xkb/rules/evdev. which has the
> chromebook specified as ...
>
> ! model     =   symbols
>   chromebook    =   +inet(evdev)+chromebook(overlay)
>   $evdevkbds    =   +inet(evdev)+inet(%m)
>   applealu_jis  =   +inet(evdev)+macintosh_vndr/jp(alujiskeys)
>   *             =   +inet(evdev)
>
> and
>
> ! model     layout      =   compat
>   chromebook    *       =   complete+chromebook
>   pc98      nec_vndr/jp =   pc98(basic)
>   *     jp      =   complete+japan
>   olpc          *               =       olpc
>   olpcm         *               =       olpc
>   *     *       =   complete
>
> ! model     layout[1]   =   compat
>   chromebook    *       =   complete+chromebook
>   *     *       =   complete
>
> This all looks like greek to me but I do know it has something to do with
> specifying that the chromebook symbols layout file should be used when the
> rules above match. I'm assuming that there is something wrong with this
> evdev rules file for chromebook that keeps it from matching. What this is
> trying to match and how the matching works are questions I need to answer
> next.
>
> Once again, if anyone knows anything about any of this stuff I'd
> appreciate some help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1558#issuecomment-89721844>.
>



-- 
*DennyL@GMail*

**Comment by mark-hahn** [comment] 2015-04-05 19:23
Do any of the search-key combos work in a xiwi window/tab for you on your current setup?  For example `search-leftarrow` should do a `home`.  I've been suspicious that it doesn't work for anyone.

**Comment by mark-hahn** [comment] 2015-04-06 21:33
*Note: I have deleted a number of my posts in this thread because they told only   interim results of my search for the solution to this problem.  In other words it was too-much-information.*

> It should have "model: chromebook" set in there somewhere.

I finally found where the model should be set. I added this to the keyboard page of the wiki ...

"In order to make the bindings active you will need to edit `/etc/default/keyboard`. Change the line that starts with `XKBMODEL` to `XKBMODEL="chromebook"`. Your version of OS may require the keyboard model to be set in a different manner.".

Unfortunately I still don't have the keyboard mappings working on my setup but I know this requirement is correct.  In a terminal in a xiwi window I executed `setxkbmap -print -verbose 10` and saw the keyboard model was set to `pc105`.  I then executed `setxkbmap -model chromebook`.  When I did the `setxkbmap -print -verbose 10` again and saw the keyboard model was set to `chromebook`.  BTW, this is a good tool to use when checking your setting.

Another verification was that @lchulilla reported (#1574) that changing the model in `/etc/default/keyboard` fixed his keyboard problem.

Now I need to find the remaining problem in my setup.  I'll try to avoid blasting this thread with a zillion posts like I did before.

**Comment by DennisLfromGA** [comment] 2015-04-07 01:55
No problem for me at least, keep up the sleuthing, sounds like it's paying
off.

On Mon, Apr 6, 2015 at 5:33 PM, mark-hahn <notifications@github.com> wrote:

> *Note: I have deleted a number of my posts in this thread because they
> told only interim results of my search for the solution to this problem. In
> other words it was too-much-information.*
>
> It should have "model: chromebook" set in there somewhere.
>
> I finally found where the model should be set. I added this to the
> keyboard page of the wiki ...
>
> "In order to make the bindings active you will need to edit
> /etc/default/keyboard. Change the line that starts with XKBMODEL to
> XKBMODEL="chromebook". Your version of OS may require the keyboard model
> to be set in a different manner.".
>
> Unfortunately I still don't have the keyboard mappings working on my setup
> but I know this requirement is correct. In a terminal in a xiwi window I
> executed setxkbmap -print -verbose 10 and saw the keyboard model was set
> to pc105. I then executed setxkbmap -model chromebook. When I did the setxkbmap
> -print -verbose 10 again and saw the keyboard model was set to chromebook.
> BTW, this is a good tool to use when checking your setting.
>
> Another verification was that @lchulilla reported (#1574
> <https://github.com/dnschneid/crouton/issues/1574>) that changing the
> model in /etc/default/keyboard fixed his keyboard problem.
>
> Now I need to find the remaining problem in my setup. I'll try to avoid
> blasting this thread with a zillion posts like I did before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1558#issuecomment-90251609>.
>



-- 
*DennyL@GMail*

**Comment by jlchulilla** [comment] 2015-04-13 14:28
I have updated my report about the problem I mentioned on https://github.com/dnschneid/crouton/issues/1558

**Comment by mark-hahn** [comment] 2015-04-13 21:23
#1558 is this issue.  I'll search for yours.

**Comment by Sodman** [comment] 2015-04-16 04:19
I was seeing similar issues here with the pixel 2. Using gnome,keyboard,cli-extra, touch targets. Keyboard model was set to pc105 by default. Running on precise.

I updated the 'XKBMODEL' to 'chromebook' as mark suggested, and now it seems to be working as expected. Thanks!

**Comment by mark-hahn** [comment] 2015-04-16 20:31
That's not fair.  My suggestion fixed two other's problems and I can't fix
mine.  :-)  I guess I'll have to keep banging my head against it.

**Comment by tedm** [comment] 2015-04-16 20:42
@mark-hahn just close your eyes and keep typing, the files are small enough so that there is a finite number of alphanumeric combinations that will eventually fix anything here.

**Comment by mark-hahn** [comment] 2015-04-16 20:50
Are you calling me a monkey?  :-)

**Comment by tedm** [comment] 2015-04-16 21:21
nope, a programmer, and most likely with skills orders of magnitude better than my skills. Just noticing a pattern though that over the decades, code went from cryptic (early assembly days) to readable (pascal, well documented c/c++, OOPLs, etc.) back to cryptic shell programming in 2015. I helped Dr. William Shockley with some IT stuff in the mid '80s, and he was using APL, one of the most cryptic languages, I asked him why, and he went on for an hour, and then I wished I hadn't asked him (it was way over my head).

**Comment by mark-hahn** [comment] 2015-04-16 21:33
> back to cryptic shell programming in 2015

There has been cryptic shell programming since the early 70's.  I would
think there is less done now.  Crouton seems to be an exception to my
experience.  Why anyone would subject themselves to this torture is beyond
me.  Python can always be used instead of a shell.

> I helped Dr. William Shockley with some IT stuff

Then you must be an old guy like me.  :-)

**Comment by tedm** [comment] 2015-04-16 21:37
@mark-hahn Who are you calling old? :) GET OFF OF MY LAWN! :)

**Comment by DennisLfromGA** [comment] 2015-04-16 21:54
@tedm, @mark-hahn - I've probably got you both beat. :)

**Comment by mark-hahn** [comment] 2015-04-16 22:46
> I've probably got you both beat. :)

I'll call you on that.  I'm 65 and have been programming since 1966.

**Comment by DennisLfromGA** [comment] 2015-04-16 22:52
67 but only computing since the mid 70's (VIC-20) and programming since the 80's.

**Comment by tedm** [comment] 2015-04-17 17:17
A few behind you two at 54, but still get the AARP magazine every month :)

**Comment by cribalik** [comment] 2015-04-22 23:30
I am experiencing the same problem as Mark, and changing 'XKBMODEL' did the trick for all mappings except using the Search key for pageup/pagedown/home/end/...

Checking with xev, the Search key is indeed read as Overlay1_Enable when using xiwi but xev does not announce the KeyPress event for Overlay1_Enable until the Search key has been released! In contrast, when not using xiwi the KeyPress event is instantly registered. 

This could explain why no Searchkey+otherkey combinations work, if the KeyPress event is not registered until the Search key is released.

**Comment by mark-hahn** [comment] 2015-04-22 23:46
That matches my symptoms exactly.  I had taken a break from working on this
because I was burned out from working on it for weeks.

> This could explain why no Searchkey+otherkey combinations work, if the
KeyPress event is not registered until the Search key is released.

Ouch.  That sounds hard to fix.  We might need the pros, whoever they are,
to step in.

Once again, I am surprised no one else reported such a major problem.

**Comment by cribalik** [comment] 2015-04-23 00:14
It does sound hard to fix.. In the meantime, until we can find a solution, you can always map the Overlay1_Enable key to another key instead of the Search key so you at least can get some work done without going crazy: 

`xmodmap -e "keycode <insert keycode here> = Overlay1_Enable"`

**Comment by mark-hahn** [comment] 2015-04-23 01:32
Awesome, thanks.

**Comment by cribalik** [comment] 2015-04-23 04:07
After digging around a little, i found the problem. 

In order to send the correct keycodes from Chrome to X11, the xiwi extension performs a mapping from Chromes keycodes to the corresponding X11 keycodes. Or rather, the mapping uses the string representation of Chromes keycodes to map them to the X11 keycodes. The problem is that although the keycodes sent by pepper to the embedded code for ChromeOS' `PageDown/PageUp/Home/End` keys are correct, the string representations are **incorrect** (`'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'`).

I can make an attempt to rewrite the keycode mapping from using the string representations to the javascript keycodes, but it's just a workaround for a probable bug in Chrome.

**Comment by cribalik** [comment] 2015-04-23 04:25
Or, if this is a feature (maybe we want don't want Chrome to make the Search+Left => Home conversion and instead leave it up to X11), then the initial Search KeyDown event should perhaps be let through and not held until it is released, which is how it is now (lines 529-543 in kiwi.cc).

**Comment by mark-hahn** [comment] 2015-04-23 05:51
Let me know if either of those ideas work.  I wish I could help.

**Comment by cribalik** [comment] 2015-04-23 12:58
So i completely removed the logic added in [this fix](https://github.com/dnschneid/crouton/commit/9c5e1cc57e9aabb985534d52c7dedebf15bb5151) and it works! 

I think this code might be from earlier versions of Chrome where `OSLeft + Left` sent `Home`, but now that it sends the 'real' keypress (`Left`) i think that the fix is unnecessary.

**Comment by cribalik** [comment] 2015-04-23 13:13
Bad new for you though. I don't see a workaround other than cloning and building the extension yourself until the issue is fixed. If you cant wait until it is fixed, throw me an email :P

**Comment by mark-hahn** [comment] 2015-04-23 17:55
>  If you cant wait until it is fixed, throw me an email

I *am* feeling pain without the keys.  Is it hard to build?  I guess there
is no way to know when it will be fixed.  Who owns that code?

**Comment by mark-hahn** [comment] 2015-05-02 21:13
I forgot to mention here that I did throw @cribalik an email and he did fix my problem.  I'd like to publicly thank him.  It had to use his fork of the crouton extension but it has been working great for the last week.

**Comment by dnschneid** [comment] 2015-05-03 21:05
The issue isn't actually fixed (you have a workaround, which is nice), so keeping this open.

**Comment by cribalik** [comment] 2015-05-25 21:20
Until this issue is fixed, you are welcome to use my fork which has no other changes than this bugfix.

To install, simply clone my repository, go into `chrome://extensions` in the browser. Tick `developer mode` if you haven't already. Select `load unpacked extension` and browse to `crouton/host-ext/crouton` under the cloned repository.
Disable the original crouton extension and enable the newly loaded one.

If you want to save space, you can delete everything under crouton except the crouton/host-ext/crouton folder.

**Comment by ameily** [comment] 2015-05-27 19:23
I can confirm that @cribalik's fork fixes the issue, thank you! Can you do a PR to get this fix merged into master?

**Comment by cribalik** [comment] 2015-06-01 10:44
Just as an update; a PR is now up. Hopefully it will be merged soon :)

**Comment by mark-hahn** [comment] 2015-06-04 18:34
> Just as an update; a PR is now up. Hopefully it will be merged soon :)

I just found out the my problem with xiwi dying was due to your forked version of the extension.  When I when to the standard one xiwi started working again.  I don't know if your PR will have this problem.  How can I test your PR?

**Comment by cribalik** [comment] 2015-06-04 20:36
The master branch of my fork no longer has the fix. I moved the fix to the branch `tmpkeyfix`, would you mind changing to that branch and give it another try?

**Comment by mark-hahn** [comment] 2015-06-04 22:35
> simply clone my repository

I don't think you mentioned what repo you are talking about.  I keep looking it up in my email archives. (grin)

**Comment by cribalik** [comment] 2015-06-04 22:38
Heh, could've been clearer there. [My fork](https://github.com/cribalik/crouton) is what I am referring to.

**Comment by mark-hahn** [comment] 2015-06-04 22:50
>  I moved the fix to the branch tmpkeyfix, 

That branch fixed it.  Thanks.

**Comment by cribalik** [comment] 2015-06-04 22:52
Good. Sorry about moving it. ALWAYS branch first!

**Comment by mark-hahn** [comment] 2015-06-04 23:08
> That branch fixed it.

I should have said that it fixed the new bug of keeping the xiwi window from loading.  Unfortunately it doesn't fix the original problem with the keyboard anymore.  I know I'm loading the right branch `tmpkeyfix` because I see `kiwi.pexe` in `host-ext/crouton`.

I also know my keyboard model is set right in the window.  When I enter `'setxkbmap -model chromebook'` and then do `setxkbmap -print -verbose 10` in that window I get ...

```
Setting verbose level to 10                                                                               
locale is C                                                                                               
Applied rules from evdev:                                                                                 
rules:      evdev                                                                                         
model:      chromebook                                                                                    
layout:     us                                                                                            
Trying to build keymap using the following components:                                                    
keycodes:   evdev+aliases(qwerty)                                                                         
types:      complete                                                                                      
compat:     complete+chromebook                                                                           
symbols:    pc+us+inet(evdev)+chromebook(overlay)                                                         
geometry:   pc(pc104)                                                                                     
xkb_keymap {                                                                                              
        xkb_keycodes  { include "evdev+aliases(qwerty)" };                                                
        xkb_types     { include "complete"      };                                                        
        xkb_compat    { include "complete+chromebook"   };                                                
        xkb_symbols   { include "pc+us+inet(evdev)+chromebook(overlay)" };                                
        xkb_geometry  { include "pc(pc104)"     };                                                        
};                                                             
```

**Comment by cribalik** [comment] 2015-06-04 23:31
*sigh* my bad again. Okay, **now** the branch should actually fix something! Its a hassle to keep track of all the different compilations.

**Comment by mark-hahn** [comment] 2015-06-04 23:46
Thanks for doing this for us (which you may regret by now).

**Comment by cribalik** [comment] 2015-06-04 23:51
Haha no prob, but it would be nice to see the PR get accepted soon. Just tested it now, works fine on my machine. Are you having better luck on your end now?

**Comment by mark-hahn** [comment] 2015-06-04 23:55
Yes, works great.

I just noticed I don't have to do `setxkbmap -model chromebook` after the window loads anymore.  Just fixing `/etc/default/keyboard` once is all that is needed.  Is this something you fixed?

**Comment by cribalik** [comment] 2015-06-04 23:57
I'm afraid I had nothing to do with that, but that's great!

**Comment by mark-hahn** [comment] 2015-06-04 23:57
>  I don't have to do setxkbmap -model chromebook after the window loads anymore.

**Comment by mark-hahn** [comment] 2015-06-04 23:58
>  I don't have to do setxkbmap -model chromebook after the window loads anymore.

I lied.  The keyboard model is still being lost while the window opens.  Damn.

**Comment by cribalik** [comment] 2015-06-05 00:04
I think I found the script that is at fault for that. I might get up a fork tomorrow. Should we open up a new issue for that? This issue has kind of branched into two different ones..

**Comment by mark-hahn** [comment] 2015-06-05 00:11
This problem does relate to the initial problem.  It is stopping the fix
from working.

**Comment by mark-hahn** [comment] 2015-06-05 00:30
FYI, I just put `setxkbmap -model chromebook` in my `~/.xiwirc` file and I
don't have to deal with it any more.  If you can't fix this the right way
then I'll put that in the instructions.

**Comment by cribalik** [comment] 2015-06-05 14:33
Default setting of the keyboard model to chromebook is explicitly disabled on xiwi, which works fine for users not on Freon, where chromeOS's key combinations are sent, but us Freon users needz it!

So anywho I found it and fixed it, and it works on my machine. Would you mind being guinea-pig one more time @mark-hahn? Don't forget to remove the `setxkbmap` call in your `~/.xiwirc` file first!

copy [`croutonxinitrc-wrapper`] (https://github.com/cribalik/crouton/blob/freon-kbmodel/chroot-bin/croutonxinitrc-wrapper) into `/usr/local/bin/` (**make a backup copy of the old `/usr/loca/bin/croutonxinitrc-wrapper` first!**). The keyboard model should now be set to chomebook for new xiwi windows.

**Comment by mark-hahn** [comment] 2015-06-05 16:39
Will do.

**Comment by pcw120190** [comment] 2015-06-13 15:47
Hi, 

I've got a very similar issue to the problem you had getting the chromebook mapping to stick. I'm on a UK version of the c720p acer chromebook, I've manage to get it to keep the chromebook model option but when I change the layout to gb it doesn't stick. The change is effective immediately and I can type in the gb layout to begin with but the change is reverted when I log out.

It's just a bit of a pain to have to edit the /etc/defaults/keyboard file every time I log in. I don't know why it's not keeping the changes over log ins. Any help would be great,

Thanks,

Phil

**Comment by cribalik** [comment] 2015-06-13 22:55
@pcw120190 Are you using the crouton extension?

**Comment by pcw120190** [comment] 2015-06-13 23:14
@cribalik yes, I'm using xiwi now but I switched to that whilst trying to get the keyboard to work. The changes weren't persisting before I used xiwi either however.

**Comment by cribalik** [comment] 2015-06-13 23:27
@pcw120190 You can put files `.xiwirc` and `.xinitrc` in your home folder. they will be run at startup (`.xiwirc` when running xiwi, `xinitrc` otherwise). Try setting your keyboard layout there :)

**Comment by pcw120190** [comment] 2015-06-14 10:14
@cribalik Thanks, I've tried that but it's still not running the changes when I log in. After I log in and run `setxkbmap -print` it tells me the keyboard model is `pc105` and the layout is `us` despite having commands to change them to `chromebook` and `gb` in `~/.xiwirc`

**Comment by cribalik** [comment] 2015-06-14 14:18
@pcw120190 That the model is not set to `chromebook` is a bug, and a pull request is up to get that fixed. But that your commands are not run on startup is strange. I think you would be best off to create a separate issue for that :)

**Comment by dnschneid** [comment] 2015-06-17 23:32
Fixed, thanks to @cribalik.  Update and restart your chroots.

**Closed by dnschneid** 2015-06-17 23:32 UTC
Labels: bug

**Comment by GiowGiow** [comment] 2017-03-06 05:32
I have the same problem, xiwirc does not run any commands
