### ISSUE TITLE
kali-rolling install fails when attempting to download netsurf-gtk

### ISSUE THREAD

**Issue by mkirkhart** [dnschneid/crouton#2513] opened 2016-04-03 01:12 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all
```
sudo sh ~/Downloads/crouton -r kali-rolling -t xfce

#### Please describe your issue:
I noticed the kali sana release is no longer supported, and saw that kali-rolling (the new release) was added to the list of chroots.  Unfortunately, when I went to install it, the installation failed when attempting to download the netsurf-gtk package.  Upon further investigation, this package was removed from the kali-rolling package repositories. (http://pkg.kali.org/news/251836).

#### If known, describe the steps to reproduce the issue:
To reproduce, simply attempt to install kali-rolling, using the above command.

**Comment by nickurbanik** [comment] 2016-04-03 05:22
The same issue occurs with Debian stretch.

**Comment by DennisLfromGA** [comment] 2016-04-03 16:29
@mkirkhart,

The ['gtk-extra'](https://github.com/dnschneid/crouton/blob/master/targets/gtk-extra) target gets pulled in by the ['xfce'](https://github.com/dnschneid/crouton/blob/master/targets/xfce) target and that's where the 'netsurf-gtk' package is installed.

If, after the crouton installation fails, you modify the `prepare.sh` script to remove 'netsurf-gtk' and then let the `prepare.sh` script continue, it may succeed. See this https://github.com/dnschneid/crouton/issues/2260#issuecomment-166209184 for a similar situation where it was done.

**Comment by bpd1069** [comment] 2016-04-05 12:42
Same issue here, prepare.sh is removed after a failed setup
`E: Unable to locate package netsurf-gtk
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.`

Please advise.

**Comment by zxvv** [comment] 2016-04-05 17:44
I've submitted a pull request for a change that is intended to continue when installation of netsuft-gtk fails:

[https://github.com/dnschneid/crouton/pull/2516](url)

**Comment by solsticesolutions** [comment] 2016-04-07 08:06
Thanks for the fix, too bad ^W does not work very well inside of a Chrome window  (same command to close the window).

Deleting:

```
# if netsurf-gtk is not available (in certain debian and kali releases), fallback to dillow.
if install netsurf-gtk; then
    netsurf='/usr/bin/netsurf-gtk'
    for link in x-www-browser gnome-www-browser; do
        if ! update-alternatives --query "$link" | grep -q "$netsurf"; then
            update-alternatives --install "/usr/bin/$link" "$link" "$netsurf" 10
        fi
    done

```
And netsurf-gtk from the line above that has got my installation rolling again.

**Comment by msdos41** [comment] 2016-04-08 13:58
@solsticesolutions 

I modified prepare.sh and deleted the same lines as you mentioned, after my crouton installation failed. However, when I updated the installation (crouton -r kali-rolling -u), still the same error. Then I reopened prepare.sh, which turned back into the original status (still containing these netsurf-gtk lines).

I tried many times and still the same error, and I don't know if my command is wrong or what.

Could you tell me your detail command? or Do you find my command's fault?


P.S. Kali-rolling was installed on the sd card

Thank you

**Comment by solsticesolutions** [comment] 2016-04-08 16:43
Are you running update after changing the file? Doing that will download a
new prepare.sh.

Instead use the normal command to enter your chroot. Sudo enter
kali-rolling. It will be different in your case because of the location.

There will be a prompt that asks if you want to finish the setup process.
Say yes! Then it should complete the installation. It has quite a few more
files to download.

**Comment by zxvv** [comment] 2016-04-14 18:40
netsurf-gtk is not available in the repositories for certain most-recent releases of kali, debian and ubuntu.

various options to fix this are being discussed: 
https://github.com/dnschneid/crouton/pull/2516

For the moment, here is one potential workaround is:
omit xfce when creating the chroot, and install it afterward:

sudo sh -e crouton -r kali-rolling -t extrension,xiwi
enter-chroot
sudo apt-get install xfce4 xfce4-goodies xfce4-artwork xubuntu-icon-theme

**Comment by Penguination** [comment] 2016-07-02 22:45
I also have a workaround for this. What i did was I created a chroot with only xiwi as a target then I entered the chroot and added the debian jesse repo to my sources, then downloaded netsurf from there. After updating the chroot with xfce I am happy to say its working. 
To Recap
`1. sudo crouton -r kali-rolling -n kali -t xiwi
2. sudo enter-chroot -n kali
3. cd /etc/apt
4. sudo nano sources.list
5. add deb http://ftp.us.debian.org/debian jessie main 
6. sudo apt-get update
7. sudo apt-get install netsurf-gtk
8. exit
9. sudo crouton -u -n kali -t xfce
10. sudo start xfce4`
Done!

**Comment by donkeywrong** [comment] 2016-07-05 01:19
For step 5, is jessie supposed to be there, or do we replace it with out username?
After I complete Step5 (adding http://ftp.us.debian.org/debian jessie main),
Do I go back to the crosh shell and continue with 6?

**Comment by mrspedro** [comment] 2016-07-05 02:11
help i would like to install kali-rolling on xfce however it unable to locate netsurf please instruct me on how to properly install this.

**Comment by DennisLfromGA** [comment] 2016-07-05 17:28
@msdos41 - Take a look above - https://github.com/dnschneid/crouton/issues/2513#issuecomment-230125641

**Comment by Penguination** [comment] 2016-07-05 18:48
@donkeywrong Hmm thanks for bringing that up, I'll go ahead and update my workaround.

**Comment by mrspedro** [comment] 2016-07-08 01:12
@DennisLfromGA i have already try that however it didn't work. i would like to try the prepare.sh but i don't know how to get there. can someone tell me step by step.

**Comment by mrspedro** [comment] 2016-07-10 23:29
@Penguination Step 10 fails for me. i get this"The following packages have unmet dependencies:
 libc6-dev : Breaks: libc6-dev:i386 (!= 2.22-13) but 2.19-18+deb8u4 is to be installed
 libc6-dev:i386 : Depends: libc6:i386 (= 2.19-18+deb8u4) but 2.22-13 is to be installed
                  Depends: libc-dev-bin:i386 (= 2.19-18+deb8u4)
                  Depends: linux-libc-dev:i386 but it is not going to be installed
                  Breaks: libc6-dev (!= 2.19-18+deb8u4) but 2.22-13 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali..." please help me fix this

**Comment by nromsdahl** [comment] 2016-08-21 01:35
I compiled a version from my fork that just doesn't install netsurf.

https://sourceforge.net/projects/kalicrouton/files/kalicrouton/download

 sudo sh -e ~/Downloads/kalicrouton -r kali-rolling -t xfce

I'll work on fixing the larger issue, and requesting a merge when I have time, but for now this should work.

**Comment by pfunj002** [comment] 2016-08-23 21:36
Anyone know who/where to reach out to get these servers rebooted? 

Err:1 http://ca.mirror.babylon.network/kali kali-rolling/main armhf libpthread-stubs0-dev armhf 0.3-4
  503  Error [IP: 149.56.229.30 80]
Err:2 http://ca.mirror.babylon.network/kali kali-rolling/main armhf xorg-sgml-doctools all 1:1.11-1
  503  Error [IP: 149.56.229.30 80]
Err:3 http://ca.mirror.babylon.network/kali kali-rolling/main armhf x11proto-core-dev all 7.0.29-1
  503  Error [IP: 149.56.229.30 80]

**Comment by donkeywrong** [comment] 2016-08-26 15:12
Something else I noticed is that you may need the crouton extension in the chrome browser if you're trying to install on a chromebook using the crouton method

**Comment by willchertoff** [comment] 2016-08-29 23:18
@Penguination I am getting an ```Error: not connected. Unable to start display, make sure the crouton extension is installed and enabled``` when attempting step 11.

**Comment by donkeywrong** [comment] 2016-08-30 05:34
Make sure you download the crouton extension on google chrome on your chrome OS
https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom

**Comment by DennisLfromGA** [comment] 2016-08-30 13:40
The 'Crouton Integration' extension from the Chrome Web Store mentioned above is required when you install the 'xiwi' target/xmethod.

**Comment by mikesackett85** [comment] 2016-08-31 22:05
Any update on this?

**Comment by choas0422** [comment] 2016-08-31 22:11
@mikesackett85 

solsticesolutions had the right idea. as soon as i removed those lines from the prepare.sh script it worked right away.

**Comment by mikesackett85** [comment] 2016-08-31 22:14
Great news, I will go that route.  Thank you!

**Comment by mikesackett85** [comment] 2016-08-31 23:21
Sorry for the noob question here but I'm just wondering which prepare.sh file to edit, I grabbed the master zip file and then attempted to edit the first one that I found but there weren't any lines calling for the installation of netsurf.

**Comment by DennisLfromGA** [comment] 2016-09-01 16:23
@mikesackett85,

The `prepare.sh` script is built *on-the-fly* depending on which targets you specify and will be placed in the root directory of your chroot.

When the crouton install fails, just go back into your chroot using `enter-chroot` and answer 'n' when asked if you want to let it finish. You'll then drop to a shell and you can edit `/prepare.sh` to remove 'netsurf-gtk'.

You can exit then and re-enter the chroot using enter-chroot to let it finish the setup.

Hope this helps,
-DennisL

**Comment by tolman42** [comment] 2016-09-08 23:38
Pengiunation's comment got it to work for me.  Thank you so much!  It's a big relief to have installing a new distro take 2 hours instead of 3 days.

**Comment by dnschneid** [comment] 2016-10-11 19:00
Merged in the fix for this, so you shouldn't need to manually modify things anymore.  Sorry this took so long!

**Closed by dnschneid** 2016-10-11 19:00 UTC
Labels: P2
