### ISSUE TITLE
ctrl+shift+alt+forward/back not working

### ISSUE THREAD

**Issue by mmarkle** [dnschneid/crouton#2179] opened 2015-10-11 23:44 UTC
ctrl+shift+alt+forward/back not working on HP Chromebook 14 running Chrome OS canary 40. The only way I can get back to Chrome OS is by logging out.

**Comment by DennisLfromGA** [comment] 2015-10-12 18:16
You could try switching from your chroot to Chrome OS via the command line. In a chroot shell (terminal), enter: `croutoncycle cros`

Then you can switch from Chrome OS to your chroot via clicking on your chroot name in the *'crouton integration'* extension window if you have it installed.﻿

**Comment by chrisofCCL** [comment] 2015-10-29 15:34
This one is like the common cold - similar symptoms but many potential causes!  I had a similar and long running issue( #1699) with my Asus C300. Finally solved by mkasick: 

"I think I might've sorted this out in #2003. The only discrepancy is that the xserver-xorg-video-intel package that ships with trusty does not have the change the causes the problem, but utopic does. Installing an LTS backport or PPA version probably would though."

So check out #2003.  However, that patch was merged with the master on 11 Aug so if your version of the crouton installer is older than that, update it and then update your chroot.  If not, I'm afraid it's a different problem.

Chris

**Comment by shelleyvadams** [comment] 2016-06-08 01:30
> like the common cold

For sure!

Tried to install the newer version of xserver-xorg-video-intel from jessie-backports -- replacing [2:2.21.15-2+b2][jessie] with [2:2.99.917+git20160522-1~bpo8+1][backports] -- to [fix a bug][reddit] with shadows on GTK-3 windows in GNOME 3.14 

Anybody know if the Intel driver is causing problems in stretch? If not, I may trade in my jessie chroot for stretch.

```
$ croutonversion
crouton: version 1-20160518095657~master:fd37bb79
release: jessie
architecture: amd64
xmethod: xorg
targets: gnome
host: version 8172.47.0 (Official Build) beta-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Wed Jun 1 23:05:52 PDT 2016 x86_64 GNU/Linux
freon: yes
```

[jessie]: https://packages.debian.org/jessie/xserver-xorg-video-intel
[backports]: https://packages.debian.org/jessie-backports/xserver-xorg-video-intel
[reddit]: https://www.reddit.com/r/debian/comments/3augqu/csd_windows_shadow_bug_fix_for_intel/

**Comment by drinkcat** [comment] 2016-10-11 19:29
Don't think there is anything actionable in the issue.

**Closed by drinkcat** 2016-10-11 19:29 UTC
