### ISSUE TITLE
after crouton update -u kali won't start X (connection refused)

### ISSUE THREAD

**Issue by The1andONLYdave** [dnschneid/crouton#2997] opened 2017-01-03 21:23 UTC
```
name: kali
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali...
crouton: version 1-20161129162558~master:5f2f11f9
release: kali-rolling
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 9000.29.0 (Official Build) beta-channel cyan 
kernel: Linux localhost 3.18.0-13497-gbec0bdb #1 SMP PREEMPT Wed Dec 14 22:05:02 PST 2016 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/kali...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.0
Release Date: 2016-11-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.18.0-13497-gbec0bdb #1 SMP PREEMPT Wed Dec 14 22:05:02 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=1d4d5bda-7556-364a-b7cf-105796f2ff37/PARTNROFF=1 hashtree=PARTUUID=1d4d5bda-7556-364a-b7cf-105796f2ff37/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=4e2c477dd543151f7a10719395701f4fec7df592 salt=d6d9f861b6b203f45699385a91b4bb1911a91ddc36bb4e35fdac797f572bbc9f" noinitrd vt.global_cursor_default=0 kern_guid=1d4d5bda-7556-364a-b7cf-105796f2ff37 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 16 December 2016  07:30:27PM
xorg-server 2:1.19.0-3 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.3.log", Time: Tue Jan  3 22:18:22 2017
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/lib/xorg/Xorg: symbol lookup error: /usr/lib/xorg/modules/drivers/dummy_drv.so: undefined symbol: ChangeWindowProperty
 sudo startxiwi -b xterm/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error

#### Broke yesterday after:
Inside Kali: croutonversion -u -d -c 
Exit; 
Outside chroot: sudo sh ~/Downloads/crouton -u -n kali
(Finished without errors, now won't start X, but enter-chroot works)

Redownloading crouton-script and re-renning update command above won't fix it.

**Comment by DennisLfromGA** [comment] 2017-01-03 21:51
@The1andONLYdave,

It reported an Xorg log here:

> (++) Log file: **"/tmp/Xorg.crouton.3.log"**, Time: Tue Jan 3 22:18:22 2017

Could you post the output of that log file or give us a gist or pastebin link, etc. to it please?

-**DennisL**

**Comment by bigeagle** [comment] 2017-01-04 14:49
＃2953 would help

**Comment by The1andONLYdave** [comment] 2017-01-04 17:30
I created a new log with same error: http://pastebin.com/maM0eAMw

**Comment by DennisLfromGA** [comment] 2017-01-04 18:26
@The1andONLYdave,

Thanx for the Xorg log.
I'm afraid I'm out of my depth when it comes to analyzing and interpreting the data, I'm hoping someone more knowledgeable about it might be able to help.

Of note though I think are these GLX entries:
```
[ 13108.059] (II) LoadModule: "glx"
[ 13108.062] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[ 13108.082] (II) Module glx: vendor="X.Org Foundation"
[ 13108.082]    compiled for 1.19.0, module version = 1.0.0
[ 13108.082]    ABI class: X.Org Server Extension, version 10.0
```
and further down:
```
[ 13108.101] (II) AIGLX: Screen 0 is not DRI2 capable
[ 13108.101] (EE) AIGLX: **reverting to software rendering**
```

And there are some about the DUMMY driver too:
```
[ 13108.083] (II) DUMMY: Driver for Dummy chipsets: dummy
[ 13108.083] (WW) Falling back to old probe method for dummy
[ 13108.083] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
```

I'm afraid I don't know if these warnings relate to 'xinit giving up' or not though.

Maybe the issue is the one mentioned by @bigeagle above concerning the `/usr/lib/xorg/Xorg: symbol lookup error` ???

*Hope this helps,*
-**DennisL**

**Comment by middleagedman** [comment] 2017-01-17 03:48
@bigeagle 
I don't suppose you can give us a short tutorial about how to do that?  I know how to git clone and such, and make as well.  Did you just do it inside your chroot and make install?

**Comment by bigeagle** [comment] 2017-01-17 03:55
@middleagedman No, I did this on my Linux PC. 
`` 
git clone https://github.com/nxtr/crouton 
git checkout origin/xiwi-xf86-video-dummy-0.3.8
make
```
you'll get a runnable crouton script.

**Comment by middleagedman** [comment] 2017-01-17 04:00
@bigeagle 
Thanks!  I do have the misfortune of having a x86 linux box and a rockchip asus flip, but I'll see if I can narrow a build environment for just the video-dummy

**Comment by middleagedman** [comment] 2017-01-17 04:03
*facepalm* nm.. make just builds an installer script.  Good to go

**Comment by jernic** [comment] 2017-01-18 10:19
In case anyone has similar problems, I had to do the following to overcome this error:
$ enter the chroot
$ sudo apt-get install git
$ git clone https://github.com/nxtr/crouton
$ cd crouton
$ git checkout origin/xiwi-xf86-video-dummy-0.3.8
$ sudo apt-get install make
$ make
$ cp crouton ../Downloads/

However, this still didn't solve the problem, so I ran the crouton update (-u) using the new crouton script. Then it worked. :-)

**Comment by HedleyPty** [comment] 2017-02-08 07:33
I have the same problem but with sid

**Comment by dnschneid** [comment] 2017-03-16 01:34
I think this fix has been merged.

**Closed by dnschneid** 2017-03-16 01:34 UTC
