### ISSUE TITLE
How to get Youtube History in android programmatically

### ISSUE THREAD

**Issue by anagham** [dnschneid/crouton#1593] opened 2015-04-08 10:21 UTC
I am developing an android application to get youtube history in android app. I read about Youtube Player API but it is only to play videos. Also I referred Youtube Data API V3 but I am not getting how to utilize it. Guide me regarding the same.

**Comment by MAkerboom** [comment] 2015-04-08 11:17
How is this crouton related?

**Comment by smibarber** [comment] 2015-04-08 15:34
Dupe of #262.

**Closed by smibarber** 2015-04-08 15:34 UTC

**Comment by mohitkha** [comment] 2016-12-29 12:32
I am developing an android application to get youtube history in android app.  how it possible
