### ISSUE TITLE
Can't install crouton on samsung chromebook plus

### ISSUE THREAD

**Issue by mesahusa** [dnschneid/crouton#3111] opened 2017-02-24 04:29 UTC
```
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

#### Please describe your issue:
I followed a guide to install crouton, and after it prompts me to type in a username, it pulls out this message. I read some other forums and updated the program, and now it tells me: 

UID 1000 not found in precise

I then uninstalled it, and tried installing trusty version. This time, it let me create a username and password, but wouldn't run, giving me:

Segmentation fault at address 0x0
Caught signal 11 (Segmentation fault). Server aborting

I apologize if I'm not using the right terminology or format, I'm new to this. 

#### If known, describe the steps to reproduce the issue:
Try to install crouton on samsung chromebook plus

**Comment by DennisLfromGA** [comment] 2017-02-24 14:32
Mostly likely duplicate of: https://github.com/headmelted/code-builds/issues/12, https://github.com/dnschneid/crouton/issues/3098 & https://github.com/dnschneid/crouton/issues/3083

**Closed** 2017-03-15 16:47 UTC
