### ISSUE TITLE
Snap does not work on supported Debian and Ubuntu releases.

### ISSUE THREAD

**Issue by vastraz** [dnschneid/crouton#4583] opened 2021-08-30 04:24 UTC
```
Entering /mnt/stateful_partition/crouton/chroots/stretchxfce...
crouton: version 1-20210817115015~master:d607c558
release: stretch
architecture: amd64
xmethod: xorg
targets: xfce,extension
host: version 13982.69.0 (Official Build) stable-channel snappy 
kernel: Linux localhost 4.4.254-20533-gcb85bd3a0149 #1 SMP PREEMPT Thu Jul 29 21:56:25 PDT 2021 x86_64 GNU/Linux
freon: yes
```

Attempting to use Snap with the packages "snap" and "snapd" installed will produce this error upon entering a command to install a Snap package (that being "sudo snap install package-name").

```
error: cannot communicate with server: Post http://localhost/v2/snaps/package-name: dial unix /run/snapd.socket: connect: no such file or directory
````

Upon attempting to troubleshoot this using information acquired on various forums I found by copy and pasting that error into Google, I ran into many more errors related to "systemd" and "systemctl" which I cannot comprehend.

I replicated this on Debian Stretch KDE and XFCE4 alongside Xenial GNOME.

**Comment by BetaPictoris** [comment] 2021-08-30 15:15
Duplicate of #4553.

**Closed** 2021-09-01 02:10 UTC
