### ISSUE TITLE
debian buster  wont install

### ISSUE THREAD

**Issue by danielfm123** [dnschneid/crouton#3936] opened 2018-11-12 10:35 UTC
#### Please describe your issue:

sudo sh ./crouton -t xiwi,keyboard,extension,cli-extra,audio -r buster -n debian -m http://ftp.cl.debian.org/debian/ wont work

#### If known, describe the steps to reproduce the issue:

sudo sh ./crouton -t xiwi,keyboard,extension,cli-extra,audio -r buster -n debian -m http://ftp.cl.debian.org/debian/

will fail on something related to audio

**Comment by mikehgentry** [comment] 2018-11-12 11:37
This is a duplicate of #3930

**Comment by mikehgentry** [comment] 2018-11-13 00:32
Read the rest of the bug

**Closed** 2018-11-13 17:16 UTC
