### ISSUE TITLE
xiwi screen painting broken in chromeos beta channel

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#2692] opened 2016-07-24 03:43 UTC
```
name: roo
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/roo...
crouton: version 1-20160715134041~master:0dc76a22
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,keyboard
host: version 8350.60.0 (Official Build) beta-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 20 21:30:42 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

The windows in xiwi are screwed up.  Random sections of the window will scroll and update and other parts will not paint.   Also I can't get the UI to respond whether I try in the working part of the window or outside.  This happens with all apps.

This occured after I upgraded my chromeos channel to beta from stable.  I will try going back to stable.

Edit: Said dev channel but meant beta.

**Comment by divx118** [comment] 2016-07-24 07:25
@mark-hahn Just in case you didn't know. Going back to stable means a power wash. So remember to backup your chroots before doing it.

**Comment by mark-hahn** [comment] 2016-07-25 01:08
When I went back to stable the problem went away.

Isn't this going to be a big problem when the chrome bug/change gets to stable?  Can someone fix this now using the beta channel so we don't have to scramble later?

BTW, I can describe the problem better now.  Only the upper left of any pane will paint until you click anywhere in the pane.  Then the whole pane will paint.  This happens no matter what is requesting the repaint.  I noticed this upper left is the same area that shows when the xiwi window opens but before it resizes to the correct size.  So something doesn't get updated when the size is increased.

**Comment by plee3** [comment] 2016-07-28 04:33
Just updated to latest stable channel and this problem is now occurring on my Pixel 2.
Here is the current version info:

crouton: version 1-20160715134041~master:0dc76a22
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,audio,core,cli-extra,extension,keyboard,touch,xfce
host: version 8350.60.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 20 21:30:42 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by mark-hahn** [comment] 2016-07-28 05:02
Ouch, I can't live without xiwi but I can't stop a stable update, can I?

**Comment by jaduncan** [comment] 2016-07-29 18:09
Confirmed on Pixel 2/Samus stable channel with both old abd newly created chroots. Looks like it is a ChromeOS issue.

**Comment by mark-hahn** [comment] 2016-07-29 20:29
Does this only happen with xiwi?  I only run with xiwi now and I wonder what the alternatives are.  What is the Xorg option?  I've never understood the difference.  And does the problem happen with full-screen xiwi alternatives?

**Comment by plee3** [comment] 2016-07-29 20:48
Xorg seems to work OK, but you need to deal with the issue of Xfce not handling HiDPI well on the Pixel. You can refer to the wiki about using crouton on Pixel for some options on handling the high resolution.

**Comment by jaduncan** [comment] 2016-07-30 08:42
Xorg opens in a separate screen, so it's full screen and independent - you can't window it. I'd heavily recommend Gnome hidpi wise, it resizes things.

**Comment by mark-hahn** [comment] 2016-07-30 19:35
Stable got to me so goodbye xiwi.  I'm installing xfce and xorg now.  This will make the experience of using crouton much worse.  I have always run xiwi by itself with no linux desktop and was very happy.

**Comment by bodil** [comment] 2016-08-02 12:50
Things started breaking for me too with the latest stable upgrade on my Pixel 2. Xiwi windows seem to work fine until I resize them, after which only the top left quadrant seems to be updating.

For reference, these are the relevant version numbers:

> Version 52.0.2743.85 (64-bit)
> Platform 8350.60.0 (Official Build) stable-channel samus
> Firmware Google_Samus.6300.174.0

**Comment by drinkcat** [comment] 2016-08-02 13:17
Does changing the internal panel resolution fix the problem? e.g. change to 1280x850?

Looks like there is an issue with hidpi handling...

**Comment by ryanphjohnson** [comment] 2016-08-02 14:58
Just here to pile on: I'm on Chromebook Pixel 2, updated to ChromeOS v52, now Xiwi is behaving differently. I use it to run eclipse. The first pop up asking for which workspace I want works fine. The moment I select a workspace the window goes black (as it always has) but never repaints (window remains black) once eclipse opens the workspace. Hope this helps

**Comment by drinkcat** [comment] 2016-08-03 00:26
2 workarounds for now:
 - Enabling "debugging" mode in extension fixes the issue (then there is then a bar on top of the screen).
 - Switching resolution to native 2560x1700 (instead of hi-dpi "fake" 1280x850), also fixes the problem.

**Comment by drinkcat** [comment] 2016-08-03 01:16
Looks like a Chrome (OS) bug: Filed https://bugs.chromium.org/p/chromium/issues/detail?id=633806, feel free to star, but please refrain from commenting unless you have something important to add.

**Comment by sethml** [comment] 2016-08-28 19:26
The Chromium bug is marked fixed, so hopefully on the next upgrade this'll be fixed.
https://bugs.chromium.org/p/chromium/issues/detail?id=633806

**Comment by phedders** [comment] 2016-08-31 16:15
As of the last reboot, seems to be fixed here (Dev channel) Yey!

**Comment by tabatkins** [comment] 2016-09-01 21:46
Fixed on Aug 24, and it's trying to get backported to the 53 release coming out now.  Worst case it'll be in the 54 release in six weeks!

**Closed** 2016-10-11 16:34 UTC
Labels: crosbug
