### ISSUE TITLE
Can't install kali-rolling with kde.

### ISSUE THREAD

**Issue by wolfy01** [dnschneid/crouton#4557] opened 2021-07-25 17:06 UTC
I ran this command: `sudo crouton -t kde -r kali-rolling`. Everything was going well until it had this error: 
```
E: Unable to locate package kde-runtime
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### Please describe your issue:
I cannot install kali-rolling with kde.

#### If known, describe the steps to reproduce the issue:
Run this command: `sudo crouton -t kde -r kali-rolling`.

**Comment by MrHallway0** [comment] 2021-07-25 18:48
Maybe [this](https://gist.github.com/jayluxferro/5cb6ee45726bd30264918df2b0553b70#kde-desktop) will help, you could manually install the desktop.

**Comment by wolfy01** [comment] 2021-07-25 18:50
> Maybe [this](https://gist.github.com/jayluxferro/5cb6ee45726bd30264918df2b0553b70#kde-desktop) will help, you could manually install the desktop.

I do not have access to apt or apt-get because I am using the `shell` that you get with `ctrl+alt+t`

**Comment by DennisLfromGA** [comment] 2021-07-25 18:53
@wolfy01,

This issue was reported for a 'bullseye' release also, see the explanation linked below:  
- https://github.com/dnschneid/crouton/issues/4453#issuecomment-817160556  

Unfortunately, this won't get resolved until a pull request to remove it gets initiated, reviewed, and merged.

*Hope this helps,*
-**DennisLfromGA**

**Comment by wolfy01** [comment] 2021-07-25 18:59
> @wolfy01,
> 
> This issue was reported for a 'bullseye' release also, see the explanation linked below:
> 
> * [Unable to install kde desktop in  #4453 (comment)](https://github.com/dnschneid/crouton/issues/4453#issuecomment-817160556)
> 
> Unfortunately, this won't get resolved until a pull request to remove it gets initiated, reviewed, and merged.
> 
> _Hope this helps,_
> -**DennisLfromGA**

Is there any possible workaround currently?

**Comment by wolfy01** [comment] 2021-07-25 19:04
I guess I could try to use `xfce` then inside kali remove it and install kde? I wonder if that would break something though.

**Comment by DennisLfromGA** [comment] 2021-07-25 19:08
@wolfy01,

You could modify crouton to remove the kde-runtime line in the kde-target, see these instructions for more about that:
- [If you're modifying crouton ...](https://github.com/dnschneid/crouton#:~:text=If%20you%27re%20modifying%20crouton)

And, yes, you can try other desktop targets, I use lxde or lxde-desktop since it has a small footprint and works well for me.

*Hope this helps,*
-**DennisLfromGA**

**Comment by wolfy01** [comment] 2021-07-25 20:04
> @wolfy01,
> 
> You could modify crouton to remove the kde-runtime line in the [kde-target](https://github.com/dnschneid/crouton/blob/master/targets/kde#L12), see these instructions for more about that:
> 
> * [If you're modifying crouton ...](https://github.com/dnschneid/crouton#:~:text=If%20you%27re%20modifying%20crouton)
> 
> And, yes, you can try other desktop targets, I use lxde or lxde-desktop since it has a small footprint and works well for me.
> 
> _Hope this helps,_
> -**DennisLfromGA**

Ive decided to powerwash my device because it started saying "uid 1000 not found in kali"  and anything I tried sadly didnt work

**Comment by DennisLfromGA** [comment] 2021-07-26 15:34
@wolfy01,

Powerwashing to remove a crouton chroot is ...
![image](https://user-images.githubusercontent.com/3418772/127015675-d6f6a90a-5318-4f98-b6c5-f61e95ee943a.png)

Next time just use:   
- `sudo delete-chroot -a [-c CHROOTS]`   

That way *only* your chroots are removed, not all user profiles & data. 

*Hope this helps,*
-**DennisLfromGA**

**Closed by DennisLfromGA** 2021-07-26 15:34 UTC

**Comment by wolfy01** [comment] 2021-07-26 15:37
> @wolfy01,
> 
> Powerwashing to remove a crouton chroot is ...
> ![image](https://user-images.githubusercontent.com/3418772/127015675-d6f6a90a-5318-4f98-b6c5-f61e95ee943a.png)
> 
> Next time just use:
> 
> * `sudo delete-chroot -a [-c CHROOTS]`
> 
> That way _only_ your chroots are removed, not all user profiles & data.
> 
> _Hope this helps,_
> -**DennisLfromGA**

I am very well aware of that, and that's what I did. But when I Re-installed kali it resulted in this error: `uid 1000 not found in kali`. And nothing I did fixed it. The only thing that worked was powerwashing to remove anything that was changed and couldnt be reverted for some reason

**Comment by DennisLfromGA** [comment] 2021-07-26 15:50
@wolfy01,

> I am very well aware of that, and that's what I did. But when I Re-installed kali it resulted in this error: uid 1000 not found in kali. And nothing I did fixed it.

The error:
> uid 1000 not found in kali  

Simply means the crouton chroot installation bailed (errored out) before it even created a user id 

kali and some other distros like bullseye ***will not*** install with the current kde target due to the kde-runtime package as explained above. Other desktop targets should work in kali, also explained above.

> The only thing that worked was powerwashing to remove anything that was changed and couldnt be reverted for some reason

Again, it's not necessary to powerwash if the issue is with a crouton chroot but to each his/her own.

*Hope this helps,*
-**DennisLfromGA**
