### ISSUE TITLE
startxfce4 not working on freshly installed precise chroot

### ISSUE THREAD

**Issue by ddllaagg** [dnschneid/crouton#2934] opened 2016-12-07 06:46 UTC
When trying to enter a fresh precise install in xfce4 I get a black screen, here is the output in crosh when I attempt ```sudo startxfce4```

```
 Entering
 
  /mnt/stateful_partition/crouton/chroots/precise...
 /usr/bin/startxfce4: Starting X server
 
 _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
 
 X.Org X Server 1.15.1
 Release Date: 2014-04-13
 X Protocol Version 11, Revision 0
 Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
 Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Dec 1 21:56:24 PST 2016 x86_64
 Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=53f1dd78-d512-d54e-ab32-e6551aaac164/PARTNROFF=1 hashtree=PARTUUID=53f1dd78-d512-d54e-ab32-e6551aaac164/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=d11335a2b65d5fa5456e63a1e27d147fbf1da7ab salt=40337c851571888b038a5c0d6272ca30c848358b20f78d3bf4e5035ae5691e16" noinitrd vt.global_cursor_default=0 kern_guid=53f1dd78-d512-d54e-ab32-e6551aaac164 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
 Build Date: 12 February 2015  03:37:52PM
 xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
 Current version of pixman: 0.30.2
         Before reporting problems, check http://wiki.x.org
         to make sure that you have the latest version.
 Markers: (--) probed, (**) from config file, (==) default setting,
         (++) from command line, (!!) notice, (II) informational,
         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
 (++) Log file: "/tmp/Xorg.crouton.2.log", Time: Wed Dec  7 17:04:53 2016
 (==) Using system config directory "/usr/share/X11/xorg.conf.d"
 setversion 1.4 failed: Permission denied
 Initializing built-in extension Generic Event Extension
 Initializing built-in extension SHAPE
 Initializing built-in extension MIT-SHM
 Initializing built-in extension XInputExtension
 Initializing built-in extension XTEST
 Initializing built-in extension BIG-REQUESTS
 Initializing built-in extension SYNC
 Initializing built-in extension XKEYBOARD
 Initializing built-in extension XC-MISC
 Initializing built-in extension SECURITY
 Initializing built-in extension XINERAMA
 Initializing built-in extension XFIXES
 Initializing built-in extension RENDER
 Initializing built-in extension RANDR
 Initializing built-in extension COMPOSITE
 Initializing built-in extension DAMAGE
 Initializing built-in extension MIT-SCREEN-SAVER
 Initializing built-in extension DOUBLE-BUFFER
 Initializing built-in extension RECORD
 Initializing built-in extension DPMS
 Initializing built-in extension X-Resource
 Initializing built-in extension XVideo
 Initializing built-in extension XVideo-MotionCompensation
 Initializing built-in extension XFree86-VidModeExtension
 Initializing built-in extension XFree86-DGA
 Initializing built-in extension XFree86-DRI
 Initializing built-in extension DRI2
 Loading extension GLX
 xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
 setversion 1.4 failed: Permission denied
 crouton: version 1-20161129162558~master:5f2f11f9
 release: precise
 architecture: amd64
 xmethod: xorg
 targets: xfce
 host: version 9000.15.0 (Official Build) dev-channel swanky 
 kernel: Linux localhost 3.10.18 #1 SMP Thu Dec 1 21:56:24 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
 freon: yes
 Another instance of croutontriggerd running, waiting...
 /etc/xdg/xfce4/xinitrc: 1: /etc/xdg/xfce4/xinitrc: ssh-agent: not found
 _IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
 
 (xfwm4:2577): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
 
 (xfsettingsd:2582): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
 
 (xfce4-session:2571): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
 xfdesktop[2584]: starting up
 
 (xfwm4:2577): GLib-CRITICAL **: g_str_has_prefix: assertion `prefix != NULL' failed
 
 (xfdesktop:2584): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
 
 (polkit-gnome-authentication-agent-1:2598): GLib-CRITICAL **: g_variant_new_string: assertion `string != NULL' failed
 
 (polkit-gnome-authentication-agent-1:2598): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
 
 (migrate:2610): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
 
 (xfce4-settings-helper:2611): xfce4-settings-helper-WARNING **: Failed to get the _NET_NUMBER_OF_DESKTOPS property.

``` 

Any advice anyone can offer?

**Comment by aleifuu** [comment] 2016-12-07 14:05
Hi everyone and ddllaagg, 

Same experience here. I got a black screen with with standard xfce install on my Acer Chromebook CB5-571. I have since tried to create some more chroots with different enviroments. 

tried -r jessie -t gnome ... it says something's wrong with one button to press. logout button
tried -t xbmc ... just blank screen
tried -t xfce ... something with unable to connect do d-bus 

The only one working is -t unity -r trusty. But I am deleting it, since it occupies almost 4GB of space alone. As of now I'm trying to install xfce and trusty. See If it can works

**Comment by DennisLfromGA** [comment] 2016-12-07 17:40
@aleifuu,

> tried -r jessie -t gnome ... it says something's wrong with one button showing ie one button to logout

I haven't used 'jessie' in ages so I can't help there, sorry.

> tried -t xbmc ... just blank screen. I forgot what was it complaining for

Take a look at/track this issue here: [Black screen #2923](https://github.com/dnschneid/crouton/issues/2923
)
> tried -t xfce ... something with unable to connect do d-bus. some dialog window pop-up with similar error message

Take a look at/track this issue here: [chroots will no longer boot to gui after updating chrome OS to version 56.0.2924.9 dev (64-bit) #2917](https://github.com/dnschneid/crouton/issues/2917)

-----
An alternative is to use the 'xiwi' xmethod.

*Hope this helps,*
-**DennisL**

**Comment by aleifuu** [comment] 2016-12-08 02:08
Hi @DennisLfromGA, thanks for the reply. Sure I will look at those threads you mentioned

As for now. Well, I can confirm ` -t xfce -r trusty` is working and occupies around 900MB instead of unity/trusty that can go up to 4GB ( and slow ! ). So I'm good for now

On the other hand I'd just like to have separate xbmc chroots up and running and still having black screen. Will do some tweaking and see how it goes

**Comment by Roaders** [comment] 2016-12-23 13:05
I am very new to all this only having got my Pixel yesterday but I was a bit disappointing when I was just greeted with a black screen after following the default instructions.

Having found this issue I have managed to get it working with trusty and unity but trusty and xfce still fails.

**Comment by DennisLfromGA** [comment] 2016-12-23 17:49
@Roaders,

Have you tried using the 'xiwi' target?

*Hope this helps,*
-**DennisL**

**Comment by Roaders** [comment] 2016-12-24 09:13
Yes, it does work with xiwi thanks Dennis. Thanks for the help, I much prefer xfce to unity :-)

**Comment by dnschneid** [comment] 2017-03-16 01:25
Black screen has been fixed with drinkcat's workarounds.

**Closed by dnschneid** 2017-03-16 01:25 UTC

**Comment by sgt7fathom** [comment] 2017-04-08 18:23
My daughter is using the ASUS Chromebook for Minecraft. When trying to startxfce4 recently, the screen went immediately blank. I am new to this and could use some help I tried to follow work arounds, no luck. Here is the script when typing sudo edit-chroot -all

name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9202.60.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 4.4.35-06796-g0d8baba #1 SMP PREEMPT Tue Mar 28 23:35:35 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Any help would be appreciated...

**Comment by DennisLfromGA** [comment] 2017-04-10 20:44
@sgt7fathom,

This issue is closed but see this issue and comment for a probable cause: https://github.com/dnschneid/crouton/issues/3184#issuecomment-293057721

*Hope this helps,*
-**DennisL**
