### ISSUE TITLE
Keyboard and mouse stop working during crouton "install".

### ISSUE THREAD

**Issue by JoshMcCullough** [dnschneid/crouton#2133] opened 2015-09-23 14:59 UTC
I've been trying to re-create my chroot (trusty) on my Pixel (2), but every time it gets to the step where I enter a username for the primary user, my keyboard and/or mouse stop working! So I can't get past this step.I have to force-shutdown and start over. I tried with just the minimal install:

    sudo sh crouton -r trusty -t core,cli-extra

And I still can't input a username. In the latest case, the mouse works but the keyboard does not. Any suggestions?! At this point it seems like there's no way for me to get trusty installed again!

**Machine Info**
- Google Pixel 2 (i5)
- Just powerwashed, on Beta channel.

**Comment by jessietn** [comment] 2015-09-23 15:23
I had the same problem.  Once you get to the spot asking for the username, shutdown your computer and reboot it.  Then, when back at the shell, enter
`sudo enter-chroot -n trusty`
assuming your chroot is named trusty.  It will detect it did not complete and ask if you want to continue.  Answer yes and it will scroll a bit then ask for your name again.  It will finish now.

This is not a good solution, but it does work.

**Comment by JoshMcCullough** [comment] 2015-09-23 15:24
Awesome, trying that now -- thanks!

**Comment by JoshMcCullough** [comment] 2015-09-23 15:25
Success. Not sure why it happened originally, seems like a bug, so I'll leave this open.

**Comment by jessietn** [comment] 2015-09-23 15:29
Glad to hear.  I had just assumed it was mine acting up.

**Comment by tista500** [comment] 2015-09-24 04:40
This issue seems an exact duplicate of this bug: #1994 
So I hope you guys let this close and post your issues to original one... 

Regards.

**Comment by dnschneid** [comment] 2015-09-24 07:49
Thanks for flagging :)

**Closed by dnschneid** 2015-09-24 07:49 UTC
Labels: duplicate

**Comment by JoshMcCullough** [comment] 2015-09-24 12:48
Thanks, couldn't find that one.
