### ISSUE TITLE
xenial just installed. I only get a black screen.

### ISSUE THREAD

**Issue by jvschiavo** [dnschneid/crouton#3011] opened 2017-01-09 17:18 UTC
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20161129162558~master:5f2f11f9
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,xfce,keyboard
host: version 9150.0.0 (Official Build) dev-channel winky 
kernel: Linux localhost 3.10.18 #1 SMP Wed Jan 4 03:13:25 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
I only get a black screen when trying to enter xfce4.

#### If known, describe the steps to reproduce the issue:
I've just installed xenial using:
sudo sh ~/Downloads/.crouton -r trusty -t xiwi,xfce,keyboard
sudo sh ~/Downloads/.crouton -n trusty -u -t xorg
sudo enter-chroot
sudo apt-get install software-properties-common ubuntu-restricted-extras ttf-ubuntu-font-family bash-completion language-pack-pt nano vim gedit vlc

Then when launching startxfce4 I get:

chronos@localhost / $ sudo startxfce4
Password: 
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-45-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Wed Jan 4 03:13:25 PST 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=b62e34b7-8805-dc44-a745-0da769ecfe75/PARTNROFF=1 hashtree=PARTUUID=b62e34b7-8805-dc44-a745-0da769ecfe75/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=9560f18079c24b1c1ba5ace61b5d8805c767c5ad salt=ac4d978a1f5e2b1e293fa672d75af125c7c118678323a43f779d1a1ab5de5c0f" noinitrd vt.global_cursor_default=0 kern_guid=b62e34b7-8805-dc44-a745-0da769ecfe75 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 02 November 2016  10:06:10PM
xorg-server 2:1.18.4-0ubuntu0.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Jan  9 14:56:53 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20161129162558~master:5f2f11f9
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,xfce,keyboard
host: version 9150.0.0 (Official Build) dev-channel winky 
kernel: Linux localhost 3.10.18 #1 SMP Wed Jan 4 03:13:25 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
_IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.
xfce4-session: No GPG agent found
xfce4-session: No SSH authentication agent found

(xfce4-session:26917): xfce4-session-WARNING **: xfsm_manager_load_session: Something wrong with /home/joao/.cache/sessions/xfce4-session-localhost:1, Does it exist? Permissions issue?
/usr/bin/xbindkeys_autostart: linha 24: CONF: unbound variable
Cannot open /sys/class/tty/tty0/active: No such file or directory
Error: target STRING not available
(II) AIGLX: Suspending AIGLX clients for VT switch
Error: target STRING not available
^C
Session terminated, terminating shell.../usr/bin/xinit: connection to X server lost

waiting for X server to shut down xscreensaver: 15:02:10: SIGHUP received: restarting...
xscreensaver: 15:02:10: running as joao/joao (1000/1000)

Hangup
Hangup
Running exit commands...

(xfsettingsd:26939): libxfce4ui-WARNING **: ICE I/O Error

(xfsettingsd:26939): libxfce4ui-WARNING **: Disconnected from session manager.
xfwm4: Fatal IO error 2 (Ficheiro ou directoria inexistente) on X server :1.0.
xfsettingsd: Fatal IO error 11 (Recurso indisponível temporariamente) on X server :1.0.
Hangup
xfdesktop: Fatal IO error 11 (Recurso indisponível temporariamente) on X server :1.0.
xscreensaver: 15:02:10: Can't open display: :1.0
xscreensaver: 15:02:10: running as joao/joao (1000/1000)

xscreensaver: 15:02:10: Errors at startup are usually authorization problems.
              But you're not logging in as root (good!) so something
              else must be wrong.  Did you read the manual and the FAQ?

              http://www.jwz.org/xscreensaver/faq.html
              http://www.jwz.org/xscreensaver/man.html

(II) Server terminated successfully (0). Closing log file.

/usr/bin/xinit: unexpected signal 2
 ...terminated.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $

**Comment by DennisLfromGA** [comment] 2017-01-09 17:52
Probably a duplicate of #2923, see this for help: https://github.com/dnschneid/crouton/issues/2923#issuecomment-268418795

*Hope this helps,*
-**DennisL**

**Comment by jvschiavo** [comment] 2017-01-17 04:00
Changing to "uxa" worked, but I ended up installing trusty again and updating it.

Thanks, Dennis. :)

**Comment by drinkcat** [comment] 2017-02-16 03:31
#2923

**Closed by drinkcat** 2017-02-16 03:31 UTC
