### ISSUE TITLE
Keyring file not available Kali Linux 

### ISSUE THREAD

**Issue by Harambeislife** [dnschneid/crouton#2988] opened 2016-12-29 22:53 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all

name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8872.73.0 (Official Build) stable-channel terra 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:05:03 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

whenever I trype the command  "sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce" 

I receive the following message 

Installing kali-rolling-amd64 chroot to /usr/local/chroots/kali-rolling
Downloading latest debootstrap...
Download from Debian gitweb failed. Trying latest release...
2016-12-29 14:50:20 URL:http://mirrors.wikimedia.org/debian/pool/main/d/debootstrap/ [3515] -> "-" [1]
Downloading debootstrap version 1.0.87...
2016-12-29 14:50:21 URL:http://mirrors.ocf.berkeley.edu/debian/pool/main/d/debootstrap/debootstrap_1.0.87.tar.gz [65875/65875] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
I: Retrieving InRelease 
I: Retrieving Packages 
^CE: Interrupt caught ... exiting

**Comment by drrobotnic** [comment] 2016-12-31 19:15
Possible duplicate of [this issue](https://github.com/dnschneid/crouton/issues/1868)

**Comment by DennisLfromGA** [comment] 2016-12-31 22:40
@Harambeislife,

Perhaps you interrupted it too soon???
I just installed kali-rolling and, although I got the same error as you, it did complete without error -

> Patching debootstrap...
Downloading bootstrap files...
**W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg**
I: Retrieving InRelease 
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...

I used the following to install mine: 

`sudo sh ~/Downloads/crouton -r kali-rolling -n kalir -t xorg,xiwi,lxde,cli-extra,keyboard,chrome-beta`

However I did run into the blavkscreen issue and resolved it by employing this fix: https://github.com/dnschneid/crouton/issues/2923#issuecomment-268418795

-----
@drrobotnic,

Nope, I don't think it's a duplicate of issue #1868, it's more like the tl;dr issue #2387 that's been resolved.

*Hope this helps,*
-**DennisL**

**Comment by drrobotnic** [comment] 2016-12-31 22:57
Actually, if you just wait (like I did), you would get past that. Took me a long time to figure that out lol

**Closed** 2017-03-09 19:05 UTC
