### ISSUE TITLE
Crouton enter-chroot broken on Chrome OS 124

### ISSUE THREAD

**Issue by jpolsonaz** [dnschneid/crouton#5063] opened 2024-04-06 05:58 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
The enter-chroot command fails with the following errors in Chrome OS Version 124.0.6367.24

/usr/local/bin/crash_reporter_wrapper: 119: exec: /var/run/crw/crw: Permission denied
chroot: failed to run command 'su': Permission denied
chroot: failed to run command 'su': Permission denied

#### If known, describe the steps to reproduce the issue:

This error is caused by the new symlinks behavior which disables following all symlinks mounted under the /mnt/stateful_partition mount point.  I fixed this error by adding the following lines to enter-chroot which enable symlinks in the crouton chroot partition.

> #!/bin/sh -e
> # Copyright (c) 2016 The crouton Authors. All rights reserved.
> # Use of this source code is governed by a BSD-style license that can be
> # found in the LICENSE file.
> 
> set -e
> 
> mount -o remount,rw /sys/kernel/security
> echo -n /mnt/stateful_partition > /sys/kernel/security/chromiumos/inode_security_policies/allow_symlink

**Comment by nethershaw** [comment] 2024-05-09 01:27
But no one in the world will bother to incorporate what you've found into anything because the original maintainers, in their infinite wisdom, decided to leave everything hanging out in "maintenance mode" (which is nothing of the kind) so that everyone -- and therefore no one -- has the responsibility to do so.

**Comment by dnschneid** [comment] 2024-05-09 01:39
dupe of #5056

@nethershaw not sure if this is your intent, but you're actually being helpful

**Closed by dnschneid** 2024-05-09 01:39 UTC

**Comment by eritain** [comment] 2024-06-01 02:55
> dupe of #5056

Is it? #5056 has remounting `$sec` read+write, but doesn't have `allow_symlink`. I did the remount, but still have the `/usr/local/bin/crash_reporter_wrapper: 119: exec: /var/run/crw/crw: Permission denied` error.
