### ISSUE TITLE
Problems returning to ChromeOS (black screen) from xorg chroot

### ISSUE THREAD

**Issue by chrisofCCL** [dnschneid/crouton#1699] opened 2015-05-01 11:40 UTC
I'm running Trusty/XFCE with the XORG target. I tried xiwi for a few weeks when I had problems switching back to ChromeOS after an upgrade but I got a bit fed up with the poor graphics performance (no gpu acceleration).

Anyway, I'm back with xorg and when I ctrl-alt-shift-F1, I just get a black screen.  If I ctrl-alt-shift-F2 or even ctrl-alt-shift-F1 again, I get back to the chroot ok. If I log out of the chroot, it goes back to the black screen.  So it looks like the switching may be working ok but somehow ChromeOS is completely hidden and remains so even after I leave the chroot.

Any ideas anyone???

**Comment by singularperturbation** [comment] 2015-05-01 16:57
I've run into this issue too (Asus C200, running Trusty w/ XFCE4 as well). 

I found a workaround: If I switch to a real terminal, Control-Alt-F2 (Right arrow), I can log in using the chronos user and kill the running chrome process.  That seems to restore the display, but chrome has to restart, so obviously not ideal.

**Comment by DennisLfromGA** [comment] 2015-05-01 21:07
I saw a quick way to restart Chrome is `sudo restart ui`.

On Fri, May 1, 2015 at 12:57 PM, Sloane Simmons <notifications@github.com>
wrote:

> I've run into this issue too (Asus C200, running Trusty w/ XFCE4 as well).
>
> I found a workaround: If I switch to a real terminal, Control-Alt-F2
> (Right arrow), I can log in using the chronos user and kill the running
> chrome process. That seems to restore the display, but chrome has to
> restart, so obviously not ideal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1699#issuecomment-98177340>.
>



-- 
*DennyL@GMail*

**Comment by dnschneid** [comment] 2015-05-03 21:02
Could you post the output of `croutonversion`?

**Comment by singularperturbation** [comment] 2015-05-05 03:51
singularperturbation@localhost ~> croutonversion
crouton: version 1-20150430123324~master:90ad47ff
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce,extension,keyboard
host: version 6812.83.0 (Official Build) stable-channel squawks 
kernel: Linux localhost 3.10.18 #1 SMP Mon Apr 27 08:42:03 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
singularperturbation@localhost ~>

**Comment by chrisofCCL** [comment] 2015-05-05 11:51
And mine  (original problem in this issue) is:

crouton: version 1-20150430123324~master:90ad47ff
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xfce,xiwi
host: version 6946.31.0 (Official Build) beta-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Wed Apr 29 23:17:46 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

I thought when I'd updated my chroot with xorg that xiwi would disappear from the target list. Is its presence confusing the system?  If so how do I remove it?  And should I be using the extension target?

**Comment by DennisLfromGA** [comment] 2015-05-05 16:36
@chrisofCCL - 
When you updated your chroot to add 'xorg', it didn't replace or remove 'xiwi', it just made 'xorg' the new default xmethod. Doing this won't confuse the system at all and it has the added benefit of allowing you to choose which xmethod you to use when you invoke your start* script(s).
To use 'xorg', just run it in the normal way - `sudo startxfce4 -n trusty`
To use 'xiwi', run it with the -X option - `sudo startxfce4 -n trusty -X xiwi`

Also, the extension target is a requirement of 'xiwi' so you already have it; only the targets you specify with '-t ...' will be shown in croutonversion 'targets:' (`/etc/crouton/targets`), others, like 'extension' will still be there but won't be displayed. When using 'xiwi', you'll also need to add the '[Crouton Integraton](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension if you haven't already done so.

**Comment by tsbarnes** [comment] 2015-05-07 15:28
I'm having the same issue on an Acer C720P.

```
crouton: version 1-20150503215233~master:75fb08cb
release: vivid
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,extension,xfce,x11,audio,cli-extra,keyboard,touch,gtk-extra
host: version 6946.31.0 (Official Build) beta-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Apr 29 21:58:12 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

**Comment by singularperturbation** [comment] 2015-05-10 20:21
Found another workaround for this:
Switch to a real terminal first (Ctrl-Alt-F2), then switch back to chroot / chrome OS using control-alt-shift-F2 / F1.  Somehow if you switch from a real terminal rather than directly from X / Chrome OS, it doesn't crash.

YMMV, obviously.

**Comment by idpnd** [comment] 2015-05-11 17:43
Same here on acer CB5-571/utopic. I also had this on my previous toshiba cb5..

**Comment by chrisofCCL** [comment] 2015-05-19 10:06
Thanks Sloane,

but what exactly do you mean by a "real terminal"?  Ctrl-Alt-F2 has no
effect on my system (a Trusty/XFCE chroot).

Chris

Chris Morris BSc C.Eng MIET
*Chardstock Consulting Ltd*
Bristol

email: chris.chardstockconsulting@gmail.com
mobile: +44 (0) 7976 123257



*Please consider the environment before printing a hard copy of this
e-mail. Chardstock Consulting Ltd. A company registered in England and
Wales.*
*Registered Number 8935506*

**Comment by divx118** [comment] 2015-05-19 16:34
@chrisofCCL @singularperturbation Has a different problem then yours. He is experiencing #1475. Since you are already on freon this isn't your problem. Also that (being on freon) is why you don't have a ´real´ terminal anymore. See #1557

**Comment by singularperturbation** [comment] 2015-05-20 01:53
@chrisofCCL - I think divx118 is correct (we're experiencing different issues), but all I mean by 'real' terminal is not a shell in a terminal emulator (either in the chroot or crosh as a chrome tab).

According to (https://plus.google.com/+FrancoisBeaufort/posts/L3zmATV8BW5), you still should have a (virtual) terminal iff in developer mode with freon, but I've held off on upgrading, so I'm not sure if that would work for you or not.

**Comment by divx118** [comment] 2015-05-20 16:13
@singularperturbation That is true, but when starting a chroot, crouton will kill the dev console, because of a crossbug. See #1557. If you didn't start a chroot yet on a reboot it will be there on devices with freon.  Switching to the dev console will not work for @chrisofCCL.

**Comment by Snowflake6** [comment] 2015-06-05 13:56
Just to add to this issue, i'm seeing it too on an Acer C720P/4GB RAM/128GB SSD.  My croutonversion (updated this morning in hopes of a resolution, but no dice...):

chronos@localhost / $ sudo enter-chroot -n utopic croutonversion
Entering /mnt/stateful_partition/crouton/chroots/utopic...
crouton: version 1-20150604154515~master:91b3e350
release: utopic
architecture: amd64
xmethod: xorg
targets: cli-extra,audio,chrome,core,keyboard,touch,unity
host: version 6812.88.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Fri May 8 12:21:21 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/utopic...
chronos@localhost / $

**Comment by chrisofCCL** [comment] 2015-06-05 14:53
ok, I was the originator of this thread so back to me!  I have implemented a couple of workarounds, mainly a simple script that asks if I want to run in a window (-X xiwi) or full screen. If full screen, the last line after startxfce4 is "sudo restart ui" (an earlier suggestion in this thread) so that when I log out of Crouton, at least I can immediately log back into ChromeOS. But none of this is ideal and I really want my ctrl-shift-alt-F1/2 switching back. 

One of the earlier posts suggested waiting for the next ChromeOS update. I have now had two and there is no change. My ChromeOS version details are as follows.

Version 44.0.2403.25 beta (64-bit)
Platform 7077.21.0 (Official Build) beta-channel quawks
Firmware Google_Quawks.5216.204.6

My Croutonversion output is:
crouton: version 1-20150519153807~master:30cf02c9
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xfce,xiwi
host: version 7077.21.0 (Official Build) beta-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Fri May 29 11:01:52 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

Is this still a freon incompatibility somewhere?  Is there yet a solution or does it remain "wait a bit longer"??

**Comment by Snowflake6** [comment] 2015-06-05 16:06
@chrisofCCL, two questions:

1. does the Shutdown from within your Crouton work?  ie. it shuts down the laptop completely, and you can power up again and log in?

2. Does "sudo restart ui" log you out of ChromeOS so you have to log in again?  But otherwise works normally?

I'm using Shutdown now to force a hard stop when i'm done with my Crouton, and then powering up again and logging back in.  If restarting the UI would save me a reboot I might try to get that working.

I miss being able to copy and paste between Chrome and Crouton though.

**Comment by supasebie** [comment] 2015-06-05 19:50
I've been able to reproduce this problem while messing around with xorg trying to get Hearthstone to run on trusty via WINE. (HearthStone runs fine now, haha) This makes returning to ChromeOS from Linux result in a black screen;

sudo add-apt-repository ppa:xorg-edgers/ppa
sudo apt-get update
sudo apt-get dist-upgrade

**Comment by supasebie** [comment] 2015-06-05 21:06
I have the same issue after the following;

sudo add-apt-repository ppa:xorg-edgers/ppa
sudo apt-get update
sudo apt-get dist-upgrade

apt get install wine

follow through complete wine install

switch from trusty xfce -X xorg to ChromeOS - I get a black screen.

I've reproduced this multiple times on different chroots. Encountered this process while getting Hearthstone up and working through wine.

**Comment by chrisofCCL** [comment] 2015-06-06 08:12
Snowflake, yes to both. But putting the restart ui in the script means that 
I can log out from crouton and log back into chromeos without restarting 
completely. Bit quicker.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by idpnd** [comment] 2015-06-08 09:00
Same issue again, utopic on toshiba cb 2

**Comment by chrisofCCL** [comment] 2015-06-08 15:19
Supasebie, I am also using WINE (via PlayOnLinux), to run MS Office apps.  Could this be the root cause,  I wonder? Does WINE leave background processes running, which might cause this prob?

**Comment by supasebie** [comment] 2015-06-13 06:46
Chris,

I wish I knew any better. I'm still pretty new to linux, and running linux through crouton on chrome is an even greater mystery. I'll leave it up to the pros, but it seems like we can reproduce an issue. I did the best I can so far, and I'm trying to learn more.

**Comment by pickettd** [comment] 2015-06-14 02:48
I have this issue now with Trusty Kubuntu on a late 2013 HP 14. I had been using wine before and things worked fine. This issue started for me immediately after I started using the xorg-edgers graphics drivers, ie:
```
sudo add-apt-repository ppa:xorg-edgers/ppa
sudo apt-get update
sudo apt-get dist-upgrade
```
I installed the edgers drivers because the Battle.net launcher was just showing me a black screen in wine with both the default and ubuntu-x-swat graphics drivers (and the software rendering flag wasn't working for me).

I can get ChromeOS to come back up if I type `sudo restart ui` from the chroot.

Here's my output of croutonversion:
```
crouton: version 1-20150604154515~master:91b3e350
release: trusty
architecture: amd64
xmethod: xorg
targets: chrome,xbmc,audio,keyboard,extension,kde-desktop,cli-extra
host: version 6946.55.0 (Official Build) stable-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Tue May 26 18:05:07 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

**Comment by pickettd** [comment] 2015-06-25 00:04
Ah, also - I was able to get switching between ChromeOS and the chroot working again using the ppa-purge utility (note that this uninstalls the new video drivers). The following commands first installs the ppa-purge tool, removes the xorg-edgers ppa, and downgrades the packages back to what was there before:
```
sudo apt-get install ppa-purge
sudo ppa-purge xorg-edgers
```

**Comment by tonymurray** [comment] 2015-07-30 16:05
I still have the same problem - black screen, Acer C720P
Some specs:
targets: xiwi,kde,touch,audio,core,cli-extra,extension,x11,keyboard,unity,xorg
host: version 7077.95.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Jul 14 21:49:35 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

Two points:
1. When I try to remove xorg-edgers-ppa....

sudo ppa-purge xorg-edgers
results in:....
Updating packages lists
PPA to be removed: xorg-edgers ppa
Warning:  Could not find package list for PPA: xorg-edgers ppa
(So I guess xorg-edgers is not the issue for me)

2. Workaround: Rather than sudo restart ui

There is a keyboard shortcut: Ctrl + Shift + Q (twice)
Ref: https://support.google.com/chromebook/answer/183101?hl=en&source=genius-rts
(which works in the Chrome OS blank screen after logging out of crouton.)

3. As far as I can tell the [Chrome OS] Crouton integration extension does not connect to the crouton instance. Msg "Disconected (retrying every 5 seconds)

Any further solutions or things to try would be most welcome

**Comment by voidplayer** [comment] 2015-08-02 14:30
I have this exact problem
model: thinkpad yoga 11e chromebook

latest crouton version, release stretch and targets gnome xfce4 (gnome crashes so i had to install xfce as well

**Comment by chrisofCCL** [comment] 2015-08-03 12:41
I've only just caught up with this and I have the same issue as @tonymurray - I haven't got xorg-edgers installed in the first place.

Quite a few people have this problem so I'm surprised there isn't a standard solution!  Any more ideas abyone??

**Comment by mkasick** [comment] 2015-08-07 22:17
I think I might've sorted this out in #2003.  The only discrepancy is that the xserver-xorg-video-intel package that ships with trusty does not have the change the causes the problem, but utopic does.  Installing an LTS backport or PPA version probably would though.

**Comment by chrisofCCL** [comment] 2015-08-08 20:23
It looks like that may well be my problem. 

However, mkasick, you are obviously far more expert than me!  I'm just a humble user.  It seems you are providing modified source code for freon.c and the xorg target. But are there any modified files out there that the existing ones can simply be replaced by? Or at least a script to do the recompilation?

**Comment by mkasick** [comment] 2015-08-08 21:22
If you clone the repo and run make, it will generate a crouton script that you can use to update the chroot with the modifications, something like:
```
sudo enter-chroot
cd /tmp
git clone -b freon 'https://github.com/mkasick/crouton.git'
cd crouton
make
exit
sudo sh -e /tmp/crouton/crouton -u
```
Please backup the chroot first though if it's particularly important.

**Comment by tista500** [comment] 2015-08-09 02:25
@mkasick Thanks for your patch, and it seems to work on my Vivid:
```
crouton: version 1-20150809103328~freon:bbb94b86
release: vivid
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,gnome,keyboard
host: version 7330.0.0 (Official Build) dev-channel squawks 
kernel: Linux localhost 3.10.18 #1 SMP Tue Aug 4 03:52:22 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
Hope your patch could fix other people as well... :)

Regards.

**Comment by MonkeyWrench32** [comment] 2015-08-09 05:56
@mkasick The patch worked for me as well. I'm using Debian stretch with XFCE and keyboard targets on the beta Chrome OS channel.

**Comment by chrisofCCL** [comment] 2015-08-10 12:28
Mike,

Worked for me too - perfect! Thanks very much.

One question though - when I update my chroot in future, will I have to repeat this process too?.

**Comment by mkasick** [comment] 2015-08-11 03:47
Until #2003 is accepted into master, yes.  You may want to save /tmp/crouton/crouton someplace useful, i.e., "cp /tmp/crouton/crouton ~/Downloads", and use that version of the script for chroot updates for the near future.

**Comment by chrisofCCL** [comment] 2015-08-11 06:18
OK, thanks Mike - very helpful.

Chris

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by dnschneid** [comment] 2015-08-11 18:50
#2003 has been merged!  Please try the latest crouton and re-open if things aren't fixed.

**Closed by dnschneid** 2015-08-11 18:50 UTC

**Comment by c200chromebook** [comment] 2015-10-02 05:51
I recently upgraded from jessie to stretch and am getting the problem:
crouton: version 1-20150924014025~master:04ff0c11
release: stretch
architecture: amd64
xmethod: xorg
targets: keyboard,xfce
host: version 7262.57.0 (Official Build) stable-channel squawks 
kernel: Linux localhost 3.10.18 #1 SMP Thu Sep 17 23:07:25 PDT 2015 x86_64 GNU/Linux
freon: yes

**Comment by tastyminerals** [comment] 2016-04-13 15:22
Confirming, Toshiba Chromebook 2. Got a black screen after `sudo starte17` and hitting "Next"  during e17 desktop configuration.
Also, black screen with **openbox** after `sudo enter-chroot -n trusty` and `exec openbox-session`.

Can somebody at least tell what causes this?

**Comment by chepurko** [comment] 2016-04-29 16:53
Here is my `croutonversion`:

`crouton: version 1-20160420122426~master:46f3c372
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,keyboard,cli-extra,core,extension,touch,xfce-desktop,xorg
host: version 7834.70.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP Sat Apr 9 16:02:43 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes`

I'm using the xorg xmethod and constantly getting a black screen switching back to Chrome OS. Sometimes I just have to switch around to different windows or to a terminal and keep switching back and forth. Really less than ideal.

**Comment by Improbus** [comment] 2016-05-22 12:25
I can also confirm I am running into the issue consistently on my Toshiba Chromebook 2 on both my Trusty and Kali-Rolling Chroots.  See the following information:

`Version 50.0.2661.103 (64-bit)
Platform 7978.74.0 (Official Build) stable-channel swanky
Firmware Google_Swanky.5216.238.5`

The results from croutonversion:

Trusty:
`croutonversion 
crouton: version 1-20160518095657~master:fd37bb79
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,xfce
host: version 7978.74.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Thu May 12 00:50:50 PDT 2016 x86_64 x86_64 x86_64
GNU/Linux
freon: yes`

Kali-Rolling:
`croutonversion 
crouton: version 1-20160518095657~master:fd37bb79
release: kali-rolling
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,xorg,extension
host: version 7978.74.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Thu May 12 00:50:50 PDT 2016 x86_64 GNU/Linux
freon: yes`

**Comment by tomulet** [comment] 2017-02-03 00:15
Black screen when switching between Linux and Chrome OS: Make sure Chrome OS is in Stable channel.
