### ISSUE TITLE
Issues running Debian Bullseye with GNOME

### ISSUE THREAD

**Issue by vastraz** [dnschneid/crouton#4577] opened 2021-08-19 06:35 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all
```

`name: bullseye`
`encrypted: no`
`Entering /mnt/stateful_partition/crouton/chroots/bullseye...`
`crouton: version 1-20210817115015~master:d607c558`
`release: bullseye`
`architecture: amd64`
`xmethod: xorg`
`targets: gnome`
`host: version 13982.69.0 (Official Build) stable-channel snappy`
`kernel: Linux localhost 4.4.254-20533-gcb85bd3a0149 #1 SMP PREEMPT Thu Jul 29 21:56:25 PDT 2021 x86_64 GNU/Linux`
`freon: yes`
`

#### Please describe your issue:

I first attempted to install Debian Bullseye with the KDE environment but that didn't get past the bootstrapping phase. I then installed using GNOME, this worked, however it will not boot up. Whenever I enter Linux using the "sudo startgnome" command it gives me an error saying "Oh no! Something has gone wrong. Contact a system's administrator" after booting up. In the console, I have the following error:

`
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
`

 Edit: FYI the issue with KDE was as a result of the error "failed to locate package kde-runtime."

#### If known, describe the steps to reproduce the issue:

Installing Debian Bullseye on an HP Chromebook running Apollo Lake/SNAPPY with the GNOME environment then booting with the "sudo startgnome" command.

**Comment by sanrobin** [comment] 2021-08-19 15:20
possible duplicate of #4368

**Closed** 2021-08-19 20:03 UTC
