### ISSUE TITLE
Tooltip for Collapsible Animated Indented Tree

### ISSUE THREAD

**Issue by nb25** [dnschneid/crouton#2556] opened 2016-04-29 22:49 UTC
Hi,
I have been working with the Collapsible Animated Indented Tree: http://bl.ocks.org/tchaymore/1249394 by tchaymore’s Block 1249394.

However, I am fairly new to D3 and cannot make the tooltip to work. I need each of the nodes to say something different. The necessary files can be found here: https://gist.github.com/mbostock/1093025 as it draws the data from an external file source (the json file).

It would be absolutely great if you could help me out with this as it is kind of urgent. 

Thank you in advance!!

**Comment by smibarber** [comment] 2016-04-30 00:28
HTTP/1.1 301 Moved Permanently
Location: https://stackoverflow.com

Dupe of #262

**Closed by smibarber** 2016-04-30 00:28 UTC
