### ISSUE TITLE
Kali fails to compile CRAS i386 during installation.

### ISSUE THREAD

**Issue by GioPanaro** [dnschneid/crouton#4126] opened 2019-08-29 20:32 UTC
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20190807171712~master:6f45f06a
release: kali-rolling
architecture: amd64
targets: gnome-desktop,xorg
host: version 12457.0.0 (Official Build) canary-channel eve 
kernel: Linux localhost 4.4.189-16757-gc8cc94218b14 #1 SMP PREEMPT Mon Aug 26 13:49:46 PDT 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### Please describe your issue:
Kali fails to install. There is an error installing CRAS. Eventual output is below.

```
Compiling CRAS (i386)...
libcras/cras_client.c: In function 'handle_message_from_server':
libcras/cras_client.c:1713:12: error: converting a packed 'struct cras_client_message' pointer (alignment 1) to a 'struct cras_client_get_hotword_models_ready' pointer (alignment 4) may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1713 |    (struct cras_client_get_hotword_models_ready *)msg;
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
../src/common/cras_messages.h:90:36: note: defined here
   90 | struct __attribute__((__packed__)) cras_client_message {
      |                                    ^~~~~~~~~~~~~~~~~~~
../src/common/cras_messages.h:588:8: note: defined here
  588 | struct cras_client_get_hotword_models_ready {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

```
#### If known, describe the steps to reproduce the issue:
sudo crouton -r kali-rolling -t gnome-desktop,xorg

**Comment by Asternitix** [comment] 2019-08-30 03:14
this same problem happens for Debian Bullseye.

sudo crouton -r bullseye -t xfce,core,extension -p (USB drive)

**Comment by drinkcat** [comment] 2019-09-03 01:27
Dupe of #4119.

**Closed by drinkcat** 2019-09-03 01:27 UTC
