### ISSUE TITLE
Trackpad Problem (xenial)

### ISSUE THREAD

**Issue by jmccoy** [dnschneid/crouton#4550] opened 2021-07-20 14:34 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all
name: hirsute
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/hirsute...
crouton: version 1-20210709170820~master:14ca6bc7
release: hirsute
architecture: amd64
xmethod: xorg
targets: xfce
host: version 13904.77.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 4.19.185-29738-gf8e4fd700b66 #1 SMP PREEMPT Sun Jun 27 22:50:44 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/hirsute...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20210709170820~master:14ca6bc7
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,extension,xiwi,touch
host: version 13904.77.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 4.19.185-29738-gf8e4fd700b66 #1 SMP PREEMPT Sun Jun 27 22:50:44 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
chronos@localhost / $ 
```

#### Please describe your issue:

I have an Acer Chromebook R11 (CB5-132T, C738T) and I use a xenial chroot which I generated with Crouton. SInce my last update of chromeos [91.0.4472.147 (Official Build) (64-bit)], two-finger scrolling no longer works. Also, in Settings --> Mouse and Trackpad, the "Devices" screen is grayed out (not the others).

I have updated Crouton and updated the Synaptics package, to no avail. I also installed a hirsute chroot and found that two-finger scrolling does work there (although "Touch to Tap" doesn't).

Any suggestions? Thanks!

**Comment by MrHallway0** [comment] 2021-07-20 16:39
Possible duplicate of #4436.

**Comment by DennisLfromGA** [comment] 2021-07-20 16:44
- No Scroll in XFCE after update to ChromeOS 89 · 
Issue #4436 · dnschneid/crouton

Closing. Please track the above issue for further details.

-**DennisLfromGA**

**Closed by DennisLfromGA** 2021-07-20 16:44 UTC

**Comment by jmccoy** [comment] 2021-07-20 21:31
Thank you very much. Sorry I missed it!
