### ISSUE TITLE
Cant start up kali linux

### ISSUE THREAD

**Issue by vbouderau03** [dnschneid/crouton#3115] opened 2017-02-27 23:46 UTC
```

name: kali-rollingencrypted: noEntering /mnt/stateful_partition/crouton/chroots/kali-rolling...crouton: version 1-20170223114115~master:71d1c2f5release: kali-rollingarchitecture: amd64xmethod: xorgtargets: xfcehost: version 9000.91.0 (Official Build) stable-channel peppy kernel: Linux localhost 3.8.11 #1 SMP Wed Feb 22 23:39:40 PST 2017 x86_64 GNU/Linuxfreon: yesUnmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...chronos@localhost / $ name: kali-rolling
```

#### Please describe your issue:I installed kali linux and it worked perfect but when i installed the full version and left the chroot i couldn't get in it gave me this message:Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.1
Release Date: 2017-01-11
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Feb 22 23:39:40 PST 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=68f3be2f-dfcc-654c-b34d-c08c3f69ec07/PARTNROFF=1 hashtree=PARTUUID=68f3be2f-dfcc-654c-b34d-c08c3f69ec07/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=bf2e59501b63961c9d66539930bfe0a17ffe4cf6 salt=42bc575dbffd99fe1ffad956135ce3258ede51e01cee991288f49916f78d8393" noinitrd vt.global_cursor_default=0 kern_guid=68f3be2f-dfcc-654c-b34d-c08c3f69ec07 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 20 January 2017  02:50:48AM
xorg-server 2:1.19.1-4 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Feb 27 18:45:13 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE)

**Comment by divx118** [comment] 2017-02-28 20:38
duplicate of #2912

**Closed** 2017-03-15 16:42 UTC
