### ISSUE TITLE
Linux not installing saying something like CRAS

### ISSUE THREAD

**Issue by imdigitalashish** [dnschneid/crouton#4450] opened 2021-03-28 16:36 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
targets: xfce
host: version 13870.0.0 (Official Build) dev-channel cyan 
kernel: Linux localhost 4.19.182-11462-gd4095e080da4 #1 SMP PREEMPT Tue Mar 23 16:07:05 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
Reading state information... Done
patch is already the newest version (2.7.5-1ubuntu0.16.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling CRAS (i386)...
In file included from libcras/cras_client.c:47:0:
libcras/cras_client.h:1439:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1454:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1475:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1491:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1506:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1530:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1550:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1570:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1592:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1608:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1623:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1638:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1653:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1668:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1683:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1732:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1753:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1767:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1784:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1799:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1815:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1831:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1847:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1878:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1893:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1908:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1924:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1940:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1955:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1970:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1985:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:2000:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
cc1: error: unrecognized command line option '-Wno-int-in-bool-context' [-Werror]
cc1: all warnings being treated as errors
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### If known, describe the steps to reproduce the issue:
sudo crouton -t xfce

**Comment by Deacyde** [comment] 2021-04-04 22:17
I get this wonderfulness: 
Compiling CRAS (i386)...
libcras/cras_client.c: In function 'libcras_node_info_create':
libcras/cras_client.c:4211:2: error: 'strncpy' output may be truncated copying 31 bytes from a string of length 31 [-Werror=stringop-truncation]
 4211 |  strncpy(node->node_->type, ionode->type,
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4212 |   CRAS_NODE_TYPE_BUFFER_SIZE - 1);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libcras/cras_client.c:4213:2: error: 'strncpy' output may be truncated copying 63 bytes from a string of length 63 [-Werror=stringop-truncation]
 4213 |  strncpy(node->node_->node_name, ionode->name,
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4214 |   CRAS_NODE_NAME_BUFFER_SIZE - 1);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libcras/cras_client.c:4215:2: error: 'strncpy' output may be truncated copying 63 bytes from a string of length 63 [-Werror=stringop-truncation]
 4215 |  strncpy(node->node_->dev_name, iodev->name,
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4216 |   CRAS_IODEV_NAME_BUFFER_SIZE - 1);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition

**Comment by drinkcat** [comment] 2021-04-25 01:02
For those:
```
libcras/cras_client.h:1439:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
```

Introduced by https://crrev.com/c/2764116 landed in 13857.0.0.
Fixed by https://crrev.com/c/2820819 landed in 13912.0.0.

We should do a hotfix in cras target file between these releases.

**Comment by DennisLfromGA** [comment] 2021-04-25 19:13
@imdigitalashish,

It looks like you were using: 
> host: version **13870.0.0** (Official Build) dev-channel cyan

The Cyan dev channel is now at:
- 92.0.4484.0 / **13929.0.0**

So the fix that @drinkcat mentioned above may have already rolled out to.
You could try to update your chroot with:
- `sudo crouton -n xenial -u`   

And see if it finishes successfully.
If not, please let us know.

*Hope this helps,*
-**DennisLfromGA**

**Comment by esprout** [comment] 2021-05-08 22:41
I can confirm that patching cras_client.h line 1388, replacing:

```
#define DISABLE_CFI_ICALL __attribute__((no_sanitize("cfi-icall")))
```

with:

```
#if defined(__clang__)
#define DISABLE_CFI_ICALL __attribute__((no_sanitize("cfi-icall")))
#else
#define DISABLE_CFI_ICALL
#endif
```

enables the compile to go through.

So it'd be good to provide a patch in prepare.sh until 13912 goes through.

**Comment by esprout** [comment] 2021-05-08 23:04
In prepare.sh, adding after

```
sed -i -e 's/^struct \([^_]\)/struct __attribute__((__packed__)) \1/' \
                common/cras_messages.h
```
start at line 1163:

```
sed -i -e 's/#define DISABLE_CFI_ICALL __attribute__((no_sanitize("cfi-icall")))/#define DISABLE_CFI_ICALL/' \
                libcras/cras_client.h
```

does the trick.

Perhaps lines for "# FIXME(http://crrev.com/c/1759370): Remove when R78 becomes minimum target" are obsolete and can be removed now as well?

**Comment by leonbollerup** [comment] 2021-05-19 13:52
Is this a change we can make ourself or does it require an update "somewhere" ? Sorry if it sounds like a n0bb question

**Comment by PinapplePizzaaa** [comment] 2021-06-13 18:15
so has anyone fixed this issue, and explain as if I were a 5 year old cuz im just tryin to run 1 linux program here.

**Comment by DennisLfromGA** [comment] 2021-06-13 19:51
@PinapplePizzaaa,

See -  
- Update audio to fix #4506 by haberda · Pull Request #4507 · dnschneid/crouton
https://github.com/dnschneid/crouton/pull/4507

**Comment by GiddyLinux** [comment] 2021-06-19 11:38
> I can confirm that patching cras_client.h line 1338, replacing:
> 
> ```
> #define DISABLE_CFI_ICALL __attribute__((no_sanitize("cfi-icall")))
> ```
> 
> with:
> 
> ```
> #if defined(__clang__)
> #define DISABLE_CFI_ICALL __attribute__((no_sanitize("cfi-icall")))
> #else
> #define DISABLE_CFI_ICALL
> #endif
> ```
> 
> enables the compile to go through.
> 
> So it'd be good to provide a patch in prepare.sh until 13912 goes through.

could you tell me how to access prepare.sh

**Comment by rymry** [comment] 2021-06-28 05:50
@GiddyLinux  
> could you tell me how to access prepare.sh

If you use the command `sudo crouton -x /usr/local/crouton-files` you can find prepare.sh at `/usr/local/crouton-files/installer/prepare.sh`.

You may have to change permissions on the directory to access the file. You can do this by using the command `sudo chmod -R 775 /usr/local/crouton-files/installer`. And that should do the trick :)

**Comment by rymry** [comment] 2021-06-28 06:28
Though as far as I can tell the file only has 338 lines... and I can't find any instance of cras_client.h either so this hasn't been a fix for me. Maybe it will help someone else though.

**Comment by andyross** [comment] 2021-06-29 15:29
This seems to be festering.  AFAICT no fix nor workaround has been committed?  And I can't figure out the workaround procedure.  The prepare.sh file exists in the chroot directory, but it's being clobbered every time I run the top-level crouton script.  How do I make it persistent?  Or alternatively how do I run crouton from source?

Can someone **please** either commit a workaround to the tree to unbreak users or at least write a complete, from-scratch, for-regular-users explanation of exactly what needs to be modified to work around the bug?

**Comment by cathenauwu** [comment] 2021-06-29 17:26
@andyross I'll try to explain how I fixed it and why it worked the best and simplest I can. What I had to find out from seperate research is that CRAS is the audio server used my Chromium OS. It stands for ChRomium os Audio Server. From knowing that we can figure that the audio trigger is what's causing the problem. As @DennisLfromGA said but didn't explain, the proper fix can be found in issue #4506 and is fixed in PR #4507:

1. Install Crouton
2. Extract Crouton to `/usr/local` with the bash command `sudo crouton -x /usr/local/crouton-file` (the folder in /usr/local can be called whatever you want).
3. Navigate to `/usr/local/crouton-files/targets` and edit the file called `audio`. Go to line 119 and add this line: `sed -i 's/-Werror//g' Makefile.am`. The initial problem is because of the occurrence of `-Werror` in the Makefile for CRAS. `-Werror` makes the installation process treat any warnings as errors therefore stopping the installation, but by adding this line, we can bypass that.
4. Rather than run the installation with the crouton command like normal, we have to use a file in the `/usr/local/crouton-files/installer` directory. To install, just make sure you're in the `/usr/local/crouton-files` directory, and run the command `sudo ./installer/main.sh` with any extra flags or options you need (EX. `sudo ./installer/main.sh -t audio,extension,keyboard -r bionic`). This command works just like doing `sudo crouton` except it has our fix so it should run through and install the Linux distro you want!

Using this fix, you should be able to use audio just fine and instead of pulling errors that stop you're installation, there will just be warnings that you can ignore for the time being. If you have any questions about what I said I might be able to help...

**If someone could _please_ commit fix #4507 to fix this bug in total, or better yet, fix the warnings themselves, that would be very useful.**

**Comment by frodggy** [comment] 2021-07-04 05:09
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: amd64
targets: xiwi
host: version 13904.77.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.228-37743-g49d2c603c1a5 #1 SMP PREEMPT Sun Jun 27 23:18:33 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
targets: xfce
host: version 13904.77.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.228-37743-g49d2c603c1a5 #1 SMP PREEMPT Sun Jun 27 23:18:33 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by BlnKgl** [comment] 2021-07-05 11:12
The solution of **esprout** on 09 May worked well for me, even in focal, except when I wanted to do update an ENCRYPTED chroot ; (presumably the same problem would arise with a new installation, but the steps below should work equally well.)

So here are the steps that worked for me:
install the text app in Chrome, for later use;
then try
-       sudo crouton -u -n xenial
(which fails at some point with the error messages about CRAS;)
so in the ChromeOS shell:
-      sudo mount-chroot xenial
-      cd /home/user/<a long number>/Downloads
-      sudo cp /var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/prepare.sh . 
-      sudo chmod a+wr prepare.sh
use the Chrome text app to edit prepare.sh in the Downloads directory, as described by **esprout** above, and save; then
-       sudo cp prepare.sh /var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial
which overwrites the old version but keeps the right permissions, (I think;)
-       sudo startxfce4 -b
or whatever command you use to enter the chroot (- do not start the update, or the installation, again;) and when asked
-      Would you like to finish the setup?
answer "y" - and everything should just work.

**Comment by ansh315** [comment] 2021-07-07 10:49
Hi @cathenauwu,
I am getting stuck in step 3. Unable to enter /usr/local/crouton-files/targets. Says permission denied. Please help. If it helps, I am using an arm64 based chromebook (Acer Spin 311) with the MT8173 soc. 
Thanks in advance. 
Sorry for the noob question.

**Comment by BlnKgl** [comment] 2021-07-08 22:45
Hello. There are different ways of addressing that problem, mine was
actually different from the one that you seem to be using, which is I
guess to edit the file for the audio target.

But usually when the message is Permission denied, one needs to be
root, temporarily, so if you to
     sudo cd /usr/local/crouton-files/targets
and enter your password you should be able to enter that folder.

(When I tried that method, that folder seemed empty, but the other
method, of editing the file prepare.sh after the installation has
stopped, has worked for me, on two chromebooks.)

Best wishes with the installation.

**Comment by dnschneid** [comment] 2021-07-10 00:15
Please try the latest release of crouton and re-open if it doesn't fix the failure.

**Closed by dnschneid** 2021-07-10 00:15 UTC

**Comment by Snowflake6** [comment] 2021-07-16 04:53
Confirmed, this resolved my issue and I was able to install and enter a chroot with no CRAS errors.

Although, my first test was with -t unity, and on entering I was given a nice desktop with no window manager... I will exit and try updating with -t unity-desktop.

**Comment by MrHallway0** [comment] 2021-07-16 15:48
> Please try the latest release of crouton and re-open if it doesn't fix the failure.

When did this "*latest release*" come out, I am trying to fix my own errors?

**Comment by DennisLfromGA** [comment] 2021-07-16 18:05
@MrHallway0,

Most of the patches were 'committed' on July 7th & July 9th, 2021, you can look at them using the link below:
- https://github.com/dnschneid/crouton/commits/master

*Hope this helps,*
-**DennisLfromGA**

**Comment by DudeWhoCantDownloadKaliLinux** [comment] 2022-01-10 03:34
> 

Hey, how do I navigate to the audio files after I enter (sudo crouton -x /usr/local/crouton-file)???
