### ISSUE TITLE
Are /etc/pm/sleep.d scripts supposed to work with Crouton?

### ISSUE THREAD

**Issue by laurenweinstein1** [dnschneid/crouton#2530] opened 2016-04-12 15:03 UTC
A few days ago in another issue, I noted that I'm finding the network interfaces I add in my Trusty chroot (via /etc/rc.local) immediately vanish after the system wakes from suspend. I've tried to work around this by setting up a script to run automatically from sleep.d to reestablish them. But this also appears to fail. Are these wake/resume functions in /etc/pm/sleep.d supposed to work with Crouton? I'm trying to find a solution to this other than using cron. Thanks.

**Comment by phedders** [comment] 2016-06-06 07:16
This is a duplicate of #2526. Please dont flood a bug system like this.

**Closed** 2017-03-15 23:42 UTC
