### ISSUE TITLE
Rendering problems after upgrade to ChromeOS 53 same has happened on 50

### ISSUE THREAD

**Issue by mangas** [dnschneid/crouton#2634] opened 2016-06-18 16:58 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
Same as https://github.com/dnschneid/crouton/issues/2491

After upgrade I can't use the extension unless I am running the native resolution otherwise it seems only 1/4 of the extension window works properly.

I am aware this has happened after an upgrade twice and that is probably not related/cause by the extension but maybe there is something that can be done to make the extension more resilient? 

@dnschneid if you have some suggestion I am happy to help and chase it out but I need some guidance if you have some time. 

#### If known, describe the steps to reproduce the issue:
1. Use some resolution other than the native
2. Open the extension
3. Open some app inside the extension window
4. Move the app window around 
5. Notice rendering doesn't work properly except on the upper left 'quarter' of the extension screen

**Comment by westphae** [comment] 2016-06-21 00:52
I had what sounds like a similar problem after upgrade to Chrome OS Version 52.0.2743.41 beta (64-bit).  xiwi would initially display my chroot but would respond very slowly.  I turned on debugging in the xiwi extension menu to see if there were any indication of the problem and suddenly it was responsive again.  For some reason, debugging (perhaps because it is constantly updating the screen in the debug window?) makes it responsive, but as soon as I turn off debugging it is no longer responsive again.  Debugging output didn't tell me anything helpful.  Updating the chroot doesn't help.

Chroot is Ubuntu with xfce4 running on a Chromebook Pixel (2013) under Chrome OS 52.

name: threepio
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/threepio...
crouton: version 1-20160620130246~master:c39102d9
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce,xorg,keyboard,extension,cli-extra,touch
host: version 8350.31.0 (Official Build) beta-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Tue Jun 14 21:47:39 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

Fairly

**Comment by westphae** [comment] 2016-06-21 01:15
Update: Yes, seems like I have the same problem.  I thought it was the entire chroot that is unresponsive for a few seconds after interaction just because I was using a terminal on the right-hand side of the screen, but in fact the upper-left 1/4 of the display updates right away; only the other 3/4 of the screen takes some time to update.  So it seems like some xiwi problem with updating the whole screen.  The high-dpi screen also seems to be a part of the problem, as suggested by @mangas.

**Comment by mangas** [comment] 2016-06-21 07:48
Can you please check if it's slow or if it actually only updates after mouse clicks? For me is the latter. I did some investigation around December but I couldn't figure out why it was happening. I realised in the meantime that it only happens if the screen is scaled otherwise it seems to work fine.

I will try to take go at it but some help from someone more familiar with the codebase could actually help a lot.

**Comment by westphae** [comment] 2016-06-21 20:00
The latter: the bottom/right 3/4 of the screen only updates after mouse clicks.  It is not slow (it just appeared that way initially).

I found that having xiwi extension debugging activated (from the Crouton extension menu), which creates a black debugging information bar across the top of the window, forces the screen to update, perhaps because there are constant updates in that bar across the entire window.  It's completely usable in this way, though I lose a few lines of text (I'm also mainly using crouton for Intellij ;) ).

**Comment by jesobremonte** [comment] 2016-06-24 11:40
Same issue here. Using Google Pixel 2015 on dev build.
Version 53.0.2773.0 dev (64-bit)
Platform 8481.0.0 (Official Build) dev-channel samus
Firmware Google_Samus.6300.174.0

I tried to record my screen to show this bug using a chrome extension called "Screencastify".

Strangely I found that while recording my screen output, the xiwi window will always update fully as it normally should(so I cannot record the bug). When I switch off Screencastify recording, the issue comes back where only the top-left quarter of the xiwi window refeshes normally, with the rest of the window only updating upon interaction. Hopefully this might help with narrowing down the cause.

**Comment by phedders** [comment] 2016-06-29 19:51
Those with the problem can you try right click the title bar and click on "Reload". That for me makes the window fully responsive until I resize it.

Full screen xiwi windows of course wont work because I cant get to the Reload option.

I think this is a duplicate of #2609 though the diagnosis and details above I think are very helpful.

**Comment by mangas** [comment] 2016-06-29 21:55
@phedders for me if I reload a couple of times it eventually stays broken. If you need to use it either enable debug or disable screen scaling. That way it works

**Comment by phedders** [comment] 2016-07-05 16:49
Such a shame isnt it :|

**Comment by ecgreb** [comment] 2016-08-09 20:09
Same problem here. Just started happening today. I have a Pixel 2015 on the stable channel.

Right click on the title bar > "Reload" seems to resolve the issue until I resize the window again. Happy to share any additional info needed.

Also using xiwi primarily for IntelliJ/Android Studio ;)

 ```
Version 52.0.2743.116 (64-bit)
Platform 8350.68.0 (Official Build) stable-channel samus
Firmware Google_Samus.6300.174.0
```

**Comment by 1na** [comment] 2016-08-19 15:22
Same problem here,  after the start of an application the screen is is fine, but when I leave the tab and come back only 1/4 of the screen rebuilds the rest does after reload or if debugging is enabled. 
I can try and help figure out a solution, but I don't know where to start. 

Details for the setup at my end are as follow. 
The chromebook is HP Chromebook 13.

sudo edit-chroot -all gives:
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160715134041~master:0dc76a22
release: trusty
architecture: amd64
xmethod: xiwi
targets: core,xiwi,keyboard,x11,cli-extra,extension,xfce
host: version 8350.68.0 (Official Build) stable-channel chell 
kernel: Linux localhost 3.18.0-12320-gbb6b499 #1 SMP PREEMPT Tue Aug 2 21:11:16 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

Ubuntu is: 
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

ChromeOS:
Version 52.0.2743.116 (64-bit)
Platform 8350.68.0 (Official Build) stable-channel chell
Firmware Google_Chell.7820.98.0

**Comment by 1na** [comment] 2016-08-19 15:36
I just found there is chromium bug that seems related. : [reported here](https://bugs.chromium.org/p/chromium/issues/detail?id=633806)

**Comment by msolters** [comment] 2016-09-04 07:43
I have this problem too.  But, when I connect my Chromebook to an external monitor with 4K resolution (USB-C), the problem disappears.  It's almost as if the 1/4 xiwi refresh bug were monitor-dependent.

**Comment by phedders** [comment] 2016-09-08 08:30
See [https://bugs.chromium.org/p/chromium/issues/detail?id=633806](url).
I think this ticket can be closed now.

**Comment by mangas** [comment] 2016-09-08 08:34
Awesome, this had happened around December last year, happy someone managed to fix it. When will it be available? any idea ? 

Thanks

**Comment by msolters** [comment] 2016-09-08 14:18
Hey @phedders , pardon my ignorance but what does that bug fix mean for us here in Crouton & ChromeOS land?  I take it that it is some form of upstream change, but what I don't understand is when it will be deployed, or if there is a way to manually implement it...?

BTW your URL seems broken, the display text is correct (can copy/paste into address bar) but the actual hyperlink destination is incorrect.

**Comment by mangas** [comment] 2016-09-08 14:26
@msolters As far as I understand the rendering problem is from a graphics library/component which affects one of the example applications the same way it affects the crounton extension window. As to the release, they mention M53 which I assume is the current version 53 from beta or similar.

**Comment by 1na** [comment] 2016-09-09 14:12
I switched to the Beta channel today and the issue resolved. So I agree with @phedders , I think the ticket can be closed.

**Closed** 2016-09-09 14:12 UTC
