### ISSUE TITLE
Debootstrap; Permission Denied

### ISSUE THREAD

**Issue by avaiv** [dnschneid/crouton#4803] opened 2022-09-08 22:16 UTC
```
chronos@localhost / $ sudo crouton -t xfce
```
Every time I type the command I get this:

WARNING: Your rootfs is writable. Signed boot verification cannot be enabled.
If this is a surprise to you, you should do a full system recovery via USB.
Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading bootstrap files...
/tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.3x9/installer/ubuntu/bootstrap: /tmp/crouton.UZp/debootstrap: Permission denied
debootstrap error log:
tail: cannot open '/tmp/crouton.UZp/xenial-amd64/debootstrap/debootstrap.log' for reading: No such file or directory
Failed to run debootstrap.

**Comment by Kitty035** [comment] 2022-09-10 21:21
Have the same issue.  Appears Crouton is out of date

**Comment by BobUnderwoodSF** [comment] 2022-09-11 21:57
Try

`sudo crouton -r focal -t xfce`

**Comment by iptoux** [comment] 2022-09-13 21:01
> ```
> chronos@localhost / $ sudo crouton -t xfce
> ```
> 
> Every time I type the command I get this:
> 
> WARNING: Your rootfs is writable. Signed boot verification cannot be enabled. If this is a surprise to you, you should do a full system recovery via USB. Installing xenial-amd64 chroot to /usr/local/chroots/xenial Downloading bootstrap files... /tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.3x9/installer/ubuntu/bootstrap: /tmp/crouton.UZp/debootstrap: Permission denied debootstrap error log: tail: cannot open '/tmp/crouton.UZp/xenial-amd64/debootstrap/debootstrap.log' for reading: No such file or directory Failed to run debootstrap.
> 
> #### If known, describe the steps to reproduce the issue:

Hey, i can't reproduce this error:

```
chronos@localhost / $ sudo /usr/local/bin/crouton -t xfce
WARNING: USB booting is enabled; consider disabling it.
WARNING: Signed boot verification is disabled; consider enabling it.
You can use the following command: sudo crossystem dev_boot_usb=0 dev_boot_signed_only=1
Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease 
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Checking component main on http://archive.ubuntu.com/ubuntu...
I: Retrieving adduser 3.113+nmu3ubuntu4
I: Validating adduser 3.113+nmu3ubuntu4
I: Retrieving apt 1.2.10ubuntu1
```
---
Please try an `sudo mount -i -o remount,exec /tmp/`, after this try crouton install again.

**Comment by notgoodatlinux** [comment] 2022-09-16 00:04
having the same problem i think chrome updated something that stopped this from working. im currently trying to get crouton for the first time and im stuck at this step

**Comment by iptoux** [comment] 2022-09-16 06:15
> having the same problem i think chrome updated something that stopped this from working. im currently trying to get crouton for the first time and im stuck at this step
> 

Have you tried my instructions? Then, i still can't reproduce the error.

**Comment by notgoodatlinux** [comment] 2022-09-16 12:16
> > having the same problem i think chrome updated something that stopped this from working. im currently trying to get crouton for the first time and im stuck at this step
> 
> Have you tried my instructions? Then, i still can't reproduce the error.

I have but its still the same error
![image](https://user-images.githubusercontent.com/113646558/190636868-1edd57db-6f48-4845-8ae6-f53b8599768e.png)

**Comment by avaiv** [comment] 2022-09-17 22:01
its still getting the same error even after i tried powerwashing and after i tried all of your suggestions. maybe try looking into how to getting by the permission denied bit?

**Comment by iptoux** [comment] 2022-09-21 07:23
The problem is, that i can't reproduce the error, also there is no logic behind this error, because of following things:

- You run script as sudo
- on line 95 in `installer/crouton` is nothing (empty line)
- on line 95 in `direct crouton binary` is nothing, only an check of verbose options.

The permission error comes from your system and not crouton, so the problem is not on crouton side here. Can you please give us the output of `sudo ls -la /tmp/` (in second tab, also after typing shell) shortly after starting install.

**Comment by iptoux** [comment] 2022-09-21 07:50
Okay, i have done some forensics... and found where the error comes. Need future inspecting to understand the code lines and see if i could found the issue.

Line 95 from `installer/ubuntu/bootstrap` 

```
# Grab the release and drop it into the subdirectory
    echo 'Downloading bootstrap files...' 1>&2
    if ! PATH="$newpath" DEBOOTSTRAP_DIR="$tmp" $FAKEROOT \
            "$tmp/debootstrap" --foreign --extractor='ar' --arch="$ARCH" \
            "$RELEASE" "$tmp/$subdir" "$MIRROR" 1>&2; then
        echo "debootstrap error log:" 1>&2
        tail -n 3 "$tmp/$subdir/debootstrap/debootstrap.log" 1>&2 || true
        error 1 'Failed to run debootstrap.'
    fi
```
Maybe @TomTravis or @DennisLfromGA can help here.

**Comment by Kitty035** [comment] 2022-10-13 00:52
A month later and after trying all suggestions posted here, I still cannot get crouton to work.  Still getting the Failed to run debootstrap error.

Downloading bootstrap files...
/tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.cyv/installer/ubuntu/bootstrap: /tmp/crouton.K2R/debootstrap: Permission denied
debootstrap error log:
tail: cannot open '/tmp/crouton.K2R/xenial-amd64/debootstrap/debootstrap.log' for reading: No such file or directory
Failed to run debootstrap.

I am running all commands as sudo.  I would really like to get out of having to use Crostini for linux and get back to using Crouton for Linux.  Are there anymore suggestions that I can follow or an eta of when this issue will be fixed??

**Comment by dinoswong** [comment] 2022-10-16 04:08
I found the issue is caused by ChromeOS upgrade. It may be started from v107. There is some security  and permission change. The script on /tmp cannot be executed anymore even remount /tmp to allow executable. But I don't know how to fix it.

![Screenshot 2022-10-16 11 02 31](https://user-images.githubusercontent.com/24631050/196017486-8b807e76-1f14-4dcf-a2b7-1424592e23a2.png)

**Comment by foss-dragon** [comment] 2022-10-17 16:40
anyone found fix?

**Comment by iptoux** [comment] 2022-10-17 18:21
> anyone found fix?

Do you read last line of @dinoswong reply?

**Comment by myelin** [comment] 2022-10-18 07:05
The problem is that tmpfs mounts in ChromeOS are now noexec, so you can't drop a script in /tmp and execute it (which breaks the bootstrap script), and /usr/local/ is mounted nodev, so the installer script needed changes.

My latest code at https://github.com/myelin/crouton is working for me right now; can you give it a try?  I spent some time on it today and it can create sid, focal, jammy, and kinetic chroots on my brya machine running a personal 108.0.5355.0 build.

Note that startxfce4 currently fails on sid, jammy, and kinetic, but works on focal, so you probably want to use focal rather than any of the newer distributions.

**Comment by foss-dragon** [comment] 2022-10-18 19:05
> The problem is that tmpfs mounts in ChromeOS are now noexec, so you can't drop a script in /tmp and execute it (which breaks the bootstrap script), and /usr/local/ is mounted nodev, so the installer script needed changes.
> 
> My latest code at https://github.com/myelin/crouton is working for me right now; can you give it a try?  I spent some time on it today and it can create sid, focal, jammy, and kinetic chroots on my brya machine running a personal 108.0.5355.0 build.
> 
> Note that startxfce4 currently fails on sid, jammy, and kinetic, but works on focal, so you probably want to use focal rather than any of the newer distributions.

perfect! i try it tomorrow

**Comment by SepticRedhead** [comment] 2022-10-21 15:56
> The problem is that tmpfs mounts in ChromeOS are now noexec, so you can't drop a script in /tmp and execute it (which breaks the bootstrap script), and /usr/local/ is mounted nodev, so the installer script needed changes.
> 
> My latest code at https://github.com/myelin/crouton is working for me right now; can you give it a try? I spent some time on it today and it can create sid, focal, jammy, and kinetic chroots on my brya machine running a personal 108.0.5355.0 build.
> 
> Note that startxfce4 currently fails on sid, jammy, and kinetic, but works on focal, so you probably want to use focal rather than any of the newer distributions.

i keep getting this when entering my chroot 
Entering /mnt/stateful_partition/crouton/chroots/focal...
/usr/local/bin/crash_reporter_wrapper: 119: exec: /var/run/crw/crw: Permission denied
WARNING: Unable to register core dump handler.
dbus[5292]: Unknown username "whoopsie" in message bus configuration file

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.20.13
X Protocol Version 11, Revision 0
Build Operating System: linux Ubuntu
Current Operating System: Linux localhost 5.10.147-20137-gfa8e6d1d4794 #1 SMP PREEMPT Sun Oct 16 23:14:38 PDT 2022 aarch64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 5324800 verity payload=PARTUUID=9dfac76e-a780-4c56-9716-bbbd838df974/PARTNROFF=1 hashtree=PARTUUID=9dfac76e-a780-4c56-9716-bbbd838df974/PARTNROFF=1 hashstart=5324800 alg=sha256 root_hexdigest=a43d60da85bd4fac5e2fb4b3ad514e11624e3d817e6028c427f3481d584c4d17 salt=03f0628d51731be6789698004606f2432bd1c5fce172c5bda24f6be93504eec6" noinitrd vt.global_cursor_default=0 kern_guid=9dfac76e-a780-4c56-9716-bbbd838df974 cpuidle.governor=teo  
Build Date: 06 July 2022  01:53:24PM
xorg-server 2:1.20.13-1ubuntu1~20.04.3 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.38.4
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Oct 21 11:48:40 2022
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1666367320.665477 sender=:1.308 -> destination=:1.819 serial=15633 reply_serial=2
   boolean true
(II) modeset(0): Initializing kms color map for depth 24, 8 bpc.
(EE) event8  - Google Inc. Hammer: libinput bug: Internal or external? Please file a bug.
(EE) event8  - Google Inc. Hammer: libinput bug: Internal or external? Please file a bug.
crouton: version 1-20221017235132~main:0f39a42b
release: focal
architecture: arm64
xmethod: xorg
targets: gnome
host: version 15183.8.0 (Official Build) dev-channel kukui 
kernel: Linux localhost 5.10.147-20137-gfa8e6d1d4794 #1 SMP PREEMPT Sun Oct 16 23:14:38 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Running exit commands...
/usr/bin/xinit: connection to X server lost
Hangup

waiting for X server to shut down Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1666367329.520237 sender=:1.308 -> destination=:1.821 serial=15645 reply_serial=2
   boolean true
(II) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/focal...
and it doesnt boot it just shuts down

**Comment by TomTravis** [comment] 2022-10-22 16:55
yes chromeOS updates have changed permissions and privs for files system 
/var
/tmp
/media
/
sudo  mount -o remount,symfollow,exec /var* /tmp* /media* /*
all need exec mounts

Shell  now asked for password on sudo in shell
the UID and PID are not tracked to well in Crouton chroot is it own FS and processes. ChromeOS tracks UID and PID better now
My share "MyFiles" Download will no longer mount the icon on Desktop is gone the folder is present today for some reason 
i now using bullseye and bookworm

I now use a X86 M900 lenovo for FS bookworm and work general the chroots  CB has issue but still works x2go work just fine over the next 
TB is storage and fast processor
Mate and KDE desktops

it seems the X86 CB is supported different then arm CB this is reason for the m900 X86_64 intel

I really like the arm64 mediatek it run with less power and it performs very good

**Comment by avaiv** [comment] 2022-10-22 21:19
Your code worked! Thank you so much!

**Comment by RAMBoykott** [comment] 2022-10-29 10:57
@TomTravis 

chronos@localhost / $ sudo mount -o remount,symfollow,exec /var* /tmp* /media* /*
mount: bad usage
Try 'mount --help' for more information.


How to fix that???

**Comment by adamant-pwn** [comment] 2022-11-25 02:32
Please re-open this. I still get the error and nothing in the thread seems to fix it...

**Comment by peer-pri** [comment] 2022-11-25 05:51
Yes it isnt working for me too. I did not fixed it

**Comment by peer-pri** [comment] 2022-11-25 05:54
It isnt working for me too. I didnt fixed it

**Comment by avaiv** [comment] 2022-11-28 12:51
#4878 this helped me a lot

**Comment by dnschneid** [comment] 2022-11-28 19:33
The original issue is fixed in the latest crouton, so please try it again.

**Closed by dnschneid** 2022-11-28 19:33 UTC

**Comment by peer-pri** [comment] 2022-11-29 11:52
Okay I will try it again todqy
