### ISSUE TITLE
ACER Chromebook - Crouton fails to complete installation if a single package fails

### ISSUE THREAD

**Issue by thatonetechdude** [dnschneid/crouton#4179] opened 2019-12-02 22:09 UTC
I am trying to install linux kali (kali-roling) to my cromebook acer CB3-111 I have downloaded

https://github.com/dnschneid/crouton
https://goo.gl/fd3zc

when installing with the code "sudo sh crouton -r kali-rolling -t xfce,extension,xiwi" for the first time all wne well exept untill what I think was the end of the instalation process when it gave the text

Package xbindkeys is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'xbindkeys' has no installation candidate
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

now then I try installing again it just says

/usr/local/chroots/kali-rolling already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.

I have deleted it and I dont know how to successfully install linux kali, Any help would be nice.

![Screenshot 2019-12-02 at 4 06 05 PM](https://user-images.githubusercontent.com/58344782/69999214-bac61500-151d-11ea-83ae-50f82a20f08a.png)

**Comment by monster1612** [comment] 2019-12-03 06:21
I see you left a comment in the "tutorials are broken" issue saying you were new, which is understandable; that being said, please don't create another issue with your exact same problem simply because no one responded to it the first time. no one's obligated to help you, and duplicate issues only clutter and complicate things. as such, I will address your original issue (#4171).

**Comment by DennisLfromGA** [comment] 2019-12-03 17:27
@thatonetechdude,

See if this helps:

[https://github.com/dnschneid/crouton/issues/4153#issuecomment-560190450](https://github.com/dnschneid/crouton/issues/4153#issuecomment-560190450)

**Comment by JL2210** [comment] 2019-12-04 18:39
@DennisLfromGA Can this be closed? It is a duplicate of https://github.com/dnschneid/crouton/issues/4171.

**Comment by DennisLfromGA** [comment] 2019-12-05 18:28
@JL2210,

Yes, definitely, I missed that earlier one.

Closing, duped to https://github.com/dnschneid/crouton/issues/4171.

-**DennisLfromGA**

**Closed by DennisLfromGA** 2019-12-05 18:28 UTC

**Comment by thatonetechdude** [comment] 2019-12-06 01:42
Thank you so much for the help! Sorry for the duplicate.
