### ISSUE TITLE
Can't install debian bullseye

### ISSUE THREAD

**Issue by mcbarge** [dnschneid/crouton#4619] opened 2021-10-17 12:49 UTC
```
name: bullseye
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bullseye...
crouton: version 1-20210907212903~master:9b281df5
release: bullseye
architecture: amd64
xmethod: xorg
targets: xfce,core,audio,x11,xorg,cli-extra,kde
host: version 14150.57.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.243-18084-g7bc10658733d #1 SMP PREEMPT Mon Oct 11 23:13:10 PDT 2021 x86_64 GNU/Linux
freon: yes
```
When trying to install debian bullseye it just says unable to find package kde-runtime. I tried installing it with xfce and kde and neither worked

#### If known, describe the steps to reproduce the issue:
sudo crouton -r bullseye -t kde/sudo crouton -r bullseye -t xfce

**Comment by BetaPictoris** [comment] 2021-10-17 21:17
Duplicate of #4453.

**Closed** 2021-10-18 17:08 UTC
