### ISSUE TITLE
Switch back to chroot X not working

### ISSUE THREAD

**Issue by JohnAllanSmith** [dnschneid/crouton#1782] opened 2015-05-23 02:30 UTC
Hello Everyone! I have a problem when I want to switch from my Chromebook env back to chrooted-X. From X to chromebook works, I press SHIFT+CRTL+ALT+BACK_BUTTON  however, when I want to switch from Chromebook to Chroot, it fails, the cursor disappear but my X window doesn't come back.

Any ideas on how can get the switching back to my Linux environment working? Thanks!

Here are some details if that helps:

Model: Chromebook 2, Toshiba B3340.

crouton: version 1-20150511154233~master:392b84e4
release: jessie
architecture: amd64
xmethod: xorg
targets: xorg
host: version 6812.88.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Fri May 8 16:05:18 PDT 2015 x86_64 GNU/Linux
freon: no

My xinitrc:
#!/bin/bash
while true
do
LOCALTIME=$(date "+%F %R")
        xsetroot -name "$LOCALTIME"
 sleep 5s
done &

exec dwm

Here's what I see in the Chome shell tab while switching:

jessie)bubba@localhost:~$ startx

X.Org X Server 1.16.4
Release Date: 2014-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.10.18 #1 SMP Fri May 8 16:05:18 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=6bce7050-de8b-6642-b851-4d41ac5fb933/PARTNROFF=1 hashtree=PARTUUID=6bce7050-de8b-6642-b851-4d41ac5fb933/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=ec357573bb971b0f3c39cb8ea2f88e7f42981e93 salt=8dea690a5a70c5dc069222d934ac74e17a8d0585c2bfc011e408deaf06dbde14" noinitrd vt.global_cursor_default=0 kern_guid=6bce7050-de8b-6642-b851-4d41ac5fb933 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 11 February 2015  12:32:02AM
xorg-server 2:1.16.4-1 (http://www.debian.org/support) 
Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Sat May 23 10:16:55 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xf86: found device 0
crouton: version 1-20150511154233~master:392b84e4
release: jessie
architecture: amd64
xmethod: xorg
targets: xorg
host: version 6812.88.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Fri May 8 16:05:18 PDT 2015 x86_64 GNU/Linux
freon: no
(II) AIGLX: Suspending AIGLX clients for VT switch

**Comment by divx118** [comment] 2015-05-23 06:38
You are probably experiencing #1475 . Once your device is fully transitioned to freon this problem will be gone.
If it is indeed the same issue then please close this one. Thanks.

**Comment by JohnAllanSmith** [comment] 2015-05-23 07:45
Hi divx118. thanks for getting back to me. It is still an open issue. I've commented in #1475 . Not sure if there's any solution. The strange thing is that this worked a while back and I'm not sure what may have brake this. I haven't upgraded crouton.

**Comment by divx118** [comment] 2015-05-23 08:42
chromeos is updated. They are moving away from the X-server in chromeos and introducing freon. They do it step by step, once the transition is fully done and you are on freon it should be solved. The issue is indeed open and probably will be a won't fix for the above reason. Until then pressing ctr-C in the crosh terminal window to close your chroot is the best way to log out of your chroot.

**Closed** 2015-05-29 06:50 UTC
