### ISSUE TITLE
application connection result status code 2002

### ISSUE THREAD

**Issue by rameshmca2013** [dnschneid/crouton#1359] opened 2015-01-21 07:37 UTC
Hi,in my sample chrome cast application , if i debug the sender application the application connection result status code 2002 and  showing the error message as brain freeze(we are sorry ,but some thing could not load)activity aborted.help this issue occur in sender side ? or  connectivity issue  ? or receiver side?

**Comment by dnschneid** [comment] 2015-01-21 08:42
Dupe of #1316 and #262.

[This RFC](https://tools.ietf.org/html/rfc3588) might or might not help.

**Closed by dnschneid** 2015-01-21 08:42 UTC
