### ISSUE TITLE
Audio issues using Ubuntu Trusty 14.04 with KDE

### ISSUE THREAD

**Issue by vomc** [dnschneid/crouton#2281] opened 2015-12-07 16:38 UTC
Hi,

I was excited at the prospect of [this article about a DAW on a chromebook] (https://github.com/dnschneid/crouton/wiki/Full-Blown-Audio-Video-Workstation-using-KDE-chroot-and-KXStudio) but after following the example point by point, I am still having issues where KDE will start complaining about the drivers on my Chromebook - [ASUS C300] (http://www.asus.com/us/Notebooks/ASUS_Chromebook_C300/specifications/). I saw a few forum posts that suggested changing the order of the audio drivers in the KDE settings, prefering the 'defaults' so I did that but still no sound...

Any suggestions? I wonder if this is the best place to ask or if I should jump on the ubuntu trusty forums... 

Thanks!
- V

**Comment by CoolOppo** [comment] 2015-12-10 13:40
Possible duplicate of #2015

**Comment by drinkcat** [comment] 2016-10-11 19:23
Please re-open if this is still an issue.

**Closed by drinkcat** 2016-10-11 19:23 UTC
