### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by kirankumar8500** [dnschneid/crouton#1600] opened 2015-04-10 08:30 UTC
Hey friends ,
I want to populate the drop down menu on selecting another drop down menu. I try Ajax but I couldn't do it. What I want to do is there two drop down menus, Standard and section. On selecting Standard I should get all the sections of that standard in my Assignment drop down menu.
Please help...!

**Comment by MAkerboom** [comment] 2015-04-10 09:37
Dupe of https://github.com/dnschneid/crouton/issues/262

**Closed** 2015-04-10 09:40 UTC
