### ISSUE TITLE
Can't encrypt chroot?

### ISSUE THREAD

**Issue by kgoode517** [dnschneid/crouton#1842] opened 2015-06-09 00:15 UTC
I can't seem to be able to encrypt my kde chroot I have added the -e parameter as instructed in the readme to no avail and I can't seem to see any solutions or anyone having the same issue. I can update by using sudo sh ~/Downloads/crouton -u I just assumed that I switch the -u with a -e  to encrypt but I recieve no password promt am I doing something wrong?

**Comment by DennisLfromGA** [comment] 2015-06-09 16:37
Use both '-e -u' and it should work.

**Comment by kgoode517** [comment] 2015-06-09 17:06
Dennis,
Thank you for your response! I have tried your above suggestion, unfortunatly the respose I get is "illegal option". Do you have any other suggestions? I have tried everything I can think of.

**Comment by DennisLfromGA** [comment] 2015-06-10 14:00
@kgoode517  - Sorry, I really have no experience with encrypted chroots, I've never tried to install one with it nor add it later, I was just hoping the '-u' update option was the missing component. The [README](https://github.com/dnschneid/crouton#with-encryption) just says "Add the -e parameter when you run crouton to create an encrypted chroot or encrypt a non-encrypted chroot." like you were doing so maybe the '-u' was the wrong suggestion.

I don't think you need to first create a password in Chrome OS via `chromeos-setdevpasswd`, I believe crouton is supposed to invoke it when you apply encryption. Maybe it'd be best just to defer this to the experts. Hopefully someone will spot this and offer some more help.

**Comment by kgoode517** [comment] 2015-06-10 17:24
Dennis,
I agree I was very suprised to not see a solution though the forms I would think that others would be having the same problem. Thank you for your time and trying to help me.

**Comment by dnschneid** [comment] 2015-06-10 21:55
`-e -u` should work.  Could you post the full command you're running?

**Comment by kgoode517** [comment] 2015-06-12 01:59
Solved! I have been using sudo sh ~/Downloads/crouton -e -u but keep getting "illegal option" for whatever reason when I restarted the computer and tried again it worked!

**Comment by kgoode517** [comment] 2015-06-12 02:01
Solved! I have been using sudo sh ~/Downloads/crouton -e -u but keep getting "illegal option" for whatever reason when I restarted the computer and tried again it worked!
--------------------------------------------
On Wed, 6/10/15, David Schneider <notifications@github.com> wrote:

 Subject: Re: [crouton] Can't encrypt chroot? (#1842)
 To: "dnschneid/crouton" <crouton@noreply.github.com>
 Cc: "kgoode517" <Kgoode517@yahoo.com>
 Date: Wednesday, June 10, 2015, 4:55 PM
 
 -e -u should work. 
 Could you post the full command you're running?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by DennisLfromGA** [comment] 2015-06-12 19:34
@kgoode517 - Glad it's working; you can probably close this issue now if you like.

**Closed** 2015-06-13 05:08 UTC

**Comment by kgoode517** [comment] 2015-06-13 05:09
My apologies I though I did. Thank you for bringing it to my attention.

**Comment by SpafinDoople** [comment] 2015-06-13 05:20
The issue is apparently open... :smile:
