### ISSUE TITLE
Can't type "quotation" marks

### ISSUE THREAD

**Issue by piefert** [dnschneid/crouton#1793] opened 2015-05-24 15:10 UTC
On my xfce4 chroot, I am not able to type quotation marks, neither seperately nor as accents characters.

I suspect this has to do with the keyboard layout. In xfce4 I am using the English (US) keyboard layout. I have currently selected a generic 105-key (intl) PC and have tried some Generic ...-key variants which didn't seem to work.

edit:
tapping the " button multiple times does nothing.
" then space then space gives one space.
" then a character then space gives one space.
This is the same for the ` and ~ button

**Comment by divx118** [comment] 2015-05-24 16:43
Try double pressing, that works for me when running chromeos in a window.

**Comment by piefert** [comment] 2015-05-25 10:02
thanks for the quick reply, unfortunately this does not work

**Comment by divx118** [comment] 2015-05-25 10:35
Can you post the output of `sudo enter-chroot croutonversion`

**Comment by piefert** [comment] 2015-05-26 05:09
This is the output:

Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150519153807~master:30cf02c9
release: trusty
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 6812.88.0 (Official Build) stable-channel auron_yuna 
kernel: Linux localhost 3.14.0 #1 SMP Fri May 8 14:08:38 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by dnschneid** [comment] 2015-05-29 07:09
Possibly #1428?

**Comment by drinkcat** [comment] 2015-06-30 08:45
Yeah, dupe of #1428. Using US (no intl) in Chromium OS should fix that...

**Closed by drinkcat** 2015-06-30 08:45 UTC
