### ISSUE TITLE
Need help building kernel headers for HP 13 to install virtualbox

### ISSUE THREAD

**Issue by wildbill12** [dnschneid/crouton#2659] opened 2016-06-30 17:51 UTC
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160627183059~master:e3c0a690
release: trusty
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 8172.60.0 (Official Build) stable-channel chell 
kernel: Linux localhost 3.18.0-11125-g013294a #1 SMP PREEMPT Thu Jun 23 04:33:37 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes```

#### Please describe your issue:

I am the owner of a shiny new HP Chromebook 13 m5 version, and I am so far quite happy.
I am now trying to install virtualbox to run one critical windows only program that I absolutely need.
I previously had an original Pixel so was able to use divx118 prebuilt kernel header packages and virtualbox was a breeze to install.

The HP 13's kernel is 3.18.0 so it looks like I have to build my own.

I followed the guide here using the 3.18 branch: https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)

Doing that produces two .deb files named:
linux-headers-3.18.0-12563-g8e79f0d-dirty_3.18.0-12563-g8e79f0d-dirty-10.00.Custom_amd64.deb

linux-image-3.18.0-12563-g8e79f0d-dirty_3.18.0-12563-g8e79f0d-dirty-10.00.Custom_amd64.deb

Installing these does not quite work  -- my kernel version is 3.18.0-11125-g013294a when I do uname -r, so virtualbox still complains that I don't have the correct headers. I tried just setting dkms --kernelsourcedir to the headers I built and installed but no dice.

So where do I go from here? Did I build kernel headers for the wrong version? How do I do it for my version? Or do I just have to rename/force virtualbox to use the version I built

Thanks for the help!

**Comment by divx118** [comment] 2016-06-30 18:15
Sorry no solution yet. This is a duplicate of #2642 please close this one and continue discussion at #2642. Thanks.

**Closed** 2016-06-30 18:27 UTC
