### ISSUE TITLE
sudo startxfce responds error "UID 1000 not found in xenial" AND libcras/cras_client.h:2000:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]  {  ^

### ISSUE THREAD

**Issue by MacawLinux** [dnschneid/crouton#4528] opened 2021-06-29 18:33 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all give me: name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
targets: xfce
host: version 13904.66.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 4.19.185-29738-gf8e4fd700b66 #1 SMP PREEMPT Wed Jun 16 22:40:18 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue , I tried to install ubuntu on my chromebook and when I do sudo startxfce4 it gives me :UID 1000 not found in xenial
Unmounting /mnt/stateful_partition/crouton/chroots/xenial... and it gives me this long output: libcras/cras_client.h:1893:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1908:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1924:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 {

If you help me fix this that would mean alot , thankyou 
-MacawLinux

**Comment by MacawLinux** [comment] 2021-06-29 18:38
Also I do have linux and dev mode enabled.

**Comment by MacawLinux** [comment] 2021-06-29 18:42
Here![Screenshot 2021-06-29 12 41 32 PM](https://user-images.githubusercontent.com/86641971/123850642-81ab7d80-d8d7-11eb-9b44-58ad02888179.png)is a screenshot:

**Comment by MacawLinux** [comment] 2021-06-29 18:46
when I do sudo crouton -u 
click here for the output/error: https://pastebin.com/MYgQC1PT

**Comment by cathenauwu** [comment] 2021-06-29 18:51
It looks like this is a duplicate of issue #4450. I answered how to fix this there.

**Comment by DennisLfromGA** [comment] 2021-07-01 02:43
Yes, it is, please track it here:

- Linux not installing saying something like CRAS #4450 (comment)

**Closed by DennisLfromGA** 2021-07-01 02:43 UTC
