### ISSUE TITLE
Gnome, Unity, Kde doesn't work on Focal Fossa

### ISSUE THREAD

**Issue by Just-Randomly-Me** [dnschneid/crouton#4500] opened 2021-05-27 08:24 UTC
```
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.20.9
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.0-140-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.14.232-17769-g23d4a2633f21 #1 SMP PREEMPT Sun May 23 21:06:22 PDT 2021 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 4710400 verity payload=PARTUUID=db693ba5-f586-46ca-a0a4-61f42366edb3/PARTNROFF=1 hashtree=PARTUUID=db693ba5-f586-46ca-a0a4-61f42366edb3/PARTNROFF=1 hashstart=4710400 alg=sha256 root_hexdigest=deada098fba2c35eba382bc7d6f98c2273069e0cfcab3058a427382d71454f53 salt=56f1b176dd28fb60a20f2c4b05409caad0a718c59d316db1a6d14214e9188899" noinitrd vt.global_cursor_default=0 kern_guid=db693ba5-f586-46ca-a0a4-61f42366edb3 add_efi_memmap boot=local noresume noswap i915.modeset=1 gsmi.s0ix_logging_enable=1 intel_idle.slp_s0_check=1  
Build Date: 08 April 2021  12:29:22PM
xorg-server 2:1.20.9-2ubuntu1.2~20.04.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.38.4
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu May 27 16:20:15 2021
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1622103615.941082 sender=:1.343 -> destination=:1.884 serial=42802 reply_serial=2
   boolean true
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
pkexec version 0.105
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20200724165050~master:08dac970
release: focal
architecture: amd64
xmethod: xorg
targets: xorg,audio,core,gtk-extra,x11,gnome
host: version 13982.4.0 (Official Build) dev-channel octopus 
kernel: Linux localhost 4.14.232-17769-g23d4a2633f21 #1 SMP PREEMPT Sun May 23 21:06:22 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output DP2 is not disconnected but has no modes
Kicking xrandr again
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output DP2 is not disconnected but has no modes
Kicking xrandr again
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1622103624.119335 sender=:1.343 -> destination=:1.886 serial=42817 reply_serial=2
   boolean true
(II) Server terminated successfully (0). Closing log file.
```

#### Please describe your issue:
Whenever i start "startgnome/sudo startgnome" the screen will go black then it will crash the X server and failed to start the desktop

#### If known, describe the steps to reproduce the issue:
I tried sudo startgnome and in chroot startgnome but nothing works

**Comment by Just-Randomly-Me** [comment] 2021-05-27 10:10
Currently finding ways to fix it I'll update this when I found a way

Edit:
For anyone having the same issue as me type this:
sudo crouton -t ____ -r sid        The blank is for your operating system like XFCE4 or GNOME

Another edit:
As for i would like to try it. I also would like to try other distros instead so if that fix your problem then good, if not sorry.

**Comment by Just-Randomly-Me** [comment] 2021-05-27 12:11
Also let me know in the comments if you guys have any fixes for it etc.....

**Comment by MrHallway0** [comment] 2021-07-08 16:19
Duplicate of #4368.

**Closed** 2021-07-10 20:13 UTC

**Comment by termonaitor2004** [comment] 2022-03-12 19:44
fix for gnome
enter the chroot: sudo enter-chroot -n focal
sudo apt-get install nano
dont put anything just press ctrl+x 
then stay in chroot 
startgnome
