### ISSUE TITLE
Black Screen on Fresh Install

### ISSUE THREAD

**Issue by cryssycat** [dnschneid/crouton#2946] opened 2016-12-13 20:14 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all
```

> chronos@localhost / $ sudo edit-chroot -all
> name: precise
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/precise...
> crouton: version 1-20161129162558~master:5f2f11f9
> release: precise
> architecture: amd64
> xmethod: xorg
> targets: xfce
> host: version 9000.26.0 (Official Build) dev-channel banjo 
> kernel: Linux localhost 3.10.18 #1 SMP Sun Dec 11 21:56:42 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
> freon: yes
> Unmounting 
> /mnt/stateful_partition/crouton/chroots/precise...

#### Please describe your issue:
sudo startxfce4 produces a black screen, no mouse, nothing, just black.

#### If known, describe the steps to reproduce the issue:
- Installed fresh chroot via sudo sh ~/Downloads/crouton -t xfce
- Ran sudo startxfce4
- Resulted in black screen.

**Comment by vswarte** [comment] 2016-12-13 20:54
Duplicate of #2923

**Comment by rtpavlovsk21** [comment] 2016-12-21 02:36
See if [2917/2926](https://github.com/dnschneid/crouton/issues/2917#issuecomment-267411158) fixes your problem. I had a black unlit screen with startlxde and modesetting seemed to fix it. It would be interesting to know which processor/chromebook you have.

**Comment by davydka** [comment] 2017-02-09 19:30
I ran into this problem and [2917/2926](https://github.com/dnschneid/crouton/issues/2917#issuecomment-267411158) solved the problem for my Lenovo 100s.

**Closed** 2017-03-16 01:22 UTC
