### ISSUE TITLE
chroots will no longer boot to gui after updating chrome OS to version 56.0.2924.9 dev (64-bit)

### ISSUE THREAD

**Issue by BikeViolin** [dnschneid/crouton#2917] opened 2016-11-30 09:32 UTC
```
chronos@localhost / $ sudo edit-chroot -all
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 9000.10.0 (Official Build) dev-channel setzer 
kernel: Linux localhost 3.18.0-13485-gfd54df3 #1 SMP PREEMPT Mon Nov 28 22:00:34 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
name: trustycore
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trustycore...
crouton: version 1-20161116131524~master:9db73043
release: trusty
architecture: amd64
targets: core
host: version 9000.10.0 (Official Build) dev-channel setzer 
kernel: Linux localhost 3.18.0-13485-gfd54df3 #1 SMP PREEMPT Mon Nov 28 22:00:34 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trustycore...
```

#### Please describe your issue:

updated chrome OS now chroots won't boot to gui, something to do with dbus failing?

haven't checked the CLI only chroot.

#### If known, describe the steps to reproduce the issue:

```
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-13485-gfd54df3 #1 SMP PREEMPT Mon Nov 28 22:00:34 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=df213b0f-1abc-d547-9e40-48546f69870e/PARTNROFF=1 hashtree=PARTUUID=df213b0f-1abc-d547-9e40-48546f69870e/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=54286f5193b0b38e151c62ab05ef90af45468c46 salt=b1bb29eeb4f179f0b75f5d8ead872d6d11c47ec1cb48ee502094c0df2d5dee7c" noinitrd vt.global_cursor_default=0 kern_guid=df213b0f-1abc-d547-9e40-48546f69870e add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Nov 30 09:22:07 2016
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed: Permission denied
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 9000.10.0 (Official Build) dev-channel setzer 
kernel: Linux localhost 3.18.0-13485-gfd54df3 #1 SMP PREEMPT Mon Nov 28 22:00:34 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a window.
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
EOF in dbus-launch reading address from bus daemon
/etc/xdg/xfce4/xinitrc: 1: /etc/xdg/xfce4/xinitrc: ssh-agent: not found

** (xfce4-session:18843): CRITICAL **: Unable to contact D-Bus session bus: Unknown error

** (xfce4-session:18843): CRITICAL **: Unable to contact D-Bus session bus: //bin/dbus-launch terminated abnormally with the following error: EOF in dbus-launch reading address from bus daemon


(xfce4-session:18843): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_connect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_connect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:18843): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:18843): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed

(xfce4-session:18843): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:18843): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed

(xfce4-session:18843): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_connect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_connect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:18843): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:18843): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed

(xfce4-session:18843): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_disconnect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_disconnect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:18843): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:18843): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root

(xfce4-session:18843): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:18843): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed

(xfce4-session:18843): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:18843): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed

(xfce4-session:18843): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:18843): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed

(xfce4-session:18843): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:18843): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed

(xfce4-session:18843): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:18843): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed

(xfce4-session:18843): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!

** (xfce4-session:18843): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:18843): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
Failed to connect to Xfconf daemon: //bin/dbus-launch terminated abnormally with the following error: EOF in dbus-launch reading address from bus daemon

running 'ssh-agent -s -k'
/etc/xdg/xfce4/xinitrc: 1: eval: ssh-agent: not found
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down xscreensaver: 09:22:32: SIGHUP received: restarting...
xscreensaver: 09:22:32: running as thomas/thomas (1000/1000)

Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.
xscreensaver: 09:22:32: Can't open display: :1
xscreensaver: 09:22:32: running as thomas/thomas (1000/1000)

xscreensaver: 09:22:32: Errors at startup are usually authorization problems.
              But you're not logging in as root (good!) so something
              else must be wrong.  Did you read the manual and the FAQ?

              http://www.jwz.org/xscreensaver/faq.html
              http://www.jwz.org/xscreensaver/man.html


Unmounting /mnt/stateful_partition/crouton/chroots/precise...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/precise...
```

**Comment by Matttter** [comment] 2016-11-30 10:53
I have this issue as well, started doing this right after the update to 56.0.2924.9 dev (64-bit) on Asus C300

**Comment by BikeViolin** [comment] 2016-11-30 13:51
My trustycore chroot still works but presumably that's just because it runs in the crosh shell window still.

**Comment by Matttter** [comment] 2016-11-30 14:17
Shell works just fine (by doing enter-chroot), but as soon as I want to
start the GUI it shows just a black screen

Op wo 30 nov. 2016 om 14:52 schreef BikeViolin <notifications@github.com>:

**Comment by lovitus** [comment] 2016-11-30 15:37
i have the same issue.
try to update my crouton ubuntu ,but run xfce4 just gnome-shell work only

**Comment by pungami** [comment] 2016-11-30 22:17
It seems xiwi target/xmethod works (startxfce4 -X xiwi), but xorg 3D acceleration (Minecraft ;) is broken by the update. Asus C300SA (Trusty).

**Comment by Paumanok** [comment] 2016-11-30 23:19
not exactly the same issue but I'm having a change of behavior with graphics with the same chromeOS dev version. Where switching to the chroot used to be instant, its now only instant when switching back to ChromeOS and will delay with a screen shutoff when entering my chroot, similar to when graphics drivers load from a login screen to desktop on a full Linux install. It's a C720 running ubuntu trusty with Linux 3.8.11.

```
chronos@localhost / $ sudo startgnome
Entering /mnt/stateful_partition/crouton/chroots/trusty...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Nov 28 21:50:50 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=962c6933-4c43-c249-8c32-8869abe9c77a/PARTNROFF=1 hashtree=PARTUUID=962c6933-4c43-c249-8c32-8869abe9c77a/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=bd92bdabb4bac439a1ee5a60d99ffe3e49a6acf1 salt=8df054303498d0b506ffd25728ca7114d70ac5262cf3fc15a04e4d6c65f49fdc" noinitrd vt.global_cursor_default=0 kern_guid=962c6933-4c43-c249-8c32-8869abe9c77a add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Nov 30 18:10:17 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Unable to set master
xf86: found device 0
xf86: found device 0
crouton: version 1-20150414182244~master:da478a77
release: trusty
architecture: amd64
xmethod: xorg
targets: gnome,xfce
host: version 9000.10.0 (Official Build) dev-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Nov 28 21:50:50 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
```

**Comment by Anu78** [comment] 2016-12-04 22:07
Mine plays the booting sound, but then it's a black screen from there.

**Comment by Anu78** [comment] 2016-12-04 22:08
I'm on 56.0.2924.12 (Official Build) dev (64-bit)

**Comment by Anu78** [comment] 2016-12-04 22:11
I'm also using KDE

**Comment by pungami** [comment] 2016-12-04 22:28
Debian “stretch” (testing) seems not affected and working fine!
(cannot confirm xorg versions, but "Trusty" was the one affected/failed after the update on this same C300SA hardware).

**Comment by jefesaurus** [comment] 2016-12-04 22:44
Just piling on here to say my trusty + i3 no longer works after the update:
```
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: touch,x11,core,cli-extra,audio,chrome-beta,xorg,xiwi
host: version 9000.10.0 (Official Build) dev-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Mon Nov 28 21:57:32 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Another instance of croutontriggerd running, waiting...
Another instance of croutonclip running, waiting...
deciding for version 4 due to this line: # i3 config file (v4)
i3: No usable outputs available.

Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file.
```

xiwi works

**Comment by dvwz** [comment] 2016-12-06 06:44
I'm having the same exact issue. xiwi works I'm on a Samsung Chromebook 3.

**Comment by DennisLfromGA** [comment] 2016-12-06 16:11
@Paumanok,

I think the original issue may be due to some dbus problems but yours I think, as you mentioned, is a little different.

It looks like you might be experiencing this: 
[Probably to do with xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted) #2926](https://github.com/dnschneid/crouton/issues/2926)

-**DennisL**

**Comment by pungami** [comment] 2016-12-06 23:28
Yap, issue #2926 Xorg blank screen sounds all the same; but something I noticed for Debian Jessie over here:
Build Date: 11 February 2015  12:32:02AM xorg-server 2:1.16.4-1
"xf86EnableIOPorts: failed to set IOPL..." error message is there, but that doesn't stop X from loading - starts up, just without GPU acceleration.

On Debian Stretch all good:
Build Date: 06 September 2016  01:32:44PM xorg-server 2:1.18.4-2
No IOPL error message and 3D Hardware acceleration and glxgears all running.

**Comment by joerosato** [comment] 2016-12-15 00:50
Also the same issue, can boot into console but gui just gives black screen. I'm on acer c720 using trusty.

Version 56.0.2924.26 beta (64-bit)
Platform 9000.26.0 (Official Build) beta-channel peppy
Firmware Google_Peppy.4389.93.0

Installed a completely new trusty next to my current and still the same issue.

**Comment by rtpavlovsk21** [comment] 2016-12-15 19:00
56.0.2924.26 (Official Build) beta (64-bit)
9000.26.0 (Official Build) beta-channel peppy
Acer 720p

I noticed that the xf86-video-intel driver was being referenced in startlxde. According to some arch posts [modeset should be used over xf86-video-intel](https://www.reddit.com/r/archlinux/comments/4cojj9/it_is_probably_time_to_ditch_xf86videointel/), [SNA acceleration sometimes causes problems and UXA can solve some issues](url). 

The file I chaged was /usr/share/X11/xorg.conf.d/20-crouton-intel-sna.conf:
```bash
Section "Device"                                                                                                                                     
#   Identifier "Intel Graphics SNA+TearFree"                                                                         
#   Option     "AccelMethod" "sna"                                                                                                                   
#   Option     "TearFree"    "true"                                                                                                        
   Identifier "Modesetting"                                                                                                                
   Driver     "modesetting"                                                                                                                  
EndSection     
```
Im not sure about the performance comparisons, however i am trying this for now.

**Comment by jdfight** [comment] 2016-12-15 22:14
@rtpavlovsk21  Thanks! That fixed my issue.  I was having the "xf86EnableIOPorts: failed to set IOPL" issue with chroot booting to a blank screen.

**Comment by livejamie** [comment] 2016-12-16 09:35
So how is this fixed?

**Comment by joerosato** [comment] 2016-12-16 10:04
Same here.. @rtpavlovsk21 fix worked for me. My chroot is named trusty, so:

`chronos@localhost ~ $ sudo enter-chroot -n trusty
Entering /mnt/stateful_partition/crouton/chroots/trusty...
(trusty)joe@localhost:~$ sudo vi /usr/share/X11/xorg.conf.d/20-crouton-intel-sna.conf
(trusty)joe@localhost:~$ `

**Comment by DennisLfromGA** [comment] 2016-12-16 20:49
It looks like this issue got derailed a tad. 

Instead of resolving the black screen with dbus errors we instead ventured into the one I mentioned in https://github.com/dnschneid/crouton/issues/2917#issuecomment-265191827

So the fix mentioned in https://github.com/dnschneid/crouton/issues/2917#issuecomment-267411158 will **not** help with this issue - as far as I know.

However it *may* help with this issue: [Probably to do with xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted) #2926](https://github.com/dnschneid/crouton/issues/2926)

*Hope this helps,*
-**DennisL**

**Comment by keidax** [comment] 2016-12-17 04:24
@rtpavlovsk21 setting the modesetting driver doesn't work for me, it causes Chrome OS to crash. Running on a Toshiba Chromebook 2 (2015).

**Comment by rtpavlovsk21** [comment] 2016-12-17 09:22
@keidax would you edit the your post with a longer description of your problem? Maybe the output of the desktop env start in the original state... the second link in my post was suppose to go to the arch wiki https://wiki.archlinux.org/index.php/intel_graphics  which may also give you some hints.

**Comment by KenDickey** [comment] 2016-12-20 00:31
My Acer Chromebook 13 also crashed after the ChromeOS update.  Updating did not fix.

The 20-crouton-intel-sna.conf fix was partially successful.  I can now start xfce4 and switch _once_ back to ChromeOS with ctl-shift-alt-arrow, but trying to get back to Ubuntu again causes crash.

I not some cursor oddities (graphic misdrawn; shape changes not tracked).

Perhaps the following from the entry screen (cros->shell) helps:

Thanks in advance,
-KenD
===============================
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: 27: test: x-X: unexpected operator
/usr/bin/startxfce4: 40: test: x-X: unexpected operator
/usr/bin/startxfce4: 27: test: xxorg: unexpected operator
/usr/bin/startxfce4: 40: test: xxorg: unexpected operator
/usr/bin/startxfce4: 27: test: x-b: unexpected operator
/usr/bin/startxfce4: 40: test: x-b: unexpected operator
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-67-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Wed Dec 7 23:44:15 PST 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=e01e2f02-4d7c-6b4d-bcb3-e4b867ed3e1f/PARTNROFF=1 hashtree=PARTUUID=e01e2f02-4d7c-6b4d-bcb3-e4b867ed3e1f/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=868ece04a91943db21f34a6cda3925d461a71710 salt=ef288cc5f1503088a3abf85154e3f6d15f20a22bed7ada9a8ce55ac35752b499" noinitrd vt.global_cursor_default=0 kern_guid=e01e2f02-4d7c-6b4d-bcb3-e4b867ed3e1f  
Build Date: 12 February 2015  02:55:07PM
============...

**Comment by randomekek** [comment] 2016-12-27 03:51
I had this issue "xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)"
I'm on beta chromeos. The xorg config change seemed to fix the issue.

name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xfce,xiwi
host: version 9000.29.0 (Official Build) beta-channel panther 
kernel: Linux localhost 3.8.11 #1 SMP Wed Dec 14 21:56:55 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by eliot2** [comment] 2016-12-31 04:47
If your problem is the IOPL error, do the following:
(this worked on my c720p Acer)
Change 
/mnt/stateful_partition/crouton/chroots/test2/etc/crouton/xorg-intel-sna.conf 
to

```
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# On Intel platforms with FBC enabled, in order to see anything we need to use
# the SNA driver with the TearFree option.
Section "Device"
   #Identifier "Intel Graphics SNA+TearFree"
   #Driver     "intel"
   # Option     "AccelMethod" "uxa"
   # Option     "TearFree"    "true"
   Identifier "Modesetting"
   Driver "modesetting"
   Option "AccelMethod" "sna"
   Option "TearFree" "true"
EndSection
```

Keep in mind, depending on your system, it might be /mnt/stateful_partition/crouton/chroots/test2/usr/share/X11/xorg.conf.d/20-crouton.conf
That you have to modify, OR
/mnt/stateful_partition/crouton/chroots/test2/usr/share/X11/xorg.conf.d/20-crouton-intel-sna.conf 
but that last file is actually just a symbolic link to
/mnt/stateful_partition/crouton/chroots/test2/etc/crouton/xorg-intel-sna.conf

**Comment by DennisLfromGA** [comment] 2016-12-31 21:08
I'm pretty sure the **dbus errors** are only affecting the **precise** release so if you run into this try a newer release.

If you run into these **dbus errors** on a **newer** release than precise please post back here.

*Hope this helps,*
-**DennisL**

**Comment by pmarkkula** [comment] 2017-01-01 15:15
I think the xorg conf file should be like this if you want acceleration with modesetting driver:

`
Section "Device"
   Identifier "Modesetting"
   Driver     "modesetting"
   Option     "AccelMethod" "glamor"
   Option     "PageFlip"    "true"
EndSection
`
At least according to manual pages valid choices for "AccelMethod" are "glamor" and "none". This works for me for both trusty and xenial xfce4 chroot with 56.x ChromeOS on c720 (Celeron 2955U). Desktop that is, I haven't tested any applications that would really require acceleration. I made accidental ChromeOS update yesterday and here are my experiences with modesetting driver so far:

Trusty:
- There appears to be tearing. "PageFlip" option should help, but does not seem to.
- Windows in Firefox are not always rendered when content of window changes.
- Sometimes when starting chroot I get black screen with cursor. Switching to ChromeOS and back fixes this.

Xenial:
- No tearing, no rendering problems. Seems to just work.

I am using xenial graphics stack on trusty, but it provides 1.18.3 xorg-core and xenial has 1.18.4. Maybe that explains differences in tearing and rendering.

**Comment by DennisLfromGA** [comment] 2017-01-01 15:34
@pmarkkula,

Your '/tmp/Xorg.crouton.1.log' file should give you/us more info. about what's going on.
Look for warnings (WW) and errors (EE) to see what the problems might be.

*Hope this helps,*
-**DennisL**

**Comment by pmarkkula** [comment] 2017-01-01 15:53
Here it is. Unfortunately there doesn't seem to be any obvious warnings or errors. 

[Xorg.crouton.1.log.txt](https://github.com/dnschneid/crouton/files/680061/Xorg.crouton.1.log.txt)

**Comment by eliot2** [comment] 2017-01-01 16:00
@pmarkkula 's comment: https://github.com/dnschneid/crouton/issues/2917#issuecomment-269906678

This is even better! I use Unity3d-Editor for linux, a game dev engine. It wasn't working with "sna" and "tearfree". When I changed to "glamor" and "pageflip" it worked! Thanks!

**Comment by pmarkkula** [comment] 2017-01-01 17:44
Most of the differences I noticed between trusty and xenial were caused by xenial having compositor enabled. When I enabled compositor on trusty and ticked "Synchronize drawing to the vertical blank" box, all rendering problems seem to be gone and tearing is reduced. Trusty is still not as good as xenial, there is still some tearing, but it is very usable.

**Comment by joseph-palmer** [comment] 2017-01-11 13:11
@eliot2 what do I type in the terminal to change the file as you describe above? I still cant access trusty and get the same error as described here. Thanks in advance.

**Comment by eliot2** [comment] 2017-01-11 14:23
vim filename

vim is a text editor. Google how to use it first. Trust me on that.

**Comment by DennisLfromGA** [comment] 2017-01-11 16:15
@joseph-palmer,

You want to install gedit if it's not already and use it instead.

-**DennisL**

**Comment by mattbreeden** [comment] 2017-01-18 06:59
I'm having a little bit of a hard time figuring out if I have this issue, or https://github.com/dnschneid/crouton/issues/2926

Have a Dell Chromebook 14 running trusty/i3. It won't boot into trusty, gives dbus and IOPL messages. Tried making xorg changes mentioned in this issue without success.

I'd love to look at the /tmp/Xorg log, but after the chroot fails to load, only the chrome visuals keep working. The cursor disappears (and seems to be unresponsive), and the keyboard doesn't seem to work except the power button. After I reboot, the /tmp file is gone. Anything I can do to see the information?

**Comment by keidax** [comment] 2017-06-19 03:15
I haven't been following this issue closely. Just tried it again after a few months away, and it seems to be resolved. Xorg starts and functions as expected.

**Comment by DennisLfromGA** [comment] 2017-06-20 03:21
Closing. Please re-open if this issue is still a concern.

**Closed by DennisLfromGA** 2017-06-20 03:21 UTC
