### ISSUE TITLE
Bullseye not installing on ARM64 chromebook

### ISSUE THREAD

**Issue by krome-3k** [dnschneid/crouton#4591] opened 2021-09-05 22:10 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue: Bullseye not installing on ARM64 chromebook

sudo crouton -r bullseye -t audio,extension,gnome,gtk-extra,keyboard,xorg ends in the screenshot.

![Screenshot 2021-09-06 3 35 55 AM](https://user-images.githubusercontent.com/89704836/132142695-484fa08c-ee27-47ab-981a-1d0ee523e4e9.png)

Please help.

**Comment by BetaPictoris** [comment] 2021-09-06 15:17
Duplicate of #4389

**Comment by DennisLfromGA** [comment] 2021-09-07 16:10
Closing. Please track the above issue for further details.

-**DennisLfromGA**

**Closed by DennisLfromGA** 2021-09-07 16:10 UTC

**Comment by krome-3k** [comment] 2021-09-07 18:25
Okay
