### ISSUE TITLE
Change the default bootstrap release to trusty?

### ISSUE THREAD

**Issue by tonyxue** [dnschneid/crouton#1997] opened 2015-08-06 05:49 UTC
The default release is still precise, which is really out of date. As trusty is working quite well now, how about switch to it?

If so, I'll submit the pr.

**Comment by tedm** [comment] 2015-08-06 08:12
@tonyxue Can you qualify or quantify "really out of date" ?

**Comment by divx118** [comment] 2015-08-06 15:31
@tonyxue  #1351 prevents a good experience with Unity on ARM. That is why it is still precise.

**Comment by DennisLfromGA** [comment] 2015-08-06 16:23
@tedm,

> Can you qualify or quantify "really out of date" ?

[Here 'tis](http://goo.gl/qzpDjj)

**Comment by tedm** [comment] 2015-08-06 17:45
this link?

http://askubuntu.com/questions/450555/very-slow-graphics-performance-after-upgrade-12-04-14-04

**Comment by drinkcat** [comment] 2016-10-11 22:32
Dupe of #1671.

**Closed by drinkcat** 2016-10-11 22:32 UTC
