### ISSUE TITLE
Unable to switch keyboard layouts?

### ISSUE THREAD

**Issue by Fatal1ty93RUS** [dnschneid/crouton#2036] opened 2015-08-21 00:50 UTC
This has been an on-going issue with my Ubuntu installations ever since I first tried doing it via Crouton:

Basically, I am unable to switch between input languages within Ubuntu using keyboard shortcuts. If I switch to ChromeOS - the default Shift+Alt command works just fine

in Ubuntu, however - the same command doesn't work. So I tried remapping the shortcut - no success. I tried usng CTRL+ALT, CTRL+Space, CTRL+Shift, Shift+Space, etc - none of those work. I also tried setting up a shortcut and rebooting - no success. Setting up a shortcut and logout/log back in? Same thing

At this point the only way I can actually switch language is to manually navigate towards the input switcher and click on the other language, and do it every time I need to start typing in different language (gets especially annoying when using words from both languages within the same text or even the same sentence

Is it a bug with Crouton or an easily fixable thing?
Thanks in advance

**Comment by tista500** [comment] 2015-08-21 18:28
@Fatal1ty93RUS, You had this issue on Unity desktop, right? So could you please post these outputs?

1.
`croutonversion`
2.
`gsettings get org.gnome.desktop.interface gtk-im-module`
3.
`echo $GTK_IM_MODULE`

Regards.

**Comment by SnarkBoojum** [comment] 2015-08-21 18:40
Isn't it a duplicate of #2020 -- where a fix is given ?

**Comment by tista500** [comment] 2015-08-21 18:53
@Fatal1ty93RUS, I didn't say this could be related to #2020. I need to sort in order. Because sometimes gnome(unity)-settings-daemon and gsettings-desktop-schema causes misleading the IM setting.

Regards.

**Comment by Fatal1ty93RUS** [comment] 2015-08-21 19:52
@tista500 this is the output for each command:

1. Croutonversion
crouton: version 1-20150604154515~master:91b3e350
release: trusty
architecture: amd64
xmethod: xorg
targets: audio,chrome,cli-extra,core,gtk-extra,keyboard,unity-desktop,xorg
host: version 7077.134.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Sun Aug 16 14:33:03 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

2. gsettings get org.gnome.desktop.interface gtk-im-module
'gtk-im-context-simple'

3.  echo $GTK_IM_MODULE
ibus

Hopefully this helps..

**Comment by tista500** [comment] 2015-08-21 20:20
OK. Let's starting some tweaks.

1. Set ibus as default IM engine:
`gsettings set org.gnome.desktop.interface gtk-im-module 'ibus'`

2. Launch ibus setting window:
`ibus-setup`

3. In "General" tab, set "Next input method" keybindings for the trigger of switching keyboard layout (or IM emgine). I don't think "Alt + Shift" might be suitable keybinding for ibus. Ctrl + space, Shift + space, and others would be welcome (Since the combination of "modifier keys only" is not for general use..).

4. In "Input Method" tab, registered layout list can be shown. So add your desired layout from "Add" button.

5. Reload ibus-daemon to re-initialize with your settings:
`ibus-daemon -rd &`

Please give it a try.

Regards.

**Comment by Fatal1ty93RUS** [comment] 2015-08-21 20:34
@tista500 Nope, it didn't work

Might it be because I'm using standard Gnome Flashback instead of Unity?

**Comment by tista500** [comment] 2015-08-21 20:42
Sounds sad... :(
And no, Trusty's gnome-session-flashback uses unity-settings-daemon same as unity-desktop. So those could accept the same method...

Regards.

**Comment by Fatal1ty93RUS** [comment] 2015-08-21 20:48
@tista500 what's funnier is that I remember it WORKED just once. Like, I set the shortcut to something like CTRL+ALT, then I reloaded Ubuntu (quit into CHROMEOS then logged back in) - and it actually worked.and then the next time I loaded Ubuntu - it didn't work anymore. 
It's really weird

**Comment by tista500** [comment] 2015-08-21 20:54
@Fatal1ty93RUS, Yeah sounds weird. But actually in past, ibus and settings-daemon had avoided some keybindings like Shift+space and so, please check your ibus settings properly after exiting chroot and loging in again.

I'm also tracking this issue down on my other machine.

Regards.

**Comment by tista500** [comment] 2015-08-21 22:36
@Fatal1ty93RUS, if you had "indicator-keyboard" in your system, try to purge it:
`sudo apt-get purge indicator-keyboard`

Logout the chroot and re-login, and retry ibus setting that I've showed above... I'm not sure whether indicator-keyboard wanted to override ibus or not, but already indicator-keyboard didn't work as we expected. And if gnome-panel had a notification-tray applet, ibus icon would be shown there after reloading ibus-daemon...

Regards.

**Comment by Fatal1ty93RUS** [comment] 2015-08-22 01:11
@tista500 well... I tried to purge it.... and seems like the indicator was deleted....

Two things:
1) this command pretty much has wiped all the settings options Ubuntu usually has (so I can no longer setup display, mouse, etc.), looks like I'll have to install everything from scratch

2) this did not fix the language switcher problem still, I suppose I'm stuck with the click-to-switch-input-language method for now

**Comment by tista500** [comment] 2015-08-22 01:23
@Fatal1ty93RUS, This command could recover unity-desktop?
```
sudo apt-get install --reinstall ubuntu-desktop
```

Regards.

**Closed** 2016-10-11 19:52 UTC
