### ISSUE TITLE
Arch Linux support

### ISSUE THREAD

**Issue by henrywright** [dnschneid/crouton#2367] opened 2016-01-13 02:04 UTC
Hey guys,

Are there any plans to provide support for Arch Linux? I'd like to give that distro a try one day :)

**Comment by wulvyrn** [comment] 2016-01-13 19:06
i've seen some other postings on reddit and google+ looking for the same support.  chroagh does not seem to be maintained; installs require work arounds and stateful_partitions not unmounting, etc.

I agree, arch linux would be nice.  thank you.

**Comment by mahasamoot** [comment] 2016-02-05 03:13
I third that

**Comment by dragon788** [comment] 2016-02-26 04:03
Arch is supported in the fork here, https://github.com/drinkcat/chroagh

**Comment by aa0na** [comment] 2016-02-26 12:39
Chroagh has not been updated or rebased in over a year.

**Comment by drinkcat** [comment] 2016-03-08 10:40
Sort of duplicate of #1201. I'm painfully aware that chroagh has not been rebased in a long time, sorry about that.

Arch Linux support is tricky in the long run, as it is a rolling release, and things may break unexpectedly. If somebody wants to pick up the work in #1201, it would be totally awesome, and I'd be happy to review changes. Otherwise, sorry, can't give you any ETA on Arch support...

**Closed by drinkcat** 2016-03-08 10:40 UTC
