### ISSUE TITLE
Missing characters in xfce

### ISSUE THREAD

**Issue by spafindoople** [dnschneid/crouton#2640] opened 2016-06-22 02:50 UTC
#### System info

```
name: xfce
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xfce...
crouton: version 1-20160620130246~master:c39102d9
release: precise
architecture: amd64
xmethod: xorg
targets: extension,xorg,xiwi,xfce
host: version 8172.47.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jun 1 20:27:37 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
#### Please describe your issue:

I have had xfce for about a year now, but this issue has come up about a month ago. What happens is that several characters are missing in the interface:
![weird](https://cloud.githubusercontent.com/assets/10279512/16253162/fa09297a-37e8-11e6-8392-2590ba6bc495.png)
On the ubuntu forums, there is a solution called ubuntu-tweak, however, the buttons in its gui do not render, making me unable to use it. Any help?

**Comment by flynch** [comment] 2016-07-09 14:33
I ran into the same issue, after a little reading I found that this was an issue with sna acceleration in the intel graphics card in my Acer chromebook 15" model. 
Following the advise from https://wiki.archlinux.org/index.php/intel_graphics#SNA_issues
I modified /etc/crouton/xorg-intel-sna.conf so that it looks like the following:
```

$ cat /etc/crouton/xorg-intel-sna.conf
Section "Device"
   Identifier "Intel Graphics uxa"
   Driver     "intel"
  Option      "AccelMethod"  "uxa"
EndSection

```

**Comment by DennisLfromGA** [comment] 2016-07-09 15:01
@flynch 

Just curious -

- Did you replace the existing 'Intel Graphics SNA+TearFree' driver with 'Intel Graphics uxa' or did you add the other driver to it?
- In other words, what is the content of `xorg-intel-sna.conf` now?

Maybe a 2nd '.conf' file for 'uxa' needs to be added.

-**DennisL**

**Comment by flynch** [comment] 2016-07-09 15:16
@DennisLfromGA 

> 
> Did you replace the existing 'Intel Graphics SNA+TearFree' driver with 'Intel Graphics uxa' 
>  or did you add the other driver to it?
> 

I simply modified xorg-intel-sna.conf and replaced  'Intel Graphics SNA+TearFree'  with  'Intel Graphics uxa', the entire contents of my xorg-intel-sna.conf is in my previous post.

> Maybe a 2nd '.conf' file for 'uxa' needs to be added. 

You may be right about that, but I don't know enough about how X is setup on crouton to go about doing that. 
I went with the path of least resistance and simply hacked my xorg-intel-sna.conf.

**Comment by DennisLfromGA** [comment] 2016-07-09 16:24
@flynch,

The comment in the `xorg-intel-sna.conf` file reads:
> \# On Intel platforms with FBC enabled, in order to see anything we need to use
> \# the SNA driver with the TearFree option.

Are you saying 'sna' is no longer valid?
If so, possibly what needs to be done is to -
replace -
> Option      "AccelMethod"  "sna"

with -
> Option      "AccelMethod"  "uxa"

leaving -
> Option     "TearFree"    "true"

in place.

In other words, the `xorg-intel-sna.conf` file would be replaced with a `xorg-intel-uxa.conf` file with the contents:
> Section "Device"
   Identifier "Intel Graphics UXA+TearFree"
   Driver     "intel"
   Option     "AccelMethod" "uxa"
   Option     "TearFree"    "true"
EndSection

Either way, the crouton gurus will have to weigh in on this since it may be device specific.

-**DennisL**

**Comment by flynch** [comment] 2016-07-10 00:53
I am seeing lots of tearing,  Option "TearFree" "true" seems to make very little difference. 
There is a good tearing test over on youtube: https://www.youtube.com/watch?v=5xkNy9gfKOg
I will post back here if I find a workaround. However I think I can live with this, as I watch most videos in chrome.

**Comment by spafindoople** [comment] 2016-07-10 15:42
@flynch,

Thanks for you solution. It seems to work for me now.

**~Spafindoople**

**Comment by DennisLfromGA** [comment] 2016-07-10 16:17
@flynch - *Sounds like this is a winner*. Maybe a Pull Request would be in order??? -**DennisL**

**Comment by drinkcat** [comment] 2017-03-15 23:51
I think this was fixed by a Chrome OS update.

**Closed** 2017-03-15 23:51 UTC

**Comment by Venryx** [comment] 2017-11-01 23:34
I'm getting this same issue (some characters missing) on the ASUS C302CA (x86). The issue is not present on my other Chromebook, a Lenovo N23 Yoga (ARM).

**Comment by Venryx** [comment] 2017-11-02 01:41
I updated the chroot to target "xfce-desktop" instead of "xfce", and the problem is now resolved.

Might be worth mentioning this potential issue somewhere in the Readme or target-listing, however.

**Comment by DennisLfromGA** [comment] 2017-11-02 02:07
@Venryx,

The [xfce-desktop](https://github.com/dnschneid/crouton/blob/master/targets/xfce-desktop#L13) target also install these meta packages packages -

- `install ubuntu=xubuntu-desktop,task-xfce-desktop`

I guess one of them addressed your issue.

**Comment by jtebert** [comment] 2017-11-05 18:53
I'm encountering the same problem after updating to ChromeOS 61 on my Samsung Chromebook Pro. However, it seems that setting the target with xfce-desktop didn't work in my case (using `sudo sh ~/Downloads/crouton -u -n chrootname -t xfce-desktop`). It also seems to be accompanied by various other graphical glitches that make Crouton essentially unusable.

**Comment by Venryx** [comment] 2017-11-05 19:17
Yeah, I found after more testing that that didn't resolve the issue -- for some reason, the glitches show up some launches but not others.

However, I did find a way to _reduce_ the occurrence of the glitches. Go to Settings>Appearance>Font, then enable anti-aliasing and set "Hinting" to slight (or some value other than "None")

For me, this makes the glitch show up in fewer places -- it at least doesn't show up on the desktop and taskbar anymore. It still shows up in some dialogs.

**Comment by Venryx** [comment] 2017-11-25 11:15
After more testing, it appears that the change above only solves the issue for the given desktop-environment launch. If you restart the chroot/desktop-environment, it may come back. (sometimes it does, sometimes it doesn't) IIRC, it can sometimes also reappear if you use the hotkey to return to ChromeOS, then reenter it.

However, I get by at the moment with the fix above: if the issue shows up, I open the "Appearance" app/window, press the "Font" tab, and switch the Hinting from "None" to "Slight" (or vice versa).

Definitely not ideal, but at least keeps crouton usable until a proper fix is made.

**Comment by kelchm** [comment] 2017-11-26 19:26
Also seeing this issue on my Chromebook Pro. I've seen similar issues in other desktop environments including Gnome and Unity.

**Comment by jtebert** [comment] 2017-11-27 02:02
Since this is still an ongoing problem, is there a way we get this issue reopened? (Or just start a new issue?)

**Comment by lightningmonkey** [comment] 2017-12-03 19:39
I am also seeing the same issue. @Venryx  fix for flipping the Hinting seems to work for now, but it is far from ideal.

**Comment by exim13** [comment] 2017-12-03 20:00
I am getting the same issue as well on my Chromebook Pro. Hinting fixes most of it, but letters are still missing in the web browser

**Comment by Venryx** [comment] 2017-12-03 21:21
The fix suggested by @flynch / @DennisLfromGA does seem to work for me. (I didn't try it at first, because  it seemed there wasn't concensus on what the contents should be, and required modifying system files; but I ended up trying the version suggested by @DennisLfromGA)

I will update here if the problem reoccurs.

@exim13, @lightningmonkey, @kelchm, @jtebert Can you guys check if the fix works for you as well?

If so, adding the modification to the crouton scripts/repo would seem like a good idea; the glitch is  happening on Chromebook Pro and Asus Chromebook C302CA (among others), which are two of the major chromebooks out nowadays.

**Comment by exim13** [comment] 2017-12-04 20:23
I just tried editing the xorg-intel-sna.conf file like @flynch and @DennisLfromGA suggested but after a restart the problem was actually worse on my Chromebook Pro. So i reverted all the changes. I am not using xfce-desktop though, so I will try that next.

**Comment by Venryx** [comment] 2017-12-10 01:34
Update: Restarted a few times without issue, but then this last time, had letter issue again. (though only in Chrome title-bar instead of desktop and such)

Will update if shows up in more problematic areas. (dialogs, desktop, etc.)

**Comment by thebaron88** [comment] 2017-12-21 21:16
Just a note for anyone else that comes here. I had the same problem on a ASUS Chromebook Flip C302CA. I didn't try the solution from @flynch but I did try the solution on the referenced ticket #3500 (CROUTON_BRANCH=nointeldrv) which did **not** work (it failed to remove xserver-xorg-video-intel).

Instead I just did a fresh install of xfce and just ran "apt-get purge xserver-xorg-video-intel", works well so far. Will update if it stops working.

**Comment by Venryx** [comment] 2017-12-27 20:38
@thebaron88 Yes, please let us know if the fix continues working. The OP's suggested fix _seemed_ to work for a while, but now it is happening again. (including on the desktop)

As for my quick-fix mentioned above, of toggling the font-hinting between slight and none: I went ahead and made a shell script to do it automatically. Just place this script on your desktop, then whenever you start crouton and see the glitch has occurred, double click to run it:
```
if xfconf-query -c xsettings -l -v | grep "hintnone"; then
  xfconf-query -c xsettings -p /Xft/HintStyle -t string -s hintslight
else
  xfconf-query -c xsettings -p /Xft/HintStyle -t string -s hintnone
fi
```

For me, this fixes the missing-letters glitch in most places. (still shows up in some dialogs)

**Comment by thebaron88** [comment] 2017-12-28 00:42
Still working right now. Don't use it much, but I have had _no_ issues so-far.

**Comment by escalated** [comment] 2017-12-28 05:56
Just reporting in, another Asus C302 here with the same bug. Running "apt-get purge xserver-xorg-video-intel" as mentioned above, then restarting xfce seems to have fixed it for me as well.

**Comment by Venryx** [comment] 2017-12-28 11:09
Do either of you notice longer "screen freezes" after the change? It got so bad for me after the `apt-get purge` that I reverted back, even though it may have solved the missing-characters glitch. (I don't know for sure because I didn't try it for long enough)

Seriously, after the purge it would freeze chrome pages for 8+ seconds, every minute or so.

**Comment by escalated** [comment] 2017-12-28 15:02
@Venryx I'm not noticing any "screen freezes" like you are seeing. Although, this is a very fresh install. I just surfed around for 5 or 10 minutes with xfce running in another tab and didn't see any freezing/slowdown.

**Comment by Venryx** [comment] 2017-12-28 15:16
XFCE running in another tab?

Oh, I meant screen freezes in the Chromium browser that I installed within linux/crouton.

**Comment by arndtc** [comment] 2018-01-12 04:15
Also on Asus C302 here with the same bug. As @escalated commented the following seems to have worked for me as well.
"sudo apt purge xserver-xorg-video-intel" 
Followed by restarting  xfce.

**Comment by Venryx** [comment] 2018-01-12 04:31
Have you tried running Chromium within xfce? For me, the pages get severe (8+ second) freezes after running the command above. Reinstalling the package removes those freezes -- however then the visual glitches reappear.

**Comment by Venryx** [comment] 2018-01-22 09:00
Reinstalling the package actually left me worse then when I started, because now the "go back to ChromeOS" shortcut stops working! It just shows a black screen, requiring a reboot to access ChromeOS again. I will try restoring my chroot backup or using the chroot update command to see if it resolves this.

EDIT: Indeed, updating the chroot appears to have fixed the "cannot return to ChromeOS" issue.

For reference, there are three issues I've encountered:
1) Missing characters glitch.
2) 8+ second freezes in the chroot's Chromium or VSCode windows when scrolling.
3) Black screen on attempting return to ChromeOS.

* #1 is fixed using the purge command mentioned above (`sudo apt-get purge xserver-xorg-video-intel`). However, this then causes issue #2.
* To fix issue #2 (which is much more serious), I reinstalled the package I had just purged. This fixed #2, but caused #1 to return _AND_ caused issue #3 to appear.
* To fix issue #3 and return to my original situation, I downloaded the latest crouton script then ran `sudo sh ~/Downloads/crouton -u -n chrootname`.

So now I only have issue #1 again -- which is okay, certainly much better than either of the other two problems. And at least with issue #1, I can mostly fix it by running the `FixFonts.sh` script on the desktop whenever I launch the chroot. (included a few posts up)

**Comment by thebaron88** [comment] 2018-01-22 22:25
Reporting back after some extended use. _Sometimes_ I get the 8+ second freezes when `xserver-xorg-video-intel` is uninstalled. I can't find a pattern, sometimes it works for a long time without pauses, other times its a lot more frequent (always doing the same thing, just running PyCharm).

Reinstalling the package I get the same issue as @Venryx with screen switches. Not tried updating chroot to fix it. Also the script from above _seems_ to work with the missing characters bug, but only used once.

**Comment by papaknee** [comment] 2018-01-24 05:01
Been following this thread for a while and just wanted to mention that two posts ago from Venryx EXACTLY matches my experience on a ASUS Chromebook Asus C302. I've experienced issue 1, 2, and 3 exactly as described there. 

Perhaps too soon to tell but **I think I have a fix regarding the "8+ second freezes in the chroot's Chromium"** after purging the Intel driver. Restarted the chroot twice and tried only a half-dozen sites but seen 0 lags since turning off hardware acceleration in chromium per this how-to:

https://www.techadvisor.co.uk/how-to/internet/how-turn-off-gpu-hardware-acceleration-in-google-chrome-3605455/

I found this by looking up my computer's Intel graphics version (in chroot):
`localhost:~$ lspci -vnn | grep VGA -A 12`
`VGA compatible controller [0300]: Intel Corporation Sky Lake Integrated Graphics [8086:191e] (rev 07)`

And searching for issues with this hardware + Chrome in Linux forums, I found plenty of other users (not Crouton users though) with a similar issue: https://ubuntuforums.org/showthread.php?t=2327307

Hope this helps! (This is my first-ever post).

**Comment by Venryx** [comment] 2018-01-24 06:59
Thanks for the tip @papaknee!

In my chroot, I use a few different programs with web-views, so I'll probably stick with my current approach for now (using the FixFonts.sh script). This is because, I'm not sure if all of those programs support disabling gpu-rendering for them -- Chromium and vscode do, but I might use others which don't provide that option.

That said, I'll definitely keep your suggestion in mind for if I find the `FixFonts.sh` script insufficient later.

Hopefully we'll eventually have a system-level disabling of hardware-acceleration for the chroot possible.

**Comment by c---** [comment] 2018-02-03 00:10
As mentioned above, installing _xubuntu-desktop_ fixed this issue on my ASUS C302. If someone can figure out which package within that big install actually fixes the issue then it could be installed by default in the crouton install.

**Comment by Venryx** [comment] 2018-02-03 00:16
@c--- I'm the one who initially mentioned "xubuntu-desktop" as solving the issue. However, I found a few days later that the issue still occurs (I have an Asus C302 as well).

Since then, I have done additional testing of proposed solutions, and summed up what I learned in my second-last post. If you encounter the glitches again (I suspect you will since we have the same hardware), then you can read that for a partial solution. (basically, running the FixFonts.sh script whenever you see the glitch -- the other two solutions people mentioned didn't work for me or had worse side-effects)

**Comment by radumas** [comment] 2018-02-13 16:22
I also have this issue with Asus C302C but I have Ubuntu 16.04 with unity installed. `sudo apt-get purge xserver-xorg-video-intel` did not work for me, nor did updating the chroot.

**Comment by G88n** [comment] 2018-08-09 04:26
Hey everyone,

So I just installed xfce4 through crouton on an ASUS C302CA-DHM4. I was experiencing the same issues as described above with the font.

I fixed this issue by going into system settings and changing the font size to 11.

**Comment by Venryx** [comment] 2018-08-09 09:31
@G88n You may find, after a few days, that the problem comes back after the font size change. That's because, from my experience, changing font settings will fix the problem -- but only temporarily. Hence to "permanently solve", you need to automate the font-setting-change operation. (into a script file, which you run whenever you notice the glitches)

If that's not the case, and the glitches are permanently solved by the font-size change, then that's good to hear -- though would be odd since we all have the same hardware.

**Comment by G88n** [comment] 2018-08-09 12:52
@Venryx So I noticed if I shutdown the chroot instance via "shutdown" the font issues come back immediately upon next launch. This is despite the actual size setting still being at 11 when relaunching. However changing it to 12 and back to 11 (or probably keeping at twelve) fixes it again. If I exit the chroot session via logout and keep the "save session for future logins" box ticked the problem doesn't appear to come back, at least not immediately. 

I just figured this out last night though. I'll keep using this for a week and update this thread to let everyone know how it goes.
