### ISSUE TITLE
Search key doesn't register in chroot

### ISSUE THREAD

**Issue by haoxuany** [dnschneid/crouton#2728] opened 2016-08-15 05:00 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all
```
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/jessie...
crouton: version 1-20160715134041~master:0dc76a22
release: jessie
architecture: amd64
xmethod: xiwi
targets: extension,xiwi,keyboard,x11
host: version 8350.68.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Aug 2 21:29:22 PDT 2016 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:
The `search` key doesn't get registered by the chroot at all. This happens both with and without the keyboard target. 

To clarify, on my chromebook, I have swapped the `search` and `control` keys through chromeOS's own settings. In the chroot, `xev` shows that pressing the physical `search` key (which, in chromeOS, is mapped to Control), registers as Control_L. Pressing the `control` key (which, in chromeOS, is mapped to search), doesn't get registered at all. However, ChromeOS's own shortcuts involving search still work.

This behavior is only present in some recent update of ChromeOS (probably around 3 months). It used to work fine, so somehow the "search" function (which my physical Control key is mapped to) got grabbed by ChromeOS?

#### If known, describe the steps to reproduce the issue:
I have already reinstalled a new chroot (still jessie, with keyboard extension), and the problem is still reproduced. I am using awesome WM if that matters. In my old setup, the "search" function was mapped to Super_L, which in xmodmap has modifier Mod4. 

I have followed these updated steps: https://github.com/dnschneid/crouton/wiki/awesome
However, the pressing the physical control key (which is mapped to "search") doesn't even get registered in xev, so it didn't help.

**Comment by davidlowryduda** [comment] 2016-08-16 16:52
I also have this problem. I have used crouton and chroot for a long time, and this only began to occur to me last week.

I also get nothing in xev.

**Comment by davidlowryduda** [comment] 2016-08-18 00:46
I now notice that this is the same issue as here: https://github.com/dnschneid/crouton/issues/2699

**Comment by drinkcat** [comment] 2016-10-13 18:07
Duplicate of #2639.

**Closed by drinkcat** 2016-10-13 18:08 UTC
