### ISSUE TITLE
Probably to do with xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)

### ISSUE THREAD

**Issue by dwaindibbly** [dnschneid/crouton#2926] opened 2016-12-04 14:40 UTC
The problem is that when I do `sudo startlxde` the screen is black, i can do the Ctrl-Alt-Shift + Left or Right as in F1 or F2 to get back to Chrome Os's screen.
Do not suggest anything to do with `-u` or `locale` as I've tried both.
There is no mouse.
Points of interest are:
`xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)`

`Error executing command as another user: Not authorized`

`Cannot open /sys/class/tty/tty0/active: No such file or directory`

I'm x86_64.
Suggest a fix please.

CHROMEBOOK = ASUS C300

**Comment by dvwz** [comment] 2016-12-05 06:08
I'm having the same issue.

**Comment by DennisLfromGA** [comment] 2016-12-05 16:14
Y'All, Please us the output of: `sudo edit-chroot -all`

**Comment by Giow** [comment] 2016-12-05 20:19
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: audio,core,xorg,x11,gtk-extra,extension,chrome,xfce,keyboard
host: version 9000.15.0 (Official Build) dev-channel celes 
kernel: Linux localhost 3.18.0-13492-g308c6f5 #1 SMP PREEMPT Thu Dec 1 22:03:28 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by DennisLfromGA** [comment] 2016-12-06 16:21
I've seen what I believe is this same issue, it was posted on Crouton Central here:
> [did google break crouton with latest update?](https://groups.google.com/d/msg/crouton-central/hpkPu01OLtw/3TiLFAjGAgAJ).

At first, I thought it was due to some problems with the 'precise' release but the OP tried both 'trusty' & 'xenial' to no avail.
Then I thought it might have been a problem with the 'xfce4' target but the OP tried 'lxde' and still the same black screen.

The only suggestion that I offered that worked was switching to the 'xiwi' xmethod but that has no hardware acceleration so it's not a perfect solution.

Hopefully the devs can figure this out soon'ish, whenever they get some spare cycles...

*Hope this helps,*
-**DennisL**

**Comment by pungami** [comment] 2016-12-06 23:43
Fix is easy, install another chroot to try Debian Stretch ;)
(which has newer version of Xorg running fine still after the Chrome OS update)
i.e. the issue depends on the distro/release of the chroot in use.

**Comment by tdingman** [comment] 2016-12-13 02:53
Also having the same problem. Newest version of crouton, fresh Trusty install. I'm on a Pixel 2.

**Comment by jdfight** [comment] 2016-12-15 03:23
Same problem here - I have tried jessie, stretch and xenial chroots with xfce and lxde targets... same issue ( xf86EnableIOPorts: failed to set IOPL for I/O) on all.  Running with xiwi works but performance is not ideal.

**Comment by loltroll12** [comment] 2016-12-15 15:45
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
[intel_init_bufmgr:1069] Error initializing buffer manager.
setversion 1.4 failed: Permission denied
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 8872.70.0 (Official Build) stable-channel reks 
kernel: Linux localhost 3.18.0-13434-gc3678fb #1 SMP PREEMPT Wed Dec 7 23:29:16 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.

WHAT IS THIS
it crashes my computer

**Comment by rtpavlovsk21** [comment] 2016-12-21 02:05
This discussion was carried over from #2917 because the xf86EnableIOPorts issue is more likely the issue it fixes:

After reading "man intel" I discovered that both the intel driver and modesetting driver both implement common hardware acceleration parameters:
```bash
Section "Device"                                                                                                                                     
#   Identifier "Intel Graphics SNA+TearFree"                                                                         
#   Option     "AccelMethod" "sna"                                                                                                                   
#   Option     "TearFree"    "true"                                                                                                        
   Identifier "Modesetting"                                                                                                                
   Driver     "modesetting"
   Option "AccelMethod" "sna"
   Option "TearFree" "true"                                                                                                                  
EndSection     
```
These edits significantly reduce the number of artifacts and screen switching problems that i have seen. I have not observed crashes from switching, but previously modesetting was a step down from the intel driver. With the changes I don't notice a difference in performance or appearance to how crouton use to work.

I will be getting a Samsung Chromebook 3 in the next few days and will note any obvious differences (I would have liked to had another processor series to test on but this will also be a celeron).

https://www.chromebookchart.com/

**Comment by fermionic** [comment] 2016-12-21 16:49
I have an Acer Chromebook 14 (CB3-431), and I tried updating `/etc/crouton/xorg-intel-sna.conf` with the above suggestions, but I'm still getting the black (i.e. no power whatsoever) screen when I do `sudo startxfce4`. I've tried wiping the Chromebook (by exiting Developer mode, then re-entering it) and installing both the precise and trusty versions of xfce, but no matter what I do I get the ` xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)` error.

I'm on 56.0.2924.28 beta, updated on December 15. Everything had worked fine until I rebooted the computer on the 20th.

**Comment by fermionic** [comment] 2016-12-21 17:07
I tried copying the file `/etc/crouton/xorg-intel-sna.conf` over to `/usr/share/X11/xorg.conf.d/20-crouton.conf` (which didn't exist before) and that allowed me to get into XFCE

**Comment by rtpavlovsk21** [comment] 2016-12-21 17:09
@fermionic note that the config file according to your output is in 
```bash
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
```

**Comment by yannym** [comment] 2016-12-22 15:32
I had better luck using  "uxa" and the "intel" driver.
As mentioned here by "aou" https://github.com/dnschneid/crouton/issues/2923
This method allowed my XFCE environment to start, and it preserved Hardware Acceleration.

`Section "Device"`
    `Identifier "Intel Graphics SNA+TearFree"`
   `Driver     "intel"`
   `Option     "AccelMethod" "uxa"`
    `EndSection`

**Comment by rtpavlovsk21** [comment] 2016-12-22 15:38
@yannym please tell us the type of Chromebook you are using. the problem is likely graphics specific, the uxa parameter on the i915 chipset on my Acer 720p was that the desktop would partially boot (lit screen and cursor but nothing else)

**Comment by yannym** [comment] 2016-12-22 15:44
@rtpavlovsk21 I'm using a Lenovo Thinkpad 13, the "modesetting" drivers worked fine for me, it fixed the black screen issue I was having when attempting to enter the xfce environment using xorg, but I kinda needed hardware acceleration, and the "uxa" "Accel Method" works great for me, it starts xfce and has no issues I can see so far. It may be because I have Skylake hardware.

I attempted to use uxa plus modesetting but I saw now change there between sna or uxa, it was only after I reverted to the intel driver that it started to work, so I think sna might be the issue, because that's what i had configured when the black screen was occuring, "intel" + "sna." "intel" + "uxa" seemed to fix it.

**Comment by fermionic** [comment] 2016-12-22 16:15
On my Acer Chromebook 14 (CB3-431), I also found the "uxa" driver to work better. The "modesetting" one worked fine, except that it was obviously unaccelerated, so games like Minetest didn't work very well. Changing the xorg conf file to what @yannym has allowed me to boot into XFCE with hardware acceleraton--in fact, so far I've seen no difference between "uxa" and what "sna" was before the ChromeOS update

**Comment by battez** [comment] 2016-12-25 19:18
oh I am having this issue also on Acer 15 (using Chrome dev channel 57.0.2951,  -- tried xenial and trusty, it was working ok with xiwi but nothing else, just goes black and I have to force unmount. I am not clear on the changes needed to the graphics so I will wait for a update to crouton that fixes it.

**Comment by AntiochInteractiveMedia** [comment] 2016-12-26 05:42
Happy holidays to everyone who posted on this thread!  On my son's new Acer Chromebook R13, I was able to successfully setup Steam and Minecraft using Crouton and KDE thanks to the adding this file (as mentioned before) to the chroot for 'trusty':

/user/share/X11/xord-conf.d/20-crouton.conf

Section "Device"
Identifier "Intel Graphics SNA+TearFree"
Driver "intel"
Option "AccelMethod" "uxa"
EndSection

--

Only remaining issues to figure out are why the mouse is ridiculously laggy :)

**Comment by aou** [comment] 2016-12-26 06:57
@AntiochInteractiveMedia regarding the mouse, I noticed that with uxa acceleration method and unity, performance was slow and mouse would sometimes lag.  However, with xfce, performance is very snappy.

It could be due to xfce4 by default disabling compositing in the window manager. Slightly less eye candy, but much more usable.

I'm sure there's a way to disable compositing in KDE, might help.

**Comment by daldred** [comment] 2016-12-28 10:52
I can confirm that @AntiochInteractiveMedia 's file also works on an Acer R11.

**Comment by dwaindibbly** [comment] 2016-12-30 16:01
ok so the `Option "AccelMethod" "uxa"` method works

**Comment by eliot2** [comment] 2016-12-31 04:46
On Acer c720p. With the xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted) issue.

The following have not worked:
@AntiochInteractiveMedia 's fix: https://github.com/dnschneid/crouton/issues/2926#issuecomment-269165182

This did not work because the file "20-crouton.conf" isn't referenced, so changing it does nothing.
Then someone suggested "20-crouton-intel-sna-conf" which is actually just a symlink to "/etc/crouton/xorg-intel-sna.conf".

And HALLELUJAH PRAISE JESUS IT WORKED.

In other words, change 

/mnt/stateful_partition/crouton/chroots/test2/etc/crouton/xorg-intel-sna.conf 

to

```

# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# On Intel platforms with FBC enabled, in order to see anything we need to use
# the SNA driver with the TearFree option.
Section "Device"
   #Identifier "Intel Graphics SNA+TearFree"
   #Driver     "intel"
   # Option     "AccelMethod" "uxa"
   # Option     "TearFree"    "true"
   Identifier "Modesetting"
   Driver "modesetting"
   Option "AccelMethod" "sna"
   Option "TearFree" "true"
EndSection
```

Keep in mind, depending on your system, it might be /mnt/stateful_partition/crouton/chroots/test2/usr/share/X11/xorg.conf.d/20-crouton.conf
That you have to modify, OR
/mnt/stateful_partition/crouton/chroots/test2/usr/share/X11/xorg.conf.d/20-crouton-intel-sna.conf 
but that last file is actually just a symbolic link to
/mnt/stateful_partition/crouton/chroots/test2/etc/crouton/xorg-intel-sna.conf

**Comment by rtpavlovsk21** [comment] 2017-01-03 15:28
The issue as I currently see this:
**Intel Celeron Chromebooks** (tested Acer 720p/Samsung Chromebook 3/Acer Chromebook 14) work (probably without acceleration) with changes in comment [#2926](https://github.com/dnschneid/crouton/issues/2926#issuecomment-268414152). See [#2917](https://github.com/dnschneid/crouton/issues/2917#issuecomment-267411158) for a longer discussion. 
**ARM Chromebooks** (tested by @AntiochInteractiveMedia on CB Acer R13, see [#2926 comment](https://github.com/dnschneid/crouton/issues/2926#issuecomment-269165182) )

There are exceptions listed to this (as I read them in this thread). A partial list of exceptions that need to be investigated further:
Acer CB R11 [(1 instance)](https://github.com/dnschneid/crouton/issues/2926#issuecomment-269460712)
Toshiba CB 2 [(1 instance)](https://github.com/dnschneid/crouton/issues/2917#issuecomment-267742510) - This case has an ambiguity between i3/Celeron
Asus C300 [(1 instance)](https://github.com/dnschneid/crouton/issues/2926#issuecomment-269787889) - Ambiguity between Atom/Celeron and probably uses [#2926 comment](https://github.com/dnschneid/crouton/issues/2926#issuecomment-269165182) as the fix.

**Also a great suggestion for** [**Celeron HW Acceleration**](https://github.com/dnschneid/crouton/issues/2917#issuecomment-269906678) from @pmarkkula. I have tested this on both Acer 720p and Samsung CB 3.

**Comment by gardwired** [comment] 2017-01-24 07:24
can confirm that above /user/shrare/X11/xorg.conf.d/20-crouton.conf  works on new intel asus c302 with core M3.  running chrome 56 dev channel.  -r jessie -t xfce.  i at first did jessie x11 to try to get mate but kept failing.  may try again.    just got it today so crouton is fresh.

was having same error black screen can't connect to xserver/no screens  as well as /dev/fb0 not existing.  i don't have /dev/dri/card1 so that hack wasn't going to work.  this at least gets me going.  

still getting permission errors on setting DRM interface /dev/dri/card0

as others have said, mouse very slow.  

really appreciate the efforts here.  thanks!  let me know if you'd like to see logs or something else.

**Comment by JimAmuro** [comment] 2017-01-25 15:31
Here is my case: toshiba cb2, i3, trusty+xfce, latest chrome os 57
For `xiwi`: no tweaks, everything goes well.
For `xorg`:
* `modesetting` causes my cb to crash and restart instantly after `sudo startxfce4`
* `uxa` works but typing becomes extremely laggy, other things seem OK.

Hope this can be fixed soon... Thanks!

**Comment by david-varela** [comment] 2017-02-12 07:21
I was having the same issue running jessie+xmonad on my Asus C300. The solution provided by @AntiochInteractiveMedia worked for me as well. Pretty sure that the last chromebook update is what caused things to break. Just commenting in case this information is useful to anyone, thanks!

**Comment by nemo-nullius** [comment] 2017-02-15 12:38
Has any had a same problem as mine?
After upgrading to Chrome OS 56.0.2924.87(64-bit) today, I could not get into i3wm or xfce4 + Ubuntu 14.04 either.  Black screen. I searched on the internet for a long time for the solution, and I found this issue. With the help from @eliot2 , I changed "`sna`" to "`uxa`" in `/mnt/stateful_partition/crouton/chroots/test2/etc/crouton/xorg-intel-sna.conf`. After that, I was able to get into i3wm and xfce4 and lxde. But there turned out to be another problem: **# typing became too laggy**, especially for terminals and for those Qt-programs! (Btw, gnome (including mate) does not have such a problem. Either with the option "sna" or "uxa", gnome works very well, and with "uxa", there is no problem with typing.)

I have tried many times, including changing "uxa" to "glamor", and "TearFree" to "PageFlip", but in vain. Finally, I tried to turn off acceleration to see what the result would be (for I thought that as typing was too laggy with the acceleration option on, how slow it would be if I turned it off). However, after I turned that option off, everything got fixed! It was quite unbelievable! Is it because i3wm and xfce4 do not support acceleration very well?

Here is my configuration file:
```
Section "Device"
    Identifier "Intel Graphics SNA+TearFree"
    Driver "intel"
    Option "AccelMethod" "uxa" # used to be "sna"
    Option "TearFree" "true"
    Option "NoAccel" "true" # turn off the acceleration option. For detail, see man intel.
EndSection

```

I still have another question. As I could get into i3wm and xfce4 with no problem now, why is there still such a line "xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)" in the output? Thanks!

**Comment by nemo-nullius** [comment] 2017-02-15 12:43
I have had a same problem with yours, and I have just fixed it by adding `Option "NoAccel" "true"` in `xorg-intel-sna.conf` to turn off acceleration. It works on my cb (toshiba 2015, ubuntu 14.04+i3wm/xfce). You could try it.

**Comment by JimAmuro** [comment] 2017-02-15 22:10
@nemo-nullius Thanks! But typing is still laggy after "NoAccel" "true" for me...

**Comment by nemo-nullius** [comment] 2017-02-17 00:24
@JimAmuro It is said on #2923 that update of crouton could fix the problem now. I tried, and it really works! Though days ago it still did not work....

**Comment by JimAmuro** [comment] 2017-02-17 15:54
@nemo-nullius Thank you! The update works like a charm!

**Comment by DennisLfromGA** [comment] 2017-02-17 17:05
Closing. Please update your chroot and try again, re-open if this issue is still a concern.

**Closed by DennisLfromGA** 2017-02-17 17:05 UTC

**Comment by peepo** [comment] 2017-08-26 15:36
please see related issue: #3368
tried:
sudo sh ~/Downloads/crouton -u -n xenial
result unchanged.

**Comment by dwaindibbly** [comment] 2017-08-31 11:40
everybody here focus on #3368 now, it's not related but it's a problem i've now got. and it does this:
![screenshot 2017-08-31 at 12 37 02](https://user-images.githubusercontent.com/16360233/29921451-8421f030-8e49-11e7-981b-87f681ff28a7.png)
