### ISSUE TITLE
Can't enter chroot. Powerwashed. Updated chroot. Getting 404s.

### ISSUE THREAD

**Issue by Anderfreeb** [dnschneid/crouton#1696] opened 2015-04-30 17:55 UTC
Steps I followed: I powerwashed my Pixel 2 LS. Downloaded crouton installer from top of this Github. Ran `sudo sh -e ~/Downloads/crouton -t touch,xfce`. It did its thing and then finished with:
````
it http://archive.ubuntu.com precise-updates/main Translation-en 
Hit http://archive.ubuntu.com precise-updates/multiverse Translation-en
Hit http://archive.ubuntu.com precise-updates/restricted Translation-en
Hit http://archive.ubuntu.com precise-updates/universe Translation-en
Hit http://archive.ubuntu.com precise-security/main Translation-en
Hit http://archive.ubuntu.com precise-security/multiverse Translation-en
Hit http://archive.ubuntu.com precise-security/restricted Translation-en
Hit http://archive.ubuntu.com precise-security/universe Translation-en
Err http://ppa.launchpad.net precise/main Sources                 
  404  Not Found
Err http://ppa.launchpad.net precise/main amd64 Packages
  404  Not Found
Err http://ppa.launchpad.net precise/main i386 Packages
  404  Not Found
Ign http://ppa.launchpad.net precise/main Translation-en
W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Failed to complete chroot setup.
Unmounting /usr/local/chroots/precise...it http://archive.ubuntu.com precise-updates/main Translation-en 
Hit http://archive.ubuntu.com precise-updates/multiverse Translation-en
Hit http://archive.ubuntu.com precise-updates/restricted Translation-en
Hit http://archive.ubuntu.com precise-updates/universe Translation-en
Hit http://archive.ubuntu.com precise-security/main Translation-en
Hit http://archive.ubuntu.com precise-security/multiverse Translation-en
Hit http://archive.ubuntu.com precise-security/restricted Translation-en
Hit http://archive.ubuntu.com precise-security/universe Translation-en
Err http://ppa.launchpad.net precise/main Sources                 
  404  Not Found
Err http://ppa.launchpad.net precise/main amd64 Packages
  404  Not Found
Err http://ppa.launchpad.net precise/main i386 Packages
  404  Not Found
Ign http://ppa.launchpad.net precise/main Translation-en
W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Failed to complete chroot setup.
Unmounting /usr/local/chroots/precise...
````

I updated chroot with `sudo sh -e ~/Downloads/crouton -u -n precise` and get the following error:
````
Hit http://archive.ubuntu.com precise-security/restricted Translation-en   
Hit http://archive.ubuntu.com precise-security/universe Translation-en
Fetched 4759 kB in 4s (1039 kB/s)                    
W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
````
When I try to do `sudo enter-chroot` it asks me if I want to finish setting up the chroot, I say yes and get:
````
Hit http://archive.ubuntu.com precise-security/restricted Translation-en                                                                   
Hit http://archive.ubuntu.com precise-security/universe Translation-en                                                                     
Fetched 4759 kB in 9s (525 kB/s)                                                                                                           
W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in precise
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
````

After that whenever I `sudo enter-chroot` I get 
````
Entering /mnt/stateful_partition/crouton/chroots/precise...
UID 1000 not found in precise
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
````

Seems like the links to the ppa are bad. Not sure what to do

**Comment by dnschneid** [comment] 2015-04-30 18:00
Uh oh, looks like the xfce target is now broken on precise ([the ppa](https://launchpad.net/~xubuntu-dev/+archive/ubuntu/ppa) doesn't have any precise builds at the moment).

**Comment by hidden0** [comment] 2015-04-30 18:20
I've been encountering this problem as well.  Attempts at resolution have been numerous:

- Deleted the ppa entry in /etc/apt/sources.list.d/xfce-4.10.list
- Repeated above while pausing crouton script with ctrl+z to remove inserted .list file
- Tried updating the ppa to point to 4.12 instead of 4.10

All of these cases result in the sources being automatically updated to include the 4.10 ppa for xfce.  So I wasn't able to get a work around on this one.

Thoughts?

**Comment by rrdrummer** [comment] 2015-04-30 18:22
Having similar issues. Commenting to follow thread in hopes something comes up or changes.

**Comment by tedm** [comment] 2015-04-30 18:31
I updated this morning after the stable channel upgraded (still no freon), and xfce on precise on the ARM with xiwi isn't working, but I didn't notice the errors above. enter-chroot is working.

chronos@localhost / $ sudo edit-chroot -al
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20150428153647~master:6ae56c3d
release: precise
architecture: armhf
xmethod: xiwi
targets: xfce,e17,xiwi,xephyr
host: version 6812.83.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Apr 27 08:39:10 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: no
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.
chronos@localhost / $ 

Crouton integration block C shows the attemps to connect, but selecting the chroot is just a blank window with error.

**Comment by dnschneid** [comment] 2015-04-30 18:37
ARM doesn't use the PPA.

**Comment by dnschneid** [comment] 2015-04-30 18:42
OK, crouton's been updated to let apt-get update fail (finally), which should also eliminate all PPA complaints that people have.  This bug still should remain open, because we need to remove that PPA from the xfce target.

**Comment by tedm** [comment] 2015-04-30 18:43
yup, just tried startxfce4 again and it does work, the first attempts often don't connect though, but a reboot usually lets it connect quickly. So xfce is working on the stable channel with the update this morning.

e17 comes up, but after a minute it seg v'd, and the cursor dragged a little, the selecting power off in the e17 menu, which I expected to power off the e17 chroot, shut down the chromebook! How can it do that??

**Comment by rrdrummer** [comment] 2015-04-30 18:48
I'm still getting this:

http://imgur.com/wGHYlz4

Can post the full text if you need me to.

**Comment by dnschneid** [comment] 2015-04-30 18:49
You need to update your chroot.

**Comment by rrdrummer** [comment] 2015-04-30 18:53
I'm a bit of a noob... so please bear with me. I believe you mean I need to do this:

sudo sh -e ~/Downloads/crouton -u -n trusty

Entered that. Result: 

http://imgur.com/AGg7Vay

If that was not the correct thing to update, please let me know how to proceed. Will gladly do what I'm told :)

**Comment by Anderfreeb** [comment] 2015-04-30 19:27
I just powerwashed, downloaded crouton, ran crouton, updated crouton, and tried to enter-chroot again. I'm getting all the same errors in my original post. 404 complaints about PPA and ultimately the "UID1000 not found in precise" :/

**Comment by dnschneid** [comment] 2015-04-30 19:33
Sorry, I didn't actually change all the apt-get updates...  Try again now.

**Comment by rrdrummer** [comment] 2015-04-30 19:38
Just tried.... this is what I believe is the critical part of the failure. Happy to post anything I need to to help you help us.

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Breaks: libc6-dev:i386 (!= 2.19-0ubuntu6.4) but 2.19-0ubuntu6 is to be installed
 libc6-dev:i386 : Depends: libc6:i386 (= 2.19-0ubuntu6) but 2.19-0ubuntu6.4 is to be installed
                  Depends: libc-dev-bin:i386 (= 2.19-0ubuntu6)
                  Depends: linux-libc-dev:i386 but it is not going to be installed
                  Breaks: libc6-dev (!= 2.19-0ubuntu6) but 2.19-0ubuntu6.4 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by hidden0** [comment] 2015-04-30 19:41
@dnschneid Your changes have worked on my end. The command:
```
sudo sh -e ~/Downloads/crouton -n precise -u
```
now works as expected. The 404's are indeed still present.

Thank you for your good work!

**Comment by dnschneid** [comment] 2015-04-30 19:43
Awesome.  We need to figure out what to do about xfce on precise, now that it's stuck with the really old version...

@rrdrummer your issue is different, and you already filed #1694.

**Comment by hidden0** [comment] 2015-04-30 19:45
Can xfce 4.12 be used?  I'm not entirely educated on the situation.

**Comment by Anderfreeb** [comment] 2015-04-30 19:46
I've updated and I'm still getting the same errors. After updating and trying sudo enter-chroot I get a "chroot may not be fully set up...yadayada" I enter "Y," it gives me some more 404s from my original poast and then I'm back at "UID1000 not found in precise"

So same issues as the start still.

Would a powerwash help at all? I'm not really sure if I've needed to be doing that. Also, thank you for your incredibly quick replies and work on this.

**Comment by dnschneid** [comment] 2015-04-30 19:49
@hidden0 it doesn't look like that PPA is building 4.12 for precise, so, no.

@Anderfreeb delete the crouton installer and re-download it.  I think you're still using an old (cached) version.  Powerwash isn't necessary.

**Comment by Anderfreeb** [comment] 2015-04-30 19:53
It worked! Thanks so much

**Comment by Alfriadox** [comment] 2015-06-09 15:38
If this has worked can the issue be closed?

**Comment by rrdrummer** [comment] 2015-06-09 15:47
Yes please

**Comment by dnschneid** [comment] 2015-06-10 21:38
Wait no, this isn't fixed.  We need to remove the ppa stuff from the xfce target.

**Comment by liapman** [comment] 2015-06-20 08:09
I'm experiencing the same issues. Following this thread for a fix.
Thanks for all the great work you're doing!

**Comment by SmallStrayFox** [comment] 2015-06-28 01:22
i'm new to crouton and i'm getting 404 on package sources, similar to above, so i can't install anything in xfce. is there a fix for this? i read through this thread but feel none the wiser.

cheers

**Comment by jakman** [comment] 2015-07-12 21:58
I just installed v12.04 with xfce a few days ago...along with a chroot. I'm working thru various issues including getting apt-get to work properly and removing duplicate entries found in my sources.list.

I am having this issue as well. Also, the issue below where  

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/source/Sources  404  Not Found

Not sure if the two are related.

**Comment by dnschneid** [comment] 2015-08-01 20:47
Still haven't removed the bad PPA from the xfce target, unfortunately.  It's easy to do if someone wants to take a stab at it...

**Comment by dnschneid** [comment] 2015-08-01 20:47
omg wrong button

**Comment by DennisLfromGA** [comment] 2015-08-01 20:55
> Still haven't removed the bad PPA from the xfce target, unfortunately. It's easy to do if someone wants to take a stab at it...

That might possibly be a pie, I take a look...

> omg wrong button

I hate when that happens ;)

**Comment by DennisLfromGA** [comment] 2015-08-01 21:51
@dnschneid - If [this](https://github.com/dnschneid/crouton/compare/master...DennisLfromGA:patch-3) is more or less what you had in mind, I'll submit the PR.

**Comment by dnschneid** [comment] 2015-08-11 18:51
Merged!  Thanks!

**Closed by dnschneid** 2015-08-11 18:51 UTC
Labels: bug, pie

**Comment by thereallyrealbobbyfischer** [comment] 2016-08-20 04:19
Hey super noob:

I have had success running precise, but now I am trying to run kali-rolling and whezzy to see what they are like and I am running into the same UID 1000 not found in kali-rolling


Here is the log from the update:
sudo sh -e ~/Downloads/crouton -n kali-rolling  -u 
____________________________________________________

sudo sh -e ~/Downloads/crouton -u -n kali-rolling
/usr/local/chroots/kali-rolling already exists; updating it...
WARNING: USB booting is enabled; consider disabling it.
WARNING: Legacy booting is enabled; consider disabling it.
WARNING: Signed boot verification is disabled; consider enabling it.
You can use the following command: sudo crossystem dev_boot_usb=0 dev_boot_legacy=0 dev_boot_signed_only=1
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
Hit:1 http://mirror.pwnieexpress.com/kali kali-rolling InRelease
Reading package lists... Done
Ensuring system is up-to-date...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.3~pre3).
ca-certificates is already the newest version (20160104).
sudo is already the newest version (1.8.17p1-2).
wget is already the newest version (1.18-2+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Syncing timezone...
Installing target audio...
Fetching CRAS (branch 0dac4acd30b69f02498ca4696f5660800ec848be)...
--2016-08-20 00:09:33--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/0dac4acd30b69f02498ca4696f5660800ec848be.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 173.194.204.82, 2607:f8b0:400d:c0c::52
Connecting to chromium.googlesource.com (chromium.googlesource.com)|173.194.204.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '/tmp/crouton-cras.67FoXg/adhd.tar.gz'

     0K .......... .......... .......... .......... ..........  546K
    50K .......... .......... .......... .......... .......... 1.28M
   100K .......... .......... .......... .......... .......... 1.34M
   150K .......... .......... .......... .......... .......... 1.80M
   200K .......... .......... .......... .......... .......... 1.73M
   250K .......... .......... .......... .......... .......... 3.20M
   300K .......... .......... .......... .......... .......... 1.71M
   350K .......... .......... .......... .......... .......... 1.57M
   400K .......... .......... .......... .......... .......... 1.63M
   450K .......... .......... .......... .......... .......... 1.55M
   500K .......... .......... .......... .......... .....      1.51M=0.4s

2016-08-20 00:09:34 (1.38 MB/s) - '/tmp/crouton-cras.67FoXg/adhd.tar.gz' saved [558146]

Reading package lists... Done
Building dependency tree       
Reading state information... Done
alsa-utils is already the newest version (1.1.1-1).
libasound2:i386 is already the newest version (1.1.2-1).
libspeexdsp1:i386 is already the newest version (1.2~rc1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree        
Reading state information... Done
gcc is already the newest version (4:6.1.1-1).
gcc-multilib is already the newest version (4:6.1.1-1).
pkg-config is already the newest version (0.29-4).
libc6-dev:i386 is already the newest version (2.23-4).
libspeexdsp-dev:i386 is already the newest version (1.2~rc1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libasound2-dev:i386 is already the newest version (1.1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
patch is already the newest version (2.7.5-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling CRAS (i386)...
Installing CRAS...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
alsa-utils is already the newest version (1.1.1-1).
libasound2 is already the newest version (1.1.2-1).
libspeexdsp1 is already the newest version (1.2~rc1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:6.1.1-1).
libc6-dev is already the newest version (2.23-4).
libspeexdsp-dev is already the newest version (1.2~rc1.2-1).
pkg-config is already the newest version (0.29-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree        
Reading state information... Done
libasound2-dev is already the newest version (1.1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
patch is already the newest version (2.7.5-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling CRAS (native)...
Installing CRAS...
Installing target xorg...
Canceled hold on xserver-xorg-video-intel.
Installing dependencies for /usr/local/lib/croutonfreon.so...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:6.1.1-1).
libc6-dev is already the newest version (2.23-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling /usr/local/lib/croutonfreon.so...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'xserver-xorg-core' instead of 'xserver-xorg-video-modesetting'
Package 'xserver-xorg-input-vmmouse' is not installed, so not removed
Package 'xserver-xorg-video-all' is not installed, so not removed
xorg is already the newest version (1:7.7+16).
xserver-xorg-core is already the newest version (2:1.18.4-1).
xserver-xorg-video-intel is already the newest version (2:2.99.917+git20160706-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'xserver-xorg-video-fbdev' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
sed: can't read /etc/X11/Xwrapper.config: No such file or directory
xserver-xorg-video-intel set on hold.
Installing dependencies for /usr/local/bin/croutonwmtools...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:6.1.1-1).
libc6-dev is already the newest version (2.23-4).
libx11-dev is already the newest version (2:1.6.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling /usr/local/bin/croutonwmtools...
Installing dependencies for /usr/local/bin/croutonxi2event...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:6.1.1-1).
libc6-dev is already the newest version (2.23-4).
libx11-dev is already the newest version (2:1.6.3-1).
libxi-dev is already the newest version (2:1.7.6-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling /usr/local/bin/croutonxi2event...
Reading package lists... Done
Building dependency tree        
Reading state information... Done
dbus is already the newest version (1.10.8-1).
xdg-utils is already the newest version (1.1.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree        
Reading state information... Done
dmz-cursor-theme is already the newest version (0.4.4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bsdmainutils is already the newest version (9.0.10).
kbd is already the newest version (2.0.3-2).
xautomation is already the newest version (1.09-1+b1).
xbindkeys is already the newest version (1.8.6-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing target x11...
Installing target gtk-extra...
ar: creating /tmp/crouton.DSKe7m/crouton-network-manager.deb
(Reading database ... 20846 files and directories currently installed.)
Preparing to unpack .../crouton-network-manager.deb ...
Unpacking crouton-network-manager (0) over (0) ...
Setting up crouton-network-manager (0) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package netsurf-gtk
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

__________________________________________________________________

And here is the log from:
sudo startxfce4 -n kali-rolling

sudo startxfce4 -n kali-rolling
Password: 
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] y
Preparing chroot environment...
Installing target core...
Preparing environment...
Preparing software sources...
Hit:1 http://archive.linux.duke.edu/kalilinux/kali kali-rolling InRelease
Reading package lists... Done
Ensuring system is up-to-date...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.3~pre3).
ca-certificates is already the newest version (20160104).
sudo is already the newest version (1.8.17p1-2).
wget is already the newest version (1.18-2+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Syncing timezone...
Installing target audio...
Fetching CRAS (branch 0dac4acd30b69f02498ca4696f5660800ec848be)...
--2016-08-20 00:15:14--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/0dac4acd30b69f02498ca4696f5660800ec848be.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 173.194.219.82, 2607:f8b0:4002:c08::52
Connecting to chromium.googlesource.com (chromium.googlesource.com)|173.194.219.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '/tmp/crouton-cras.t9Ixfe/adhd.tar.gz'

     0K .......... .......... .......... .......... ..........  474K
    50K .......... .......... .......... .......... .......... 1.17M
   100K .......... .......... .......... .......... .......... 1.33M
   150K .......... .......... .......... .......... .......... 3.08M
   200K .......... .......... .......... .......... .......... 1.98M
   250K .......... .......... .......... .......... .......... 1.28M
   300K .......... .......... .......... .......... .......... 1.01M
   350K .......... .......... .......... .......... ..........  514K
   400K .......... .......... .......... .......... .......... 4.37M
   450K .......... .......... .......... .......... .......... 5.72M
   500K .......... .......... .......... .......... .....      6.67M=0.4s

2016-08-20 00:15:15 (1.23 MB/s) - '/tmp/crouton-cras.t9Ixfe/adhd.tar.gz' saved [558127]

Reading package lists... Done
Building dependency tree       
Reading state information... Done
alsa-utils is already the newest version (1.1.1-1).
libasound2:i386 is already the newest version (1.1.2-1).
libspeexdsp1:i386 is already the newest version (1.2~rc1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:6.1.1-1).
gcc-multilib is already the newest version (4:6.1.1-1).
pkg-config is already the newest version (0.29-4).
libc6-dev:i386 is already the newest version (2.23-4).
libspeexdsp-dev:i386 is already the newest version (1.2~rc1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree        
Reading state information... Done
libasound2-dev:i386 is already the newest version (1.1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
patch is already the newest version (2.7.5-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling CRAS (i386)...
Installing CRAS...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
alsa-utils is already the newest version (1.1.1-1).
libasound2 is already the newest version (1.1.2-1).
libspeexdsp1 is already the newest version (1.2~rc1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:6.1.1-1).
libc6-dev is already the newest version (2.23-4).
libspeexdsp-dev is already the newest version (1.2~rc1.2-1).
pkg-config is already the newest version (0.29-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libasound2-dev is already the newest version (1.1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
patch is already the newest version (2.7.5-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling CRAS (native)...
Installing CRAS...
Installing target xorg...
Canceled hold on xserver-xorg-video-intel.
Installing dependencies for /usr/local/lib/croutonfreon.so...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:6.1.1-1).
libc6-dev is already the newest version (2.23-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling /usr/local/lib/croutonfreon.so...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'xserver-xorg-core' instead of 'xserver-xorg-video-modesetting'
Package 'xserver-xorg-input-vmmouse' is not installed, so not removed
Package 'xserver-xorg-video-all' is not installed, so not removed
xorg is already the newest version (1:7.7+16).
xserver-xorg-core is already the newest version (2:1.18.4-1).
xserver-xorg-video-intel is already the newest version (2:2.99.917+git20160706-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'xserver-xorg-video-fbdev' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
sed: can't read /etc/X11/Xwrapper.config: No such file or directory
xserver-xorg-video-intel set on hold.
Installing dependencies for /usr/local/bin/croutonwmtools...
Reading package lists... Done
Building dependency tree        
Reading state information... Done
gcc is already the newest version (4:6.1.1-1).
libc6-dev is already the newest version (2.23-4).
libx11-dev is already the newest version (2:1.6.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling /usr/local/bin/croutonwmtools...
Installing dependencies for /usr/local/bin/croutonxi2event...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:6.1.1-1).
libc6-dev is already the newest version (2.23-4).
libx11-dev is already the newest version (2:1.6.3-1).
libxi-dev is already the newest version (2:1.7.6-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling /usr/local/bin/croutonxi2event...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dbus is already the newest version (1.10.8-1).
xdg-utils is already the newest version (1.1.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dmz-cursor-theme is already the newest version (0.4.4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree        
Reading state information... Done
bsdmainutils is already the newest version (9.0.10).
kbd is already the newest version (2.0.3-2).
xautomation is already the newest version (1.09-1+b1).
xbindkeys is already the newest version (1.8.6-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing target x11...
Installing target gtk-extra...
ar: creating /tmp/crouton.fz4AmG/crouton-network-manager.deb
(Reading database ... 20846 files and directories currently installed.)
Preparing to unpack .../crouton-network-manager.deb ...
Unpacking crouton-network-manager (0) over (0) ...
Setting up crouton-network-manager (0) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package netsurf-gtk
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in kali-rolling
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by thereallyrealbobbyfischer** [comment] 2016-08-20 04:20
ps you're the man

**Comment by DennisLfromGA** [comment] 2016-08-20 19:04
@thereallyrealbobbyfischer - p.s. dup of https://github.com/dnschneid/crouton/issues/2513, see https://github.com/dnschneid/crouton/issues/2513#issuecomment-230125641 (not related to _this_ issue).
