### ISSUE TITLE
ChromeOS v47 + Crouton = Bugs

### ISSUE THREAD

**Issue by Fatal1ty93RUS** [dnschneid/crouton#2289] opened 2015-12-13 18:28 UTC
So, yesterday the charging port on my Asus C300 Chromebook broke completely so I had to repair it. 
After repairing it in the service center today, the employees reset the laptop and formatted the storage, as well as disabling the developer mode

So as soon as I got home, I immediately reenabled the developer mode, downloaded the Crouton script and proceeded to install Ubuntu for Anddoid messing purposes and such

The result? I have faced a lot of bugs

Attempt #1: Installing Ubuntu Trusty (v13)
Targets: Chrome and Unity Desktop
Result: my Touchpad and the Keyboard got completely locked out, therefore I couldn't proceed with the installation

I tried reinstalling Ubuntu three more times, adding core, keyboard and xiwi/xorg targets - same result, Touchpad and Keyboard locked out in ChromeOS -> reboot, delete chroot

Attempt #2: Debian Sid
Installation failed in the middle of the process

Debian Stretch have the same result
Reboot - delete chroot...

Attempt #3 Debian Jessie
Installation failed due to chroot not Installing completely. Tried executing the fix missing command to maybe finish the installation

Installation result is the same, entering the chroot results in not being able to mount it at all

Also my Touchpad gets locked out 
Debian Willy - same thing
Reboot - delete chroot....

Attempt #4: Ubuntu Trusty, again
Targets used: unity-desktop

Installation failed, Chrome stopped responding and crashed, had to reboot as I was unable to do anything from the terminal
Delete chroot....

So at this point I am pretty much unable to install any kind of Linux distribution via Crouton and I'm unsure if Chrubuntu or any other method supports my device at this point

Question - how did this happen and what did I do wrong when attempting to install the previous chroots? Is it the incompatibility issue with the newest ChromeOS? 

Notice - I upgraded to v47 two days ago and was able to launch Ubuntu just yesterday without problems

**Comment by dragonballz2k** [comment] 2015-12-13 21:02
I would try using an external keyboard, and mouse I think that is a bug with some chromebooks. It seems it messes up they keyboard while it installing. it should be fine after reboot and completed the installation.

**Comment by dragonballz2k** [comment] 2015-12-13 21:03
Here is the bug I am talking about https://github.com/dnschneid/crouton/issues/1994

**Comment by Fatal1ty93RUS** [comment] 2015-12-13 21:07
@dragonballz2k the weirdest part is that I NEVER had such an issue before, and I installed Linux via Crouton like 10 or so times (experimented with different distros)

**Comment by dragonballz2k** [comment] 2015-12-13 21:10
@Fatal1ty93RUS it's weird issue that seems to affect certain chromebooks. You might able to use virtual keyboard to bypass this issues also.

**Comment by Fatal1ty93RUS** [comment] 2015-12-13 21:15
but how come I was only affected by this on v47 and never before?

**Comment by dragonballz2k** [comment] 2015-12-13 21:17
I wish I knew sorry :( . I am a not a dev

**Comment by darcyparker** [comment] 2015-12-14 21:39
Is this the same as #2255 ?

**Comment by dragonballz2k** [comment] 2015-12-15 00:39
@darcyparker yep it's a very weird issue.

**Comment by dragonballz2k** [comment] 2015-12-15 00:40
@Fatal1ty93RUS I was just wondering did you ever get yours installed?

**Comment by drinkcat** [comment] 2016-10-11 19:25
Most likely dupe of #2042.

**Comment by drinkcat** [comment] 2016-10-11 19:25
Err, #1994.

**Closed by drinkcat** 2016-10-11 19:25 UTC
