### ISSUE TITLE
Chroot fails to start and screen stays black before unmounting

### ISSUE THREAD

**Issue by mkbarber** [dnschneid/crouton#2962] opened 2016-12-20 16:56 UTC
```
Please paste the output of the following command here: sudo edit-chroot -all
```
```
chronos@localhost ~/Downloads $ sudo edit-chroot -all
Password: 
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9000.29.0 (Official Build) beta-channel gandof 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Dec 14 21:56:15 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost ~/Downloads $ 
```
#### Please describe your issue:
When trying to enter my chroot the screen goes black and never shows the desktop. When I hit enter twice, the session terminates and unmounts the chroot. See below for the output of `sudo startxfce4` command.

I have tried updating my chroot with `sudo sh ~/Downloads/crouton -n trusty -u`
See output below.

I have tried deleting my chroot and doing a clean install.

At this point I'm beyond my expertise. Any help would be welcome.

#### If known, describe the steps to reproduce the issue:

I think this has something to do with the following issues when I try to enter the chroot
```
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
```

Note - I did recently update my chrome os. It is on the beta branch and was working before the most recent update.

[CroutonBlackScreenIssue.txt](https://github.com/dnschneid/crouton/files/664278/CroutonBlackScreenIssue.txt)

**Comment by DennisLfromGA** [comment] 2016-12-20 17:43
Seems to be a duplicate of: 

chroots will no longer boot to gui after updating chrome OS to version 56.0.2924.9 dev (64-bit) #2917

Please track there.

**Closed by DennisLfromGA** 2016-12-20 17:43 UTC

**Comment by eliot2** [comment] 2017-01-01 16:03
https://github.com/dnschneid/crouton/issues/2978#issuecomment-269849365
