### ISSUE TITLE
Having trouble downloading kali linux on chromebook

### ISSUE THREAD

**Issue by kenzlub** [dnschneid/crouton#3949] opened 2018-11-26 18:27 UTC
Hello, so I've downloaded multiple Linux distros onto my Chromebook before but i have never encountered any issues like this. so i typed 

sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce

and everything was normal until the downloads stopped, i typed 
sudo startxfce4
and i was met with the issue 

UID 1000 not found in kali-rolling

Can anyone help?

**Comment by DennisLfromGA** [comment] 2018-11-27 15:04
This is a duplicate of the yet unresolve issue #3930, please see https://github.com/dnschneid/crouton/issues/3930#issuecomment-437167573 for more details.

-**DennisLfromGA**

**Closed by DennisLfromGA** 2018-11-27 15:04 UTC
