### ISSUE TITLE
Install fails with chroot: failed to run command '/prepare.sh': No such file or directory

### ISSUE THREAD

**Issue by Talor-A** [dnschneid/crouton#3181] opened 2017-03-30 07:15 UTC
here's the output of `edit-chroot -all` (note: I already have a chroot, `budgie` installed and I'm trying to create a second one):
```
➜  Downloads sudo edit-chroot -all
name: budgie
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/budgie...
crouton: version 1-20161129162558~master:5f2f11f9
release: xenial
architecture: amd64
xmethod: xorg
targets: touch,keyboard,xorg,xiwi,x11,extension
host: version 9334.18.0 (Official Build) beta-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Mar 21 22:10:39 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/budgie...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
chroot: failed to run command '/usr/local/bin/croutonversion': No such file or directory
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:

```
➜  Downloads sudo sh ./crouton -t gnome,keyboard,extension,xorg,touch -n gnome
Installing xenial-amd64 chroot to /usr/local/chroots/gnome
Downloading latest debootstrap...
Download from Debian gitweb failed. Trying latest release...
2017-03-29 23:47:50 URL:http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/ [7115/7115] -> "-" [1]
Downloading debootstrap version 1.0.89...
2017-03-29 23:47:50 URL:http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.89.tar.gz [69020/69020] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease 
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Chosen extractor for .deb packages: ar
E: Unknown compression type for  in /tmp/crouton.Utz/xenial-amd64/
Moving bootstrap files into the chroot...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startgnome into the host...
Installing crouton-noroot into the chroot...
Installing startgnome into the chroot...
Installing gnome-session-wrapper into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
chroot: failed to run command '/prepare.sh': No such file or directory
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/gnome...
```

#### If known, describe the steps to reproduce the issue:

- download crouton file
-  run sudo sh ~/Downloads/crouton -t gnome

**Comment by Talor-A** [comment] 2017-04-09 22:17
Update: this happens when using `-t x11` as well, and there is a file `prepare.sh` in the root directory of the new chroot.

**Comment by Leron4551** [comment] 2017-04-16 17:59
I have the same issue, I"ve tried installing gnome and I've tried with just core and cli-extra, but it doesn't get past `chroot: failed to run command '/prepare.sh': No such file or directory`

**Comment by zhangaa** [comment] 2017-04-17 02:57
Some issue here. I tried to install debian stretch, kali-rolling, ubuntu xenial with kde, gnome, xfce, and x11 only. Always terminated by the same issue about prepare.sh cannot be found, while I can see it in the chroot....

**Comment by divx118** [comment] 2017-04-17 06:54
Tried to replicate the issue with `sudo sh ~/Downloads/crouton -r xenial -t touch,keyboard,xorg,xiwi,x11,extension -n x` However it completes with no errors. It looks to me that you encountered a corrupted download see log @Talor-A  `E: Unknown compression type for  in /tmp/crouton.Utz/xenial-amd64/` Try again, or try another mirror with the `-m` flag on crouton.

**Comment by Talor-A** [comment] 2017-04-17 07:11
@divx118 can you suggest a mirror for ubuntu xenial amd64 (with gnome, if that's relevant) ? never had to use the `-m` flag before, and there's nothing in the wiki about it. thanks.

**Comment by divx118** [comment] 2017-04-17 07:39
Here is the list of ubuntu mirrors https://launchpad.net/ubuntu/+archivemirrors Just use the http link on the right. (right click on http and select copy link address). 
For example:
```
sudo sh ~/Downloads/crouton -r xenial -t touch,keyboard,xorg,xiwi,x11,extension -n x -m https://ftp.tudelft.nl/archive.ubuntu.com/
```
This is one from a university in the Netherlands. It has always been solid and up to date for me.

**Comment by Talor-A** [comment] 2017-04-17 07:52
@divx118 just tried it and got the same error , `E: Unknown compression type for  in /tmp/crouton.jsl/xenial-amd64/`.

**Comment by Talor-A** [comment] 2017-04-17 07:54
also in case its relevant I'm on an acer c720p running v58 beta

**Comment by divx118** [comment] 2017-04-17 08:03
@Talor-A Just to be sure, do you have enough room left on your device? Well Acer C720p is also amd64 same as my acer chromebook for work. Only difference is that I am on dev channel v59

**Comment by Talor-A** [comment] 2017-04-17 08:24
@divx118 
![screenshot 2017-04-17 at 1 24 21 am](https://cloud.githubusercontent.com/assets/11509865/25083571/9e1bd760-230c-11e7-9627-2198a75acbed.png)

**Comment by Talor-A** [comment] 2017-04-17 08:25
I do have another chroot already installed already though

**Comment by divx118** [comment] 2017-04-17 08:40
Hmm 4.3 Gb should be enough. Still I think it should be a mirror issue or you have a bad internet connection. See also https://www.reddit.com/r/Crouton/comments/3hfv2s/help_install_trusty_unity_crouton/

**Comment by Talor-A** [comment] 2017-04-17 08:45
@divx118 I've tried it almost a dozen times already, and I've used both my home and school networks. I guess anything's possible though. Maybe I should invest in a usb to ethernet converter. A mirror issue seems likely, but I used the one mentioned in that reddit thread just now and it still failed for both xenial and yakkety. thanks for the help though, it's greatly appreciated

**Comment by divx118** [comment] 2017-04-17 08:50
@Talor-A Do you have this since a recent chromeos update, it could also be that there is a bug in the beta that corrupts the download. You could try to change to dev, but if you want to go back to beta you will need a powerwash. From beta to dev a powerwash is not needed.

**Comment by zhangaa** [comment] 2017-04-17 13:11
@divx118 I think you are correct. Before I encountered the issue, I just updated the chrome os to the latest. The reason why I need to reinstall the chroot because the existing one does not work anymore (I can start the command line to update/upgrade, but the desktop didn't work -- both Windoemaker and KDE). It might be something in the latest chrome os "kills" the crouton or the chroot...
@Talor-A Did you get any updates on your chrome os please?
Well, how to deal with it if it was the case of chrome os itself then? 
Thanks all!

**Comment by divx118** [comment] 2017-04-17 13:17
@zhangaa which cromeos version do you currently have? If you are also on beta you can go to dev. To see if it is fixed there. If you want to go to stable you will need to backup your chroot first, because it will require a powerwash. If we are sure if it is chromeos at fault, we can take a look at the recent changes of the update see what is causing the problem and file a bug report if it doesn't already exists.

**Comment by zhangaa** [comment] 2017-04-18 01:20
@divx118 Hi Divx118, sorry for being late. I just checked the version of my current Chrome OS as following:
Version 57.0.2987.146 (64-bit)
Platform 9202.64.0 (Official Build) stable-channel butterfly
Firmware Google_Butterfly.2788.39.0
It seems I am using a stable version but not beta. Would it be the problem please? I did activate Dev mode before (and now I need Ctrl+D to bypass the white warning, so I think the dev mode is still active).
Any suggestion I should check/do please? Thanks !!

**Comment by divx118** [comment] 2017-04-18 06:18
@zhangaa dev mode is different from dev channel. dev mode is needed to be always active when you are running crouton, so you have access to the command line. Then you have stable, beta and dev channel those point to which releases you get from chromeos. On dev you get the most recent releases, but it can contain some bugs. stable should be as the word says be a stable chromeos release with all the bugs found in beta and dev channel fixed. Since you are on a different release then @Talor-A I doubt it will be chromeos at fault.
Did you already tried deleting the old faulty chroot and create a new one with another mirror as I suggested to @Talor-A?

**Comment by zhangaa** [comment] 2017-04-18 13:06
@divx118 Thank you so much for the details!! You are right, it could be a problem from the chrome os. And I can confirm my old (deleted) chroot worked well without any issue before the update of chrome os...
I tried to install a new one using your suggested mirrors above, and same error found.

**Comment by Leron4551** [comment] 2017-04-19 03:22
@divx118 , I've also tried removing all previous chroots and creating a new one with a few of the mirror links including the one you suggested. I'm running ChromeOS Version 58.0.3029.68 (Official Build) beta (64-bit)

**Comment by zhangaa** [comment] 2017-05-03 05:44
Hello Everyone! I just tried the powerwash. And guess what, it is working smoothly... 
Not sure why it happened...but yes the Linux is installed now.

**Comment by DennisLfromGA** [comment] 2018-07-16 22:48
Closing. Please update your chroot and try again, re-open if this issue is still a concern.

**Closed by DennisLfromGA** 2018-07-16 22:48 UTC
