### ISSUE TITLE
Can't get into ubuntu focal after upgrading

### ISSUE THREAD

**Issue by kevlu8** [dnschneid/crouton#4611] opened 2021-09-22 03:43 UTC
```
"sudo edit-chroot -all"
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20210907212903~master:9b281df5
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 14092.57.0 (Official Build) stable-channel coral 
kernel: Linux localhost 4.4.254-20726-g204ae1828356 #1 SMP PREEMPT Mon Sep 13 22:25:38 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
After upgrading from Ubuntu 16.04 to 18.04, I didn't encounter any issues, however when I updated to 20.04, it doesn't let me get into Ubuntu anymore. When I type `sudo startunity` it outputs this: 
```
Entering /mnt/stateful_partition/crouton/chroots/xenial...
Creating hwaudio group with GID 18...
Changing cdrom GID from 24 to 19...
Changing floppy GID from 25 to 11...
Changing plugdev GID from 46 to 85...
Changing uucp GID from 10 to 14...
Changing video GID from 44 to 27...
Moving sudo GID from 27 to 28...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
Build Operating System: linux Ubuntu
Current Operating System: Linux localhost 4.4.275-20726-g204ae1828356 #1 SMP PREEMPT Mon Sep 13 22:25:38 PDT 2021 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 4077568 verity payload=PARTUUID=368d6a76-adb4-3544-a04c-716611551422/PARTNROFF=1 hashtree=PARTUUID=368d6a76-adb4-3544-a04c-716611551422/PARTNROFF=1 hashstart=4077568 alg=sha256 root_hexdigest=0afd6cc0b3c35b675bf9dd666a8f21407d35bce17661c0901e6b943059d07d80 salt=7f9c502a533a73762f5cd1d3e39667656f85cb89206f89e48107575b8cabaa1b" noinitrd vt.global_cursor_default=0 kern_guid=368d6a76-adb4-3544-a04c-716611551422 add_efi_memmap boot=local noresume noswap i915.modeset=1 disablevmx=off  
Build Date: 06 July 2021  10:17:51AM
xorg-server 2:1.20.11-1ubuntu1~20.04.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.38.4
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Sep 21 21:37:43 2021
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1632281863.394795 sender=:1.29 -> destination=:1.320 serial=5505 reply_serial=2
   boolean true
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
WARNING: Kernel has no file descriptor comparison support: Function not implemented
(II) modeset(0): Initializing kms color map for depth 24, 8 bpc.
crouton: version 1-20210907212903~master:9b281df5
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 14092.57.0 (Official Build) stable-channel coral 
kernel: Linux localhost 4.4.254-20726-g204ae1828356 #1 SMP PREEMPT Mon Sep 13 22:25:38 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1632281873.484377 sender=:1.29 -> destination=:1.322 serial=5521 reply_serial=2
   boolean true
(II) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### If known, describe the steps to reproduce the issue:
Get unity, then `sudo apt install ubuntu-release-upgrader-core`. Then upgrade it 2 times, first to bionic then to focal by running `sudo do-release-upgrade` twice. When shut down then attempted to turn back on, it terminates the server and doens't let you in.

**Comment by BetaPictoris** [comment] 2021-09-22 05:22
Yet another duplicate of #4368.

**Closed** 2021-09-22 13:11 UTC
