### ISSUE TITLE
Openssl symbol lookup error when trying to encrypt an existing chroot

### ISSUE THREAD

**Issue by Kakise** [dnschneid/crouton#3738] opened 2018-04-19 10:13 UTC
```
chronos@localhost / $ sudo edit-chroot -all
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20180329190032~master:d287904a
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: keyboard,xorg,xiwi,xfce
host: version 10452.69.0 (Official Build) beta-channel lars 
kernel: Linux localhost 3.18.0-17025-g5eb931360066 #1 SMP PREEMPT Tue Apr 17 12:07:48 PDT 2018 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### Please describe your issue:
This error: `openssl: symbol lookup error: openssl: undefined symbol: RC5_32_set_key` is looping when I'm trying to encrypt my chroot using the command: `sudo sh ~/Downloads/crouton -n kali-rolling -e -u`

#### If known, describe the steps to reproduce the issue:
Create a kali-rolling chroot and then try to encrypt it.

**Comment by DennisLfromGA** [comment] 2018-04-19 16:53
Hmmm, try invoking `openssl` on its own and see if you still get any errors with something like this:

- `openssl passwd -1`

If you can enter a password (twice) successfully and it displays the 35 character password string as it should then something else might be going on.

Please try it and let us know.

-**DennisLfromGA**

**Comment by Kakise** [comment] 2018-04-21 10:04
Invoking `openssl passwd -1` works perfectly. I entered a password twice and got the 35 chars string.

**Comment by DennisLfromGA** [comment] 2018-04-21 22:11
Interesting, thanx.

When you open a shell session does it prompt you for a password?

If not maybe try to set one with `sudo chromeos-setdevpasswd` and see if you get any errors.
If that goes smoothly then try to encrypt your chroot again with:

`sudo sh ~/Downloads/crouton -n kali-rolling -e -u`

Please let us know if this helps.

-**DennisLfromGA**

**Comment by Kakise** [comment] 2018-04-22 16:43
`chronos@localhost / $ sudo chromeos-setdevpasswd
openssl: symbol lookup error: openssl: undefined symbol: RC5_32_set_key`

Well.... :/

**Comment by drinkcat** [comment] 2018-04-23 00:14
I cannot reproduce on the same release:
```
CHROMEOS_RELEASE_DESCRIPTION=10452.69.0 (Official Build) dev-channel test
```

Can you also try `sudo openssl passwd -1`?

**Comment by Kakise** [comment] 2018-04-23 08:16
@drinkcat I already did and it worked correctly.

Maybe if I switch to the dev-channel I won't have this problem anymore?

**Comment by drinkcat** [comment] 2018-04-23 08:29
@Kakise : I really mean to try to command with and without `sudo`. Not sure if the environment matters for whatever reason.

**Comment by Kakise** [comment] 2018-04-23 08:45
```
chronos@localhost / $ ldd /usr/bin/openssl
        linux-vdso.so.1 (0x00007ffc72d2b000)
        libssl.so.1.0.0 => /usr/local/lib64/libssl.so.1.0.0 (0x000075bfbb501000)
        libcrypto.so.1.0.0 => /usr/local/lib64/libcrypto.so.1.0.0 (0x000075bfbb0ab000)
        libc.so.6 => /usr/local/lib64/libc.so.6 (0x000075bfbad00000)
        libdl.so.2 => /lib64/libdl.so.2 (0x000075bfbaafc000)
        /lib64/ld-linux-x86-64.so.2 (0x000075bfbb773000)
chronos@localhost / $ sudo ldd /usr/bin/openssl
        linux-vdso.so.1 (0x00007ffe35bd7000)
        libssl.so.1.0.0 => /usr/local/lib64/libssl.so.1.0.0 (0x000074d284ec6000)
        libcrypto.so.1.0.0 => /usr/local/lib64/libcrypto.so.1.0.0 (0x000074d284a70000)
        libc.so.6 => /usr/local/lib64/libc.so.6 (0x000074d2846c5000)
        libdl.so.2 => /lib64/libdl.so.2 (0x000074d2844c1000)
        /lib64/ld-linux-x86-64.so.2 (0x000074d285138000)
chronos@localhost / $ 
```

I'm currently updating to dev-channel to see if it fixes the problem

**Comment by drinkcat** [comment] 2018-04-23 09:08
@Kakise : This is interesting, I wonder if there is a mismatch between the binaries in /usr and /usr/local. 

You could also try these:
```
sudo /usr/bin/openssl passwd -1
sudo /usr/local/bin/openssl passwd -1
```

Did you run `dev_install`? Can you try to remove openssl? (`emerge -aC openssl` maybe?)

I get this on my system, BTW (as root), all the libs are in /usr/lib64:
```
# ldd /usr/bin/openssl 
	linux-vdso.so.1 (0x00007fffe7dac000)
	libssl.so.1.0.0 => /usr/lib64/libssl.so.1.0.0 (0x00007dcf9f8df000)
	libcrypto.so.1.0.0 => /usr/lib64/libcrypto.so.1.0.0 (0x00007dcf9f521000)
	libc.so.6 => /lib64/libc.so.6 (0x00007dcf9f176000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007dcf9ef72000)
	libz.so.1 => /lib64/libz.so.1 (0x00007dcf9f8c4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007dcf9f731000)
```

**Comment by Kakise** [comment] 2018-04-23 10:33
```
chronos@localhost / $ sudo /usr/bin/openssl passwd -1
/usr/bin/openssl: symbol lookup error: /usr/bin/openssl: undefined symbol: RC5_32_set_key
chronos@localhost / $ sudo /usr/local/bin/openssl passwd -1
Password: 
chronos@localhost / $ ```

Here's what I have after executing `dev_install` (I never did it before)

```
chronos@localhost / $ sudo dev_install
Starting installation of developer packages.
First, we download the necessary files.
Downloading https://commondatastorage.googleapis.com/chromeos-dev-installer/board/lars/canary-R66-10452.69.0/packages/app-admin/python-updater-0.11.tbz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22120  100 22120    0     0  36989      0 --:--:-- --:--:-- --:--:-- 39289
Extracting /usr/local/portage/packages/app-admin/python-updater-0.11.tbz2
Downloading https://commondatastorage.googleapis.com/chromeos-dev-installer/board/lars/canary-R66-10452.69.0/packages/app-eselect/eselect-python-20140125-r1.tbz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 32281  100 32281    0     0  40401      0 --:--:-- --:--:-- --:--:-- 42197
Extracting /usr/local/portage/packages/app-eselect/eselect-python-20140125-r1.tbz2
Downloading https://commondatastorage.googleapis.com/chromeos-dev-installer/board/lars/canary-R66-10452.69.0/packages/app-misc/mime-types-9.tbz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24484  100 24484    0     0  45256      0 --:--:-- --:--:-- --:--:-- 48387
Extracting /usr/local/portage/packages/app-misc/mime-types-9.tbz2
Downloading https://commondatastorage.googleapis.com/chromeos-dev-installer/board/lars/canary-R66-10452.69.0/packages/app-misc/pax-utils-1.2.2.tbz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  117k  100  117k    0     0   148k      0 --:--:-- --:--:-- --:--:--  154k
Extracting /usr/local/portage/packages/app-misc/pax-utils-1.2.2.tbz2
Downloading https://commondatastorage.googleapis.com/chromeos-dev-installer/board/lars/canary-R66-10452.69.0/packages/dev-lang/python-2.7.10-r2.tbz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.4M  100 16.4M    0     0  6644k      0  0:00:02  0:00:02 --:--:-- 6742k
Extracting /usr/local/portage/packages/dev-lang/python-2.7.10-r2.tbz2
ERROR(dev_install): Could not extract package.
ERROR(dev_install): Command tar -C /usr/local -xjf /usr/local/portage/packages/dev-lang/python-2.7.10-r2.tbz2 failed.
chronos@localhost / $ ```

It seems that I can't use emerge: 
```chronos@localhost / $ sudo emerge -aC openssl 
sudo: emerge: command not found```

Also I had the idea to `ln -s` the working binary in place of the non working one but the filesystem is read only so....

**Comment by drinkcat** [comment] 2018-04-23 10:55
I'm really unclear how you ended up with a separate copy of openssl in `/usr/local`...

I suspect removing/moving away `/usr/local/lib64/libcrypto.so.1.0.0` will fix your problem.

You could also power-wash your Chromebook, that'll remove all these files in /usr/local (including your chroots and files in `Downloads`, so please back them up).

**Comment by Kakise** [comment] 2018-04-23 11:03
Removing `/usr/local/lib64/libcrypto.so.1.0.0` worked. But I power-washed my Chromebook right before installing crouton and a chroot so I really don't understand how the bug happened in the first place. (My Chromebook is 2 months old)

**Comment by Kakise** [comment] 2018-04-23 11:37
I powerwashed my Chromebook to see if it will change anything and the problem disappeared. Really weird.

**Comment by drinkcat** [comment] 2018-04-23 13:38
Ok. I'm going to close this. If this is a real issue I'm sure other people will end up reporting it, and we can reopen.

**Closed by drinkcat** 2018-04-23 13:38 UTC

**Comment by superdav42** [comment] 2018-09-29 17:28
I just ran into this issue also. Turns out the extra  /usr/local/bin/openssl came from chromebrew. It seems to always install this when it is installed. I removed it with `crew remove openssl` and then encryption worked fine, no need to powerwash.
