### ISSUE TITLE
Tooltip for Mobile Patent Suits! Please help!

### ISSUE THREAD

**Issue by nb25** [dnschneid/crouton#2557] opened 2016-04-29 23:00 UTC
Hi,

So I have been working with the Mobile Patent Suits by Mike Bostock’s Block 1153292: http://bl.ocks.org/mbostock/1153292 .

However, I am fairly new to D3 and cannot make the tooltip to work. I need each of the nodes to say something different as a tooltip (basically more details about each of the node).

Also, if it is possible, it would be nice to have an external file source, like a json file from where the data can be drawn rather than from the html file itself (by this I mean the parent/child data).

It would be absolutely great if you could help me out with this as it is kind of urgent.

Thank you in advance!!

**Comment by smibarber** [comment] 2016-04-30 00:28
Dupe of #262

**Closed by smibarber** 2016-04-30 00:28 UTC
