### ISSUE TITLE
chroot: failed to run command '/prepare.sh': Too many levels of symbolic links

### ISSUE THREAD

**Issue by amenokos** [dnschneid/crouton#4408] opened 2021-02-06 01:50 UTC
Although I've successfully installed a crouton on a USB Drive multiple times before, I'm having issues this go around. 

Steps I've taken:
Open Crosh --> shell
$ sudo su
# fdisk -l
# umount /dev/sdb1
# mkfs -t ext4 /dev/sdb1
unplug and replug USB drive
# exit
$ sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
$ sudo crouton -t audio,chrome,cli-extra,xfce-desktop,kde-desktop,extension,xorg,xiwi -p /media/removable/USB\ Drive

After a few moments, the script gets to "Moving bootstrap files into the chroot..."
Several "Installing ________ into the chroot" lines
...
Installing xbindkeysrc.scm into the chroot...
Installing xiwi.conf into the chroot...
Installing xorg-dummy.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xiwi into the chroot...
Installing xserverrc-local.example into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
chroot: failed to run command '/prepare.sh': Too many levels of symbolic links
Failed to complete chroot setup.
Unmounting /media/removable/USB Drive/chroots/xenial...

I've not run into this error before. Any ideas on how to resolve?

**Comment by DennisLfromGA** [comment] 2021-02-07 18:41
@amenokos,

I believe the issue is due to a recent change in Chrome OS that mounts external media with the 'nosymfollow' option.
See this comment for more details and a workaround: https://github.com/dnschneid/crouton/issues/4360#issuecomment-739508057

*Hope this helps,*
-**DennisLfromGA**

**Comment by amenokos** [comment] 2021-02-07 19:48
Thank you, DennisL. That seemed to solve the issue. Installing now...

**Comment by DennisLfromGA** [comment] 2021-02-07 21:11
Closing. Please re-open if this issue is still a concern.

**Closed by DennisLfromGA** 2021-02-07 21:11 UTC
