### ISSUE TITLE
xorg err when back to chrome os from xenial

### ISSUE THREAD

**Issue by blinderjay** [dnschneid/crouton#4089] opened 2019-07-09 13:42 UTC
#3805 when I back to chrome os:
the screen color do not display properly, color seems to be reversed, blue -> red,white -> black; while my extern monitor work  properly

![IMG_20190709_213630](https://user-images.githubusercontent.com/30920401/60892828-60889700-a292-11e9-8828-b667060ca6f9.jpg)

this is the err message:
```
(EE) BUG: triggered 'if (priv->num_active_touches == 0)'
(EE) BUG: ../../src/synaptics.c:2966 in UpdateTouchState()
(EE) 
(EE) Backtrace:
(EE) 0: /usr/lib/xorg/Xorg (xorg_backtrace+0x4e) [0x592a5246d6ce]
(EE) 1: /usr/lib/xorg/modules/input/synaptics_drv.so (0x791ec478f000+0x5b9c) [0x791ec4794b9c]
(EE) 2: /usr/lib/xorg/modules/input/synaptics_drv.so (0x791ec478f000+0x7682) [0x791ec4796682]
(EE) 3: /usr/lib/xorg/Xorg (0x592a522bb000+0x94268) [0x592a5234f268]
(EE) 4: /usr/lib/xorg/Xorg (0x592a522bb000+0xb9652) [0x592a52374652]
(EE) 5: /lib/x86_64-linux-gnu/libc.so.6 (0x791ecbc94000+0x354b0) [0x791ecbcc94b0]
(EE) 6: /lib/x86_64-linux-gnu/libc.so.6 (__select+0x33) [0x791ecbd915d3]
(EE) 7: /usr/lib/xorg/Xorg (WaitForSomething+0x1d7) [0x592a5246a3f7]
(EE) 8: /usr/lib/xorg/Xorg (0x592a522bb000+0x53bce) [0x592a5230ebce]
(EE) 9: /usr/lib/xorg/Xorg (0x592a522bb000+0x57e13) [0x592a52312e13]
(EE) 10: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf0) [0x791ecbcb4830]
(EE) 11: /usr/lib/xorg/Xorg (_start+0x29) [0x592a522fd069]
(EE) 
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
```

**Comment by visor841** [comment] 2019-07-18 15:11
This appears to be a duplicate of #3791

**Comment by DennisLfromGA** [comment] 2019-07-18 18:30
Yes, I believe so, duping to:

- Display colors in Chrome are corrupted after switching from chroot. #3791

**Closed by DennisLfromGA** 2019-07-18 18:30 UTC
