### ISSUE TITLE
Help needed with Tooltip

### ISSUE THREAD

**Issue by nb25** [dnschneid/crouton#2558] opened 2016-04-30 00:08 UTC
Hi! Can you tell me how to make a tooltip for this: https://gist.github.com/frolive10/0359d1617e06b95a6ad1
I can't seem to find the original link for this in bl.ocks.org as I forgot to bookmark it!
Any help would be greatly appreciated!
Thank you!

**Comment by smibarber** [comment] 2016-04-30 00:28
Dupe of #262

**Closed by smibarber** 2016-04-30 00:28 UTC
