### ISSUE TITLE
SD Card becomes invisible

### ISSUE THREAD

**Issue by josejuanisaac** [dnschneid/crouton#3871] opened 2018-08-27 19:56 UTC
```
sudo edit-chroot -all
name: bin
encrypted: no
/media/removable/EXTRA/chroots
Entering /media/removable/EXTRA/chroots/bin...
/media/removable/EXTRA/bin/enter-chroot: 513: /media/removable/EXTRA/bin/enter-chroot: cannot create /var/run/crouton/media/removable/EXTRA/chroots/bin/etc/crouton/name: Directory nonexistent
Unmounting /media/removable/EXTRA/chroots/bin...
name: chroots
encrypted: no
/media/removable/EXTRA/chroots
Entering /media/removable/EXTRA/chroots/chroots...
/media/removable/EXTRA/bin/enter-chroot: 513: /media/removable/EXTRA/bin/enter-chroot: cannot create /var/run/crouton/media/removable/EXTRA/chroots/chroots/etc/crouton/name: Directory nonexistent
Unmounting /media/removable/EXTRA/chroots/chroots...
name: xenial
encrypted: no
/media/removable/EXTRA/chroots
Entering /media/removable/EXTRA/chroots/xenial...
crouton: version 1-20180718130616~master:5d4c3014
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 10718.29.0 (Official Build) beta-channel terra 
kernel: Linux localhost 3.18.0-17855-g76eb986d8948 #1 SMP PREEMPT Wed Jun 20 23:21:24 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/EXTRA/chroots/xenial...
```

#### Invisible SD Card
I read somewhere in the issues that there is an issue with SD Cards becoming unmounted or invisible, but I cannot seem to find it again. I cannot find a repeatable pattern for when this happens, but every now and then the SD Card will become invisible to the Chromebook. Sometimes I am still able to see it using the shell in /media/removable, but more often than not it is also invisible there. I say *invisible* because when I remove the SD Card, the Chromebook prompts with the "Whoa careful there, you should dismount the SD Card properly". Might it just be because it is a San Disk? I also read somewhere that this brand might have issues with Chromebooks.

The only way I have been able to see the SD Card again is rebooting.

Any ideas?

**Comment by levistep32** [comment] 2018-08-31 20:30
I have a USB drive, I believe it's a San Disk as well. Everytime I plug it in it works, but I close and reopen the computer and it disappears from the Files app

**Comment by Mozzy-Diffuzer** [comment] 2018-09-07 04:09
i believe that Chromium tends to hide or unmount these drives whenever it goes into hibernation.

i tend to get this issue when i close my AsusC100P no matter whether  crouton is active or not.
The best i can do is exit crouton every time i close the chromebook and restart Chromium if the drive has disappeared again..

This seems to be something that was introduced to Chromium some time ago, after crouton was released.
Not sure if there is a fix coming outside of Google dev themselves.

**Comment by kapilhp** [comment] 2018-09-19 04:11
If I recall correctly, the problem is with re-mounting the drive inside crouton (with a bind mount). If you do that, then ChromeOS will unmount this drive from its /media location before sleeping, but it will remain mounted inside crouton if that is still running. When you wake-up the system, ChromeOS will not be able to mount the drive since it is already mounted under crouton. At this point it is "invisible" in the sense that it is still mounted, but it not visible to the ChromeOS files manager (since the mount point is not in that app's default locations). Which is why you get a warning message when you "pop" the drive.

One way to avoid this problem is to avoid re-mounting the drive inside crouton. How you do that may depend on the file manager app you are running inside crouton if any.

The second problem, that the drive sometimes "disappears" even without using crouton seems to be some hardware/kernel issue which I have faced occasionally. This is cured by a drive "pop" or at worst a reboot.

**Comment by isr** [comment] 2018-09-26 23:51
Here is what I do for ensuring additional mounts stay active through multiple sleep/resume cycles.

**Don't rely on ChromeOS's mountpoint**. For the exact reason as mentioned above (chromeos will automatically unmount any external storage mounts, and then try to remount them upon resume).

Instead, for any additional storage you want to use (usb, sd, other partitions within the internal emmc/ssd), **mount it yourself**.

By that I don't mean `mount -bind ...`. I mean make a complete new mount. You don't have to unmount the chromeos-mountpoint. If you like, you can leave it there, so you can still browse through the storage device with the ChromeOS "Files" app.  You **can** mount the same device twice on linux (just don`t write to it from both mountpoints).

You can also use different mount permissions on your mount (than the more restrictive ones chromeos uses by default). So you can have exec enabled, etc.

The mount you made will remain untouched by chromeos's (ahem) overhelpful userspace disk manager.

Problem solved :)

**Comment by DennisLfromGA** [comment] 2018-09-26 23:54
Closing. Please re-open if this issue is still a concern.

**Closed** 2018-09-26 23:54 UTC
