### ISSUE TITLE
I installed chroot w/o Xiwi.  Can I add it subsequently? If so...how?

### ISSUE THREAD

**Issue by Caedmon26** [dnschneid/crouton#3229] opened 2017-05-11 21:43 UTC
```Please respond via email if possible: caedmon26@gmail.com
Please paste the output of the following command here: sudo edit-chroot -all

hronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9460.34.0 (Official Build) dev-channel celes 
kernel: Linux localhost 3.18.0-14565-g46be31c1033f #1 SMP PREEMPT Tue May 9 14:25:01 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

**Comment by DennisLfromGA** [comment] 2017-05-11 23:27
@Caedmon26,

Sure, just update your chroot adding the 'xiwi' target at the same time like this:

`sudo sh ~/Downloads/crouton -n xenial -t xiwi -u`

That will make 'xiwi' the new default xmethod so to launch your desktop with 'xorg' use:

`sudo startxfce4 -X xorg`

Also with 'xiwi' installed you can launch it in a window by default or in fullscreen with `-X xiwi-fullscreen` or in a tab with `-X xiwi-tab`

*Hope this helps,*
-**DennisL**

**Comment by Caedmon26** [comment] 2017-05-11 23:40
Thank you.  Will it have to do the whole process over again?  It took about
25 mins.  At first switching wasn't working, I'd switch over to chrome os
and upon returning to ubuntu i got some kind of login screen.  But now it's
switching back and forth nicely.  It's mildly satisfying to be running
firefox with flash on a chromebook.  There was some forced update today
that killed my access to the google play store and all the apps I had put
on this machine.  So I went this route.

**Comment by Caedmon26** [comment] 2017-05-11 23:42
It's a samsung chromebook 3 that still has the play store access in
development for secure channel.  I switched to developer channel which gave
me access to play store apps...but now it doesn't seem available on either
beta or developer channel.

**Comment by DennisLfromGA** [comment] 2017-05-12 00:24
@Caedmon26,

> Will it have to do the whole process over again?

Not exactly, it does go through a crouton update and chroot update but it doesn't take nearly as long as the initial install.

> I switched to developer channel which gave
me access to play store apps...but now it doesn't seem available on either
beta or developer channel.

Yup, it was rolled out accidentally and now pulled I've heard.
Such is life on the beta/dev channels though.

CBC: [Samsung Chromebook 11 G5 on dev channel. Lost Play Store after new update.](https://productforums.google.com/forum/#!msg/chromebook-central/aDHtI98dSHg/t7zsxE-dCQAJ)

reddit/chromeos: [Just got this notification after updating, but no Play Store or option to activate it.. (Acer Chromebook 14)](https://www.reddit.com/r/chromeos/comments/6ais6z/just_got_this_notification_after_updating_but_no/?st=j2l3hpmd&sh=bc8bc72e)

*Hope this helps,*
-**DennisL**

**Comment by Caedmon26** [comment] 2017-05-12 21:00
ty

**Comment by DennisLfromGA** [comment] 2017-05-12 22:41
No problem.
I'll close this now since I think the issue is resolved.

**Closed by DennisLfromGA** 2017-05-12 22:41 UTC
